### ISSUE TITLE
Lexically-Constrained Decoding in Sockeye 3

### ISSUE THREAD

**Issue by RamoramaInteractive** [awslabs/sockeye#1001]
Does or will Sockeye 3 still support Lexically-Constrained Decoding or should I switch to FairSeq?

How compatible are Sockeye and FairSeq together?

**Comment by fhieber** [comment]
Hi @RamoramaInteractive, Sockeye 3 does no longer support lexical constrained decoding. Sockeye models are currently not compatible with fairseq.
