### ISSUE TITLE
Mean pooling function.

### ISSUE THREAD

**Issue by alvations** [awslabs/sockeye#1003]
Hi sockeye dev, if we want to add a [mean pooling function](https://paperswithcode.com/method/generalized-mean-pooling) for the pytorch backend sockeye, where should the function be included? Or is there already a similar function in sockeye?

```python 
def mean_pooling(enc_feats, src_masks=None):
    """
    :param enc_feats: Tensor x Batch x Channel
    :param src_masks: Batch x Tensor 
    """
    if src_masks is None:
        enc_feats = enc_feats.mean(0)
    else:
        src_masks = (~src_masks).transpose(0, 1).type_as(enc_feats)
        enc_feats = (
            (enc_feats / src_masks.sum(0)[None, :, None]) * src_masks[:, :, None]
        ).sum(0)
    return enc_feats
```

**Comment by fhieber** [comment]
It does not exist in Sockeye yet. The location of that function depends on where in the model you want to use it. Where do you want to apply mean pooling?

**Comment by mjdenkowski** [comment]
Closing for now.  Feel free to reopen if you have other questions.
