### ISSUE TITLE
Sequential poisoning function

### ISSUE THREAD

**Issue by alvations** [awslabs/sockeye#1005]
Hi sockeye dev, if we want to add [sequential token poisoning](https://arxiv.org/pdf/2004.03728.pdf) function for the pytorch backend sockeye, where should the function be included? Or is there already a similar function in sockeye?

There's a version from https://github.com/raymondhs/constrained-levt/blob/master/fairseq/models/iterative_nonautoregressive_transformer.py#L11 that looks like this:

```python
def _sequential_poisoning(s, V, beta=0.33, bos=2, eos=3, pad=1):
    """
    :param s: input batch
    : V: vocabulary size
    """
    rand_words = torch.randint(low=4, high=V, size=s.size(), device=s.device)
    choices = torch.rand(size=s.size(), device=s.device)
    choices.masked_fill_((s == pad) | (s == bos) | (s == eos), 1)

    replace = choices < beta / 3
    repeat = (choices >= beta / 3) & (choices < beta * 2 / 3)
    swap = (choices >= beta * 2 / 3) & (choices < beta)
    safe = choices >= beta

    for i in range(s.size(1) - 1):
        rand_word = rand_words[:, i]
        next_word = s[:, i + 1]
        self_word = s[:, i]

        replace_i = replace[:, i]
        swap_i = swap[:, i] & (next_word != 3)
        repeat_i = repeat[:, i] & (next_word != 3)
        safe_i = safe[:, i] | ((next_word == 3) & (~replace_i))

        s[:, i] = (
            self_word * (safe_i | repeat_i).long()
            + next_word * swap_i.long()
            + rand_word * replace_i.long()
        )
        s[:, i + 1] = (
            next_word * (safe_i | replace_i).long()
            + self_word * (swap_i | repeat_i).long()
        )
    return s
```

**Comment by mjdenkowski** [comment]
To modify batches on the fly, you can add code [here](https://github.com/awslabs/sockeye/blob/main/sockeye/training_pt.py#L313) after we load the current batch onto the GPU and before we run the forward-backward pass.

[This code](https://github.com/awslabs/sockeye/blob/main/sockeye/data_io_pt.py#L1902-L1959) is the reference for how batches are structured: tensors of vocabulary IDs with special symbols (BOS, EOS, PAD) inserted at the start/end of sequences.

**Comment by mjdenkowski** [comment]
Closing for now.  Feel free to reopen if you have other questions.
