### ISSUE TITLE
Generating only the best and last parameters

### ISSUE THREAD

**Issue by RamoramaInteractive** [awslabs/sockeye#1007]
Which parameter can I use when I only want to generate the best and last params, in order to save storage space?

**Comment by mjdenkowski** [comment]
The training arguments to control this are:
```
  --keep-last-params KEEP_LAST_PARAMS
                        Keep only the last n params files, use -1 to keep all files. Default: -1
  --cache-last-best-params CACHE_LAST_BEST_PARAMS
                        Cache the last n best params files, as distinct from the last n in sequence. Use 0 or negative to disable. Default: 0
```

**Comment by RamoramaInteractive** [comment]
Thank you, @mjdenkowski. It's working!

Are there also parameters to reduce the decode.output.0.x files as well?

**Comment by mjdenkowski** [comment]
Currently there is no option to clean up decoding outputs.

**Comment by RamoramaInteractive** [comment]
Thanks again. It's a pity that the decoding outputs can't be reduced so easy.

Question is answered.

**Comment by tdomhan** [comment]
Do you actually need the checkpoint BLEU scores? If not you can disable the checkpoint decoder: `--decode-and-evaluate 0`.

**Comment by RamoramaInteractive** [comment]
Yes, I need the BLUE scores to evaluate my translation.
