### ISSUE TITLE
Dictionary or JSON as Input for a trained model with source factors

### ISSUE THREAD

**Issue by RamoramaInteractive** [awslabs/sockeye#1008]
With respect to closed issue https://github.com/awslabs/sockeye/issues/999

can I give a dictionary or JSON file as additional input to the test files, instead of annotating the test files?

I mean, in my case it should be easy to change the target vocabulary.

A dictionary like 

> { source|1 : Quelle|2,
>        test|1 : Test|2      
>                 ...              }

**Comment by tdomhan** [comment]
There's the `--json-input` flag for `sockeye-translate`.

Details for where this is parsed are here:
https://github.com/awslabs/sockeye/blob/main/sockeye/inference_pt.py#L241

If I recall correctly the format is:
```
{'text': 'Test test', 
 'factors': ['f1 f1' , 'f2 f2'], }
```

Is that what you are looking for?

**Comment by RamoramaInteractive** [comment]
Yes, I was looking for something like this. Thank you!

**Comment by RamoramaInteractive** [comment]
> There's the `--json-input` flag for `sockeye-translate`.
> 
> Details for where this is parsed are here: https://github.com/awslabs/sockeye/blob/main/sockeye/inference_pt.py#L241
> 
> If I recall correctly the format is:
> 
> ```
> {'text': 'Test test', 
>  'factors': ['f1 f1' , 'f2 f2'], }
> ```
> 
> Is that what you are looking for?

Can I also just give as text input the source and target terms with its corresponding source factors or must it be complete text lines?

**Comment by tdomhan** [comment]
You must provide the full input as factors are required for all input tokens.
