### ISSUE TITLE
Source sequences are not token-parallel: How to read sequences

### ISSUE THREAD

**Issue by RamoramaInteractive** [awslabs/sockeye#1013]
After preparing my data, I've received this error message

sockeye.utils.SockeyeError: Source sequences are not token-parallel: [[17018, 330, 12, 1807, 179, 2210, 47, 11, 33371, 1455, 1511, 45, 14, 1086, 63, 198, 387, 8, 424, 5, 3], [1479, 1479, 1479, 201, 189, 189, 1479, 1479, 1479, 1479, 1479, 1479, 1479, 1479, 1479, 1479, 1479, 1479, 1479, 3]]

Are these the lines of train.en and valid.en?

Here is the way how I replaced terms with source factors:

> diam@@ onds Kar@@ o @-@ Karten

to

> 1 1 2 2 2 2

1 are the source terms and 2 the target terms. Everything else is zero.

I have words like "move" which I had annotated differently"

> move bewegen
> move deal
> move Zug

**Comment by RamoramaInteractive** [comment]
How to read and fix the source sequences? 

sockeye.utils.SockeyeError: Source sequences are not token-parallel: [[117, 16, 206, 4, 102, 85, 16, 10517, 11, 138, 34, 4, 8, 446, 4, 14, 413, 8, 1834, 642, 56, 194, 12, 1615, 537, 1216, 12, 41, 5, 3], [1479, 1479, 1479, 1479, 1479, 1479, 1479, 1479, 1479, 201, 189, 1479, 1479, 1479, 201, 1479, 1479, 1479, 1479, 201, 1479, 1479, 201, 1479, 1479, 1479, 1479, 1479, 1479, 1479, 1479, 3]]

**Comment by fhieber** [comment]
The message tells you that the two token id sequences that are supposed to be parallel, are not. Sequence 1 has 30 tokens, sequence 2 has 32 tokens. You need to check your input files.

**Comment by RamoramaInteractive** [comment]
Alright, the numbers are token IDs and the arrays are sequences. 

Just for better understanding: For example if I have the source term "move" with the token id 1 and I add in each line another target terms like "bewegen", "deal" and "Zug", could this cause the `Source sequences are not token-parallel` error?

After I inserted the target terms to the source terms in the copies of the train.en and valid.en data

```
awk -i inplace '(NR==FNR){a[$1];next}
    FNR in a { gsub(/\<A@@ ces\>/,"& A@@ sse") }
     1
    ' <(shuf -n $n_number -i 1-$(wc -l < $file)) $file
```

I've replaced the numbers terms via sed:

```
...
sed -i 's/[0-9]/X/Ig' $file
sed -i 's/\<A@@ ce\>/1 1/Ig' $file
...
sed -i 's/\<A@@ ss\>/2 2/Ig' $file
...
```

Then I've replaced all the tokens with the numbers 0 (default term), 1 (source term), 2 (target term)

`sed -Ei 's/\<(1)\>|\<(2)\>/\n&/g; s/(^| )\S+/\10/g; s/\n//g' file`

**Comment by fhieber** [comment]
We can't debug your data preparation. You might want to check all your input files for token parallelism with something like this:
```
paste <(awk '{print NF}' DATA1) <(awk '{print NF}' DATA2) | awk '$1 != $2' | wc -l
```
which should give you `0` if DATA1 and DATA2 are whitespace-separated token parallel.

**Comment by RamoramaInteractive** [comment]
Thank you for this code. I have to debug the error now.

**Comment by RamoramaInteractive** [comment]
n_*.en = data where the target terms are inserted
s_*.en = n_*.en data where the terms are replaced with 0, 1 and 2.

` paste <(awk '{print NF}' s_train.en) <(awk '{print NF}' n_train.en) | awk '$1 != $2' | wc -l`
Output: 0

`paste <(awk '{print NF}' s_valid.en) <(awk '{print NF}' n_valid.en) | awk '$1 != $2' | wc -l`
Output: 0

I think the error comes from the sed replacement.

**Comment by RamoramaInteractive** [comment]
The problem is almost solved, but I've a problem with the validation data:

`Differing arguments: validation_source, validation_target.`

The command

`paste <(awk '{print NF}' s_valid.en) <(awk '{print NF}' n_valid.en) | awk '$1 != $2' | wc -l`

still says 0 and nothing has changed of the line. 

The lines remained the same.

Do you know what the most common causes might be?
I pressume, that there are some target terms inserted, but they have the number 0.
