### ISSUE TITLE
Mismatch in arguments for training continuation. Differing arguments: validation_target, validation_source

### ISSUE THREAD

**Issue by RamoramaInteractive** [awslabs/sockeye#1017]
This issue relates to another issue: https://github.com/awslabs/sockeye/issues/999

I want to add source factors to my model. 

I've edited the English source files of both the training file and the valid file by appending a target term "verschieben":

Original example sentence in train and valid: 

> Moreover , corruption is the ban@@ e of development everywhere , so new governments should move fast to establish institutions and procedures to fight it .

After appending "verschieben"

> Moreover , corruption is the ban@@ e of development everywhere , so new governments should move verschieben fast to establish institutions and procedures to fight it .

Then I created for train and valid a tokenized version:

> 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0

0 are the default terms, 1 are the source terms and 2 are the target terms.

I can prepare the data without any problems:

```
sockeye-prepare-data \
    -s examples/translation/wmt17_en_de/t_train.en \
    -t examples/translation/wmt17_en_de/t_train.de --shared-vocab \
    -sf examples/translation/wmt17_en_de/s_train.en \
    --source-factors-use-source-vocab true \
    --word-min-count 2 --pad-vocab-to-multiple-of 8 --max-seq-len 95 \
    --num-samples-per-shard 10000000 --output prepared --max-processes $(nproc)
```

But when I try to train my modell

```
sockeye-train -d prepared \
-vs examples/translation/wmt17_en_de/t_valid.en \
-vt examples/translation/wmt17_en_de/t_valid.de \
--shared-vocab \
-o amazon_model \
--min-num-epochs 1 \
--max-num-epochs 1 \
--batch-size 560 \
--transformer-attention-heads 8:8 \
--transformer-activation-type 'relu':'relu' \
--transformer-dropout-act 0.1:0.1 \
--transformer-dropout-attention 0.1:0.1 \
--transformer-dropout-prepost 0.1:0.1 \
--transformer-feed-forward-num-hidden 2048:2048 \
--transformer-model-size 512 --num-layers 2:2 \
--transformer-positional-embedding-type fixed \
--transformer-preprocess n:n \
--transformer-postprocess dr:dr \
--target-factors-num-embed 1 \
--source-factors-num-embed 1 \
--dtype float32 \
--max-seq-len 101:101 \
--num-words 32302:32302 \
--num-embed 512:512 \
--label-smoothing 0.1 \
--embed-dropout 0.0:0.0 \
--loss cross-entropy \
--keep-last-params 1 \
--cache-last-best-params 1 \
--validation-source-factors examples/translation/wmt17_en_de/s_valid.en
```

I get the error message 

> Mismatch in arguments for training continuation. Differing arguments: validation_target, validation_source

The files for the target language German remain unchanged. What did I wrong?

**Comment by fhieber** [comment]
Did `amazon_model` exist before? The error is telling you that it's trying to continue training from an existing model folder but you are supplying non-matching arguments, namely your inputs for validation_target & source have changed.
So you should use a different output folder, or delete the existing one, or use the `--overwrite-output` flag.

**Comment by RamoramaInteractive** [comment]
Thank you so much, @fhieber! My problem is solved! 😃
