### ISSUE TITLE
I have challenges during sockeye training

### ISSUE THREAD

**Issue by etexaco123** [awslabs/sockeye#1034]
Hi ,
I am doing a training with your toolkit, but it gives me an error that "sockeye.utils.SockeyeError: Empty target validation sentence."
I first did byte pair encoding then prepared my data using "sockeye-prepare-data" on the training data then because i am using cpu I used the 
"sockeye-train" on the prepared data and dev set that is byte pair encoded as the validation source and target and enabled the "--use-cpu" parameter. but I Keep getting error messages when trying to train, i don't know what to do, I wish it is possible to have an online meeting so I can better explain because I have some questions. I really need help because i don't want to fail my final year thesis. find the snapshot below. 
![training_error1](https://user-images.githubusercontent.com/55185779/160273291-6678c66c-1f11-46af-bfd8-a2f3fe3e4344.png)
.

**Comment by mjdenkowski** [comment]
Hi @etexaco123,

This error message indicates that at least one target sentence has length zero (no tokens).

This can be addressed by writing/running a pre-processing script that reads pairs of source-target lines and only outputs line pairs where both source and target are non-empty (`len(sentence.strip()) > 0`).
