### ISSUE TITLE
How to plot attention matrix

### ISSUE THREAD

**Issue by etexaco123** [awslabs/sockeye#1049]
1-How can I plot the transformer attention matrices of the translated text in sockeye?
2-How can I translate a test file containing about 10 lines of a language after training my model with sockeye?
3-How can I plot my BLEU score, loss, perplexity, learning rate scores after training?
4-can sockeye do Minimum risk training for neural machine translations using transformers? if so how can I do it?
5-How can I know the number of shards to set my  data preparation

I have already looked at the documentation not much info if you can specify the exact command for me it will be helpful
how can I view the list of parameters/ description of sockeye-train, sockeye-prepare-data, sockeye-translate, sockeye-average and sockeye-embedding?

**Comment by mjdenkowski** [comment]
For more information on training, monitoring, and evaluating Sockeye models, you can take a look at our tutorials: [WMT German to English news translation](https://github.com/awslabs/sockeye/blob/main/docs/tutorials/wmt.md) and [Large data: WMT English-German 2014](https://github.com/awslabs/sockeye/blob/main/docs/tutorials/wmt_large.md).

To see a detailed list of arguments for any command, you can add the `-h` flag. For example: `sockeye-train -h`

Sockeye 3 does not implement minimum risk training or attention visualization.
