### ISSUE TITLE
BrokenPipeError: [Errno 32]

### ISSUE THREAD

**Issue by whher** [awslabs/sockeye#1065]
Hi,

I followed this tutorial and trained a de-bar model: https://github.com/awslabs/sockeye/blob/main/docs/tutorials/wmt.md

However, I encountered a Broken Pipe error during translation. My command was:
`echo "ich weiss es nicht ." |
  python -m apply_bpe -c bpe.codes --vocabulary bpe.vocab.bar
                                   --vocabulary-threshold 50 |
  python -m sockeye.translate -m de-bar-base-model 2>/dev/null |
  sed -r 's/@@( |$)//g'`

And the error I received was:
`Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/nmt-sockeye-de-bar/sockeye/sockeye/translate.py", line 25, in <module>
    import torch as pt
ModuleNotFoundError: No module named 'torch'
/home/jovyan/nmt-sockeye-de-bar/sockeye/subword-nmt/apply_bpe.py:393: DeprecationWarning: this script's location has moved to /home/jovyan/nmt-sockeye-de-bar/sockeye/subword-nmt/subword_nmt. This symbolic link will be removed in a future version. Please point to the new location, or install the package and use the command 'subword-nmt'
  warnings.warn(
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/nmt-sockeye-de-bar/sockeye/subword-nmt/apply_bpe.py", line 446, in <module>
    args.output.write(bpe.process_line(line, args.dropout))
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe`

I have reached out to subword-nmt (https://github.com/rsennrich/subword-nmt/issues/117) and we concluded that this error might originate from sockeye.
Is there any way to counter this? Thank you!

**Comment by mjdenkowski** [comment]
It looks like PyTorch may not be installed: `ModuleNotFoundError: No module named 'torch'`.

If you have a local copy of the Sockeye code (`git clone https://github.com/awslabs/sockeye.git`), you can run `pip install -r requirements/requirements.txt` to install PyTorch and Sockeye's other dependencies. If not, you can run `pip install torch`.

**Comment by whher** [comment]
Sorry, I inserted the wrong error (there I removed the 2>/dev/null in the execution just for testing). Torch was already installed.

The error was:
`Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/nmt-sockeye-de-bar/sockeye/subword-nmt/apply_bpe.py", line 446, in <module>
    args.output.write(bpe.process_line(line, args.dropout))
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe`

**Comment by mjdenkowski** [comment]
Can you run the pieces of this command individually?
```bash
echo "ich weiss es nicht ." >input.tok
python -m apply_bpe -c bpe.codes --vocabulary bpe.vocab.bar --vocabulary-threshold 50 <input.tok >input.bpe
python -m sockeye.translate -m de-bar-base-model -i input.bpe -o output.bpe
sed -r 's/@@( |$)//g' <output.bpe >output.tok
```

**Comment by whher** [comment]
The first two lines were successful. I received error from executing the 3rd line.

Executed:
`python -m sockeye.translate -m de-bar-base-model -i input.bpe -o output.bpe`

Got:
`Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/nmt-sockeye-de-bar/sockeye/sockeye/translate.py", line 25, in <module>
    import torch as pt
ModuleNotFoundError: No module named 'torch'`

Even though I am certain that torch was installed. If I add "2>/dev/null", I won't see this error, but I don't get output.bpe either.

**Comment by fhieber** [comment]
it looks like the Python environment you are running `sockeye.translate` with does not have torch installed. Maybe you installed it to another environment? I would expect that running `python -c 'import torch'` would give you the same error.

**Comment by whher** [comment]
I re-installed `torch` and it worked. Seems like I have to install `torch` every time I enter the environment so that `sockeye.translate` is able to run.

Thank you both for the clarification!
