### ISSUE TITLE
How to avoid out of memory errors on large models

### ISSUE THREAD

**Issue by ejkitchen** [awslabs/sockeye#1070]
I keep running out of memory when training on a DGX with 8x80Gb A100. This may not be a question for this forum (if not, can someone guide me as to where I should post?). Let's assume I have the sockeye-train parameters below. Instead of running experiment after experiment until I find something that fits in memory, is there a way for me to calculate this upfront?

I am assuming memory consumption will be a factor of --num-layers, --transformer-model-size, --transformer-feed-forward-num-hidden and --batch-size. But does anyone have a simple calculation that could at least give me some indication of what is the max for each of those parameters I can use for 1 DGX configured as above? Also right now it appears I can only do 3.1 billion params on a single DGX if I play around with those parameters. Is it also possible to get an upfront calculation of the # of parameters? Instead of memory, should I be focusing on # of parameters? Whenever I use a combination that goes above 3.2B, I run into issues. What I do right now is change the values of the parameters below, wait for everything to start then open up the log file and monitor it until # of parameters shows up, and if it's over 3.2B, I bring things down. 

Also, does sockeye have a good guide on how to train 1 model on multiple DGX boxes in a POD or is that more of a Pytorch question?

sample parameters:

torchrun --nproc_per_node 8 -m sockeye-train \
    -d /data/prepared \
    -vs /data/en-de.de \
    -vt /data/en-de.en \
    -o /model/48-24 \
    --num-layers="48:24" \
    --transformer-model-size 1024 --transformer-attention-heads 16 --transformer-feed-forward-num-hidden 4096 \
    --batch-size 1500 --update-interval 10 --checkpoint-interval 1000 \
    --initial-learning-rate 0.0005 \
    --keep-last-params 999 --max-num-epochs 1000 --max-num-checkpoint-not-improved 99 \
    --neural-vocab-selection logit_max --bow-task-weight .9 \
    --dist --decode-and-evaluate -1 --seed 1 --amp --dtype float16 --max-seq-len 150

**Comment by mjdenkowski** [comment]
Optimizing memory usage usually involves some parameter sweeps similar to what you're describing. The main variables are model size (including number of layers, etc.) and the trade-off between batch size and update interval. You can collect data points quickly by looping over different settings using a small number of maximum updates (e.g., `--max-updates 100`).

One thing to note is that training may be faster with a smaller batch size and larger update interval. When PyTorch is low on memory, it runs garbage collection. If batches barely fit into memory, frequent garbage collection may slow down training compared to using smaller batches with a larger update interval (same effective batch size). An initial parameter sweep to find the right memory usage for a given model can save time during training.

You can also fit larger models into memory with [DeepSpeed](https://github.com/microsoft/DeepSpeed). Running [Sockeye+DeepSpeed](https://github.com/awslabs/sockeye/blob/main/CHANGELOG.md#3120) automatically activates ZeRO stage 1 which shards optimizer states across ranks. There's also an option to run the entire model in BF16, which is recommended for larger models (`--deepspeed-bf16`).

Both PyTorch and DeepSpeed support multi-node training. If you have two nodes with a shared filesystem and all TCP ports open to each other (requirement for NCCL), you can run PyTorch distributed training with commands like the following:

- Node 1: `torchrun --nnodes 2 --nproc_per_node 8 --master_addr 192.168.0.1 --master_port 9000 --node_rank 0 --no_python sockeye-train ...`
- Node 2: `torchrun --nnodes 2 --nproc_per_node 8 --master_addr 192.168.0.1 --master_port 9000 --node_rank 1 --no_python sockeye-train ...`

For DeepSpeed, the nodes also need to be set up for passwordless SSH. Nodes and number of processes per node are specified in a `hostfile` like this one:
```
192.168.0.1 slots=8
192.168.0.2 slots=8
```
Then you can launch DeepSpeed distributed training from node 1 using the `hostfile`:
`deepspeed --hostfile hostfile --no_python /path/to/sockeye-train ...`

**Comment by ejkitchen** [comment]
Hello, thanks for the quick response!

As you mention above, we did reduce the batch size until we found the minimum, but again we have to run each time to find the magic minimum batch size before we get an error saying it's too small but again trial and error with no method of calculating upfront. 

I am not sure what precisely --max-updates does apart from trying to deduce from the English what it means. I only found this reference in your documentation: "You can specify a maximum number of updates/batches using --max-updates.". Does this stop after 100 updates and what is meant by an update? Is that the printout during epochs and batch outputs from the running log? 

Is this primarily meant to be used in this scenario?

For hyperparameter test in list:
   run train --max-updates 100 with hyperparameter X with value Y
   if fails, try smaller Y, next.

We are trying the --deepspeed-bf16 option right now.

Is there any documentation on the parameters with mode detailed explanations beyond sockeye-train --help? For example--deepspeed-bf16 is not in the help file and google search simply points to the code where sockeye returns an error if you use deepspeed-bf16 with --amp. Is there not a detailed guide somewhere?

Is there a forum in the Pytorch community you could recommend for these types of questions or this is the place to ask?

Again, thanks for your help!
