### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by Verkolle** [awslabs/sockeye#1080]
Hello!

I'm having a reoccurring issue when sockeye.train reaches a checkpoint. Up until that point the training process seems to be going fine, but when it comes to saving the model I get the following error.

![Screenshot 2023-01-16 205227](https://user-images.githubusercontent.com/64806202/212748509-0f7905cc-862a-46c2-a535-8606c17a3635.png)

My source and target files have the same line count as does the validation set, so I'm unsure as to what the problem could be.

**Comment by mjdenkowski** [comment]
This looks like the NumPy compatibility issue we addressed in PR #1077.

Updating to the latest commit of Sockeye should resolve the issue.

Best,
Michael

**Comment by bricksdont** [comment]
Hi all, could you perhaps make a new Pypi release so that regular installing with pip works again?

**Comment by fhieber** [comment]
Of course, sorry about the delay. 3.1.31 should be on pypi shortly (see https://github.com/awslabs/sockeye/actions/runs/4062721441)

**Comment by bricksdont** [comment]
thank you @fhieber and have a nice day everyone
