### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by Verkolle** [awslabs/sockeye#1081]
Hello!

After training the model for a while I have been encountering an unicode error when trying to call the "sockeye.translate" command. The training process went through without issues though. All the files that I passed to the training and translate commands were using "utf-8" encoding as per the instructions.

![Screenshot 2023-01-18 003248](https://user-images.githubusercontent.com/64806202/213027990-56304fc8-5eff-4b5e-903a-7bc2a334099e.png)

**Comment by mjdenkowski** [comment]
It looks like you're running on Windows. Sockeye is not officially supported or tested on Windows.

One way to proceed would be to install CUDA on the Windows Subsystem for Linux. [Microsoft](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl) and [NVIDIA](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#getting-started-with-cuda-on-wsl) have published some documentation about setting up this type of environment. This should enable installing Python and PyTorch via [Miniconda](https://docs.conda.io/en/latest/miniconda.html).

Best,
Michael

**Comment by Verkolle** [comment]
Thank you for the help!
