### ISSUE TITLE
Speed up decoding time

### ISSUE THREAD

**Issue by summerqing** [awslabs/sockeye#148]
Hi, our team has been trying to use mxnet translation model in our product, however, the decoding speed is not satisfied.  Any suggestion to speed up translating time ?

**Comment by fhieber** [comment]
Hi, thanks for submitting an issue.
What speeds are you observing and how long are the sentences you want to decode?
Are you decoding on a GPU or CPU?
If you are using the latter, it is helpful to install MXNet with the MKL library.

**Comment by tdomhan** [comment]
closing for now. Feel free to reopen if you have additional questions.
