### ISSUE TITLE
[Minor] Parameter mismatch for default value for normalize-loss

### ISSUE THREAD

**Issue by orchidmajumder** [awslabs/sockeye#153]
Hi, I might be wrong but I think if the default value for a parameter is set to False, then action=store_true contradicts that. If user does not pass this value, will it be set to true or false?

Code here: https://github.com/awslabs/sockeye/blob/master/sockeye/arguments.py#L455-L456
I am talking about the parameter called 'normalize-loss'.

**Comment by tdomhan** [comment]
Hi! it's off by default (`False`) and when a user specifies `--normalize-loss` it will be turned on (`normalize_loss=True`).

**Comment by orchidmajumder** [comment]
Thanks @tdomhan  :) It's clear to me now.
