### ISSUE TITLE
Gluon & Sockeye

### ISSUE THREAD

**Issue by maxdel** [awslabs/sockeye#170]
Thanks for the such a neat project! 

Recently, the Gluon, MXNet's imperative interface has been released. 
What are your thoughts on it in terms of Sockeye?

**Comment by fhieber** [comment]
Gluon is definitely an interesting new API in MXNet, not only for graphs changing w.r.t to data, e.g. TreeLSTMs etc, but also for easy testing of networks! We are looking into it, but fully porting sockeye to gluon is a major rewrite.
In terms of speed, gluon seems to be still a little bit slower than the symbolic interface, but it seems to catch up (see upcoming 0.12 release of MXNet).
So the first step for us is to move from MXNet 0.10.0 to a newer MXNet version (probably 0.12), which we will do soon.

**Comment by tdomhan** [comment]
I will close the issue for now as the question was answered.
