### ISSUE TITLE
tensorboard cannot find runfiles

### ISSUE THREAD

**Issue by David-Levinthal** [awslabs/sockeye#174]
Likely trivial..but I don't 
I have sockeye up and running having followed the instructions, but tensorboard does not find the .runfiles directory
tailing the logfile that I piped stdout/stderr to
[INFO:sockeye.inference] Translator (1 model(s) beam_size=5 ensemble_mode=None buckets_source=[10, 20, 30, 40, 50, 60] buckets_target=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 118])
[INFO:root] Epoch[0] Batch [6050]	Speed: 315.80 samples/sec	perplexity=121.795174
[INFO:root] Epoch[0] Batch [6100]	Speed: 319.00 samples/sec	perplexity=118.806768
but in another shell
~/sockeye/wmt_model$ tensorboard --logdir .
Traceback (most recent call last):
  File "/home/levinth/.local/bin/tensorboard", line 152, in <module>
    Main()
  File "/home/levinth/.local/bin/tensorboard", line 102, in Main
    module_space = FindModuleSpace()
  File "/home/levinth/.local/bin/tensorboard", line 83, in FindModuleSpace
    sys.argv[0])
AssertionError: Cannot find .runfiles directory for /home/levinth/.local/bin/tensorboard

I did do the pip install tensorboard part and invoked sockeye with the invocation for the 1 layer german to english model (hidden =512, embedding = 256 etc..)
but tensorboard seems to want something else.

**Comment by tdomhan** [comment]
mhh it's not an obvious error. How did you install tensorboard? through `pip install tensorboard`?

**Comment by David-Levinthal** [comment]
actually I used pip3..as that was what the sockeye instructions "appeared"
to tell me.
"Note that for the remaining instructions to work you will need to use
python3 instead of python and pip3 instead of pip."
from: https://github.com/awslabs/sockeye
thanks for the quick response.
d

**Comment by tdomhan** [comment]
mh this seems to be a strange tensorboard issue. It seems to look for a runfiles directory which should be located where the module is installed to. For me this is `~/miniconda3/lib/python3.6/site-packages/tensorboard/tensorboard.runfiles`. For you it somehow tries to look in `~/.local`. Do you know where the tensorboard module is? Have you tried completely removing it from your system and reinstalling?

**Comment by David-Levinthal** [comment]
This is a native linux system ubuntu 16.04 (no anaconda..I have had
consistency issues with that)
it has python 2.7 and 3.5 installed.
It has tensorflow installed in my home directory..as is mxnet and sockeye.
The original tensorboard installation is likely in the tensorflow
directory(R1.3)
Where would the pip3 installation I did during sockeye install put it?
does the mxnet tensorboard monitoring invoke python and not python3?
even though I did the entire sockey/mxnet installation with pip3?
sockeye runs fine with python3, the only issue was the tensorboard
monitoring

**Comment by tdomhan** [comment]
Sockeye will important tensorboard as a python module and do the logging like this. So it will use python3.
This seems to be an issue with the standalone tensorboard fork. It might make sense to create a separate issue there
https://github.com/dmlc/tensorboard
and see if the maintainer of that package can offer any insights (he was responsive in the past when we had some python 3 issues).

**Comment by David-Levinthal** [comment]
I will try updating tensorboard with pip instead of pip3
I have python2.7 and python3 on the system..invoking python gives you
python2.7 onthis system
I will update you after I try this..(ie may be due to my installation and
nothing more..let me eliminate this possibility)
:-)
d

**Comment by tdomhan** [comment]
did you successfully install tensorboard?

**Comment by David-Levinthal** [comment]
it worked one time and then never worked again..really very odd..
but I can make the plots from the stored data and can see the current state
in stdout, so I ended up just not using it.
not sure what to say.
feel free to close this
d

**Comment by tdomhan** [comment]
ok, sorry to hear that it didn't work out. I guess it is fairly tricky to figure out what is going on from our side. I will close the ticket for now.
