### ISSUE TITLE
Line buffering / benchmark timing

### ISSUE THREAD

**Issue by mjdenkowski** [awslabs/sockeye#175]
It looks like we're currently not able to operate in "unbuffered" mode, interactively translating one line at a time with `--batch-size 1`.  We're also getting all zeros for translation time for `--output-type benchmark`.

**Comment by fhieber** [comment]
Interactive decoding is done when batch_size and chunk_size are both 1. I changed the default parameters in a new branch: translate_cli_fix.
Translation time should also now be correctly passed to the output handlers.
@artemsok will build on this branch to iron out another bug in an edge case when there a lots of empty lines. We will open a PR afterwards.

**Comment by fhieber** [comment]
see #176

**Comment by mjdenkowski** [comment]
Confirmed working, thanks!  Closing this issue.
