### ISSUE TITLE
What is the purpose of the equivalent NDArray implementation for OutputLayer?

### ISSUE THREAD

**Issue by xingniu** [awslabs/sockeye#199]
It's never been used.
https://github.com/awslabs/sockeye/blob/c0f1296607f4db3200cb6c46d6ec5e86b25c395e/sockeye/layers.py#L183-L191
I'm not sure if it's proper to ask questions like this in _Issues_.

**Comment by fhieber** [comment]
@mjdenkowski can give more details on this, but its used for decoding with a reduced vocabulary. 

The way this is implemented is as follows: if reduced vocabulary decoding is used, the inference graphs do not contain the output layer but only return the inputs to it. In beam search, we then call the output layer imperatively using a reduced smaller parameter matrix (HxW) where W << V.
The code you are referring to is called at this point.

**Comment by mjdenkowski** [comment]
As @fhieber said, this is for cases where we would like to modify the behavior of the output layer on a per-sentence basis.  This is currently only used for the `--restrict-lexicon` option.

In the code below, `decoder_outputs` from the computation graph are either the result of the output layer (default) or the inputs to the output layer (restricted vocabulary).  In the restricted version, we use the imperative API to run the output layer and final softmax with a much smaller sentence-specific vocabulary.
https://github.com/awslabs/sockeye/blob/master/sockeye/inference.py#L859-L866

**Comment by xingniu** [comment]
@fhieber @mjdenkowski Thanks a lot for your clarification. I am trying some experimental features for decoder/output_layer and I think I can just focus on the Symbol version for now if `--restrict-lexicon` is not used.
