### ISSUE TITLE
raw_corpus_bleu doesn't work for tokenized sentences

### ISSUE THREAD

**Issue by xingniu** [awslabs/sockeye#204]
https://github.com/awslabs/sockeye/blob/ccf74a928c83345a773f8293d22b9ce658354e9c/contrib/sacrebleu/sacrebleu.py#L800-L807
raw_corpus_bleu sets force=True and tokenize='none', while the condition in L800 above is still satisfied. Should it be
`if (tokenize != 'none' or not force) and lines[0].rstrip().endswith(' .'):`
or even
`if not force and lines[0].rstrip().endswith(' .'):` ?

**Comment by xingniu** [comment]
And I would suggest to log this as a warning instead of an error (and exit).

**Comment by mjpost** [comment]
Yes, you're right, this shouldn't exit. And the logic is wrong; it should be:

    if (not force or tokenize != 'none') and ...

I'll push up a fix.
