### ISSUE TITLE
Potential error of "permission denied" when trying to open lock files

### ISSUE THREAD

**Issue by xingniu** [awslabs/sockeye#209]
A "permission denied" error would be raised if the lock file was owned by another user.
Is moving L552 into try-except a possible solution?
https://github.com/awslabs/sockeye/blob/d436ae8319e9cd531a562434f5022029ff933d6c/sockeye/utils.py#L549-L575

**Comment by tdomhan** [comment]
oh ok good point, we should fix this. In your scenario does `open` through an IOError with errno.EAGAIN?

**Comment by xingniu** [comment]
I got "permission denied", so I think it's errno.EACCES. In this scenario, it's better that Sockeye tries to find another GPU.

**Comment by bricksdont** [comment]
Yes, but in case a specific device was requested by the user with `--device` I don't think sockeye should try to aquire a GPU that was not listed in this option, right?

**Comment by xingniu** [comment]
Right, "find another GPU" if `--device` got an negative value.

**Comment by tdomhan** [comment]
So this PR https://github.com/awslabs/sockeye/pull/268 should fix the issue and retry when we get a permission denied for the lock. Does this work for you?

What was the other point regarding `--device`? Is there some other issue with the way locking works right now?

**Comment by xingniu** [comment]
Thanks! It's ok for me if Sockeye behaves the same when the lock is owned by self and others.

**Comment by bricksdont** [comment]
@tdomhan Sorry I actually meant `--device-ids`, and in the context of xingniu's comment:

>In this scenario, it's better that Sockeye tries to find another GPU.

this should only happen if `--device-ids` has a negative value. But, as far as I can see, that's not an issue in your PR.

**Comment by tdomhan** [comment]
ah ok. Yes, if you specify non-negative device ids with the recent change sockeye will wait for these specific devices to become available.

I guess one potential issue with lock files owned by other people is that in case sockeye gets shut down non-gracefully and the lock files don't get deleted, then someone will need to manually delete the files. This is not the case when there are no permission errors, as there we don't rely on the existence of the file, but rather on the file system lock provided by the operating system, which ceases to exist as soon as a process dies. However, I don't see a better way of handling it, than we do now.

**Comment by tdomhan** [comment]
The code has been merged. Let us know if there are issues.
