### ISSUE TITLE
Best Parameters For Transformer Model on WMT 2014?

### ISSUE THREAD

**Issue by andrewoftoronto** [awslabs/sockeye#210]
Hello,
I am a research assistant who is part of a team that is profiling machine learning frameworks across different applications. Among other applications, I am studying the transformer model applied to translation tasks. I would like to know if there is a listing of the best settings to use with this framework to reproduce the results in the "Attention Is All You Need" paper.

Thank you

**Comment by fhieber** [comment]
Hi, 
sorry for taking a little bit to respond to this. 
Exactly reproducing the results of the "Attention Is all You Need" paper may be tricky, as there are some small differences in the toolkits you may not be able to remove completely (batching & bucketing and how data is organized in general).
However, you should be able to train a transformer model that is parameterized almost exactly like the Attention Is All You Need paper by using the existing commandline flags that start with ``--transformer`` (model size, number of attention heads, feed-forward-size etc.)
Training-specific flags like ``--batch-type word --batch-size 4096``, or transformer-specific dropout settings and methods like label smoothing are also available.

**Comment by fhieber** [comment]
Closing this for now, feel free to reopen if you have further questions.
