### ISSUE TITLE
Issues with GPUs

### ISSUE THREAD

**Issue by duyvuleo** [awslabs/sockeye#22]
Hi,

I got some issues when running sockeye on GPUs. 

**Issue 1**: leaked semaphores
>> sockeye-train --source ../data/multi30k/train.en.atok \
                       --target ../data/multi30k/train.de.atok \
                       --validation-source ../data/multi30k/val.en.atok \
                       --validation-target ../data/multi30k/val.de.atok \
                       --word-min-count 2 \
                       --rnn-num-layers 1 \
                       --rnn-cell-type gru \
		       --rnn-num-hidden 128 \
		       --num-embed-source 128 \
		       --num-embed-target 128 \
		       --attention-type mlp \
		       --attention-num-hidden 128 \
		       --batch-size 64 \
		       --normalize-loss \
		       --dropout 0.1 \
		       --initial-learning-rate 0.001 \
		       --device-ids 0 \
		       --output ../models/multi30k 
>> 
... (truncated)
[INFO:sockeye.training] Training started.
[INFO:sockeye.callback] Early stopping by optimizing 'perplexity' (minimize=True)
script-multi30k.sh: line 49: 19451 Segmentation fault      sockeye-train --source ../data/multi30k/train.en.atok --target ../data/multi30k/train.de.atok --validation-source ../data/multi30k/val.en.atok --validation-target ../data/multi30k/val.de.atok --word-min-count 2 --rnn-num-layers 1 --rnn-cell-type gru --rnn-num-hidden 128 --num-embed-source 128 --num-embed-target 128 --attention-type mlp --attention-num-hidden 128 --batch-size 64 --normalize-loss --dropout 0.1 --initial-learning-rate 0.001 --device-ids 0 --output ../models/multi30k
[vhoang@gpu047 scripts]$ /pylon2/ci560op/fosterg/tools/anaconda3/lib/python3.6/multiprocessing/semaphore_tracker.py:129: UserWarning: semaphore_tracker: There appear to be 3 leaked semaphores to clean up at shutdown
  len(cache))

**Issue 2**: Permission denied
>> sockeye-train --source ../data/multi30k/train.en.atok \
                       --target ../data/multi30k/train.de.atok \
                       --validation-source ../data/multi30k/val.en.atok \
                       --validation-target ../data/multi30k/val.de.atok \
                       --word-min-count 2 \
                       --rnn-num-layers 1 \
                       --rnn-cell-type gru \
		       --rnn-num-hidden 128 \
		       --num-embed-source 128 \
		       --num-embed-target 128 \
		       --attention-type mlp \
		       --attention-num-hidden 128 \
		       --batch-size 64 \
		       --normalize-loss \
		       --dropout 0.1 \
		       --initial-learning-rate 0.001 \
		       --device-ids -1 \
		       --output ../models/multi30k 
>> 
... (truncated)
[INFO:sockeye.train] Attempting to acquire 1 GPUs.
[INFO:sockeye.utils] Trying to acquire one of 2 available GPUs.
Traceback (most recent call last):
  File "/pylon2/ci560op/fosterg/tools/anaconda3/bin/sockeye-train", line 11, in <module>
    load_entry_point('sockeye==1.0.3', 'console_scripts', 'sockeye-train')()
  File "/pylon2/ci560op/fosterg/tools/anaconda3/lib/python3.6/site-packages/sockeye-1.0.3-py3.6.egg/sockeye/train.py", line 147, in main
  File "/pylon2/ci560op/fosterg/tools/anaconda3/lib/python3.6/site-packages/sockeye-1.0.3-py3.6.egg/sockeye/train.py", line 147, in <listcomp>
  File "/pylon2/ci560op/fosterg/tools/anaconda3/lib/python3.6/contextlib.py", line 330, in enter_context
    result = _cm_type.__enter__(cm)
  File "/pylon2/ci560op/fosterg/tools/anaconda3/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/pylon2/ci560op/fosterg/tools/anaconda3/lib/python3.6/site-packages/sockeye-1.0.3-py3.6.egg/sockeye/utils.py", line 291, in acquire_gpu
PermissionError: [Errno 13] Permission denied: '/var/lock/sockeye.gpu0.lock'

Do you have any idea to resolve them? 

Thanks!

--
Cheers,
Vu

**Comment by tdomhan** [comment]
Hi!
**Issue 1:**
How did you install MXNet? Did you compile it yourself or install the version from pip. I've seen this issue before when getting a seg fault from MXNet due to mixing GPU and CPU operations that weren't properly checked for. Did you try running on the CPU (--use-cpu), just to see if that makes a difference?

**Issue 2:**
Sockeye uses simple file locking in order to only have one training process per GPU. The directory ("/var/lock") needs to be writeable by the user. Currently you can't configure the locking directory, but maybe it would make sense to add this as a parameter to the CLI.

**Comment by duyvuleo** [comment]
Hi,

I installed sockeye from source by the following command:
>> python setup.py install -r requirements.gpu-cu80.txt

It works fine with CPU. 

Do you have any suggestions to resolve the issue on GPU?

**Comment by tdomhan** [comment]
could you generate a backtrace with **_gdb_**?
```
# gdb python
> run -m sockeye.train --source ../data/multi30k/train.en.atok 
--target ../data/multi30k/train.de.atok 
--validation-source ../data/multi30k/val.en.atok 
--validation-target ../data/multi30k/val.de.atok 
--word-min-count 2 
--rnn-num-layers 1 
--rnn-cell-type gru 
--rnn-num-hidden 128 
--num-embed-source 128 
--num-embed-target 128 
--attention-type mlp 
--attention-num-hidden 128 
--batch-size 64 
--normalize-loss 
--dropout 0.1 
--initial-learning-rate 0.001 
--device-ids 0 
--output ../models/multi30k
 .... segmentation fault
> bt
```

1. So basicallty you start **python** with ```gdb```.
1. type ```run``` followed by the normal training parameters
1. The program probably runs into a segmentation fault, after this happens type ```bt``` to get a backtrace and paste the result here.

One thing you could try independent of that is try the version of MXNet without MKL:
```
# pip uninstall mxnet-cu80mkl
# pip install mxnet-cu80
```

**Comment by cherryc** [comment]
Thanks Tobias. It turns out that we do not have access to pdb on our cluster, but I'll move it over to a machine I have more control over to replicate the error there and provide a full backtrace when I have some free cycles (not until after Wednesday). Here's a little more information, in case it helps:

Trying the version of MXNet without MKL did resolve the issue (thanks!)

This issue seemed to only occur when working with very small corpora (30k  sentence pairs).

**Comment by duyvuleo** [comment]
We resolved the issue now. Thanks for your suggestion. It was a great help!

**Comment by tdomhan** [comment]
great! I'm glad it's working now.

**Comment by tdomhan** [comment]
FYI: we added a couple of options regarding file locking:
https://github.com/awslabs/sockeye/pull/17
1. The default is now /tmp.
1. You can disable it

**Comment by duyvuleo** [comment]
Great!

Thanks Tobias.

--
Cheers,
Vu
