### ISSUE TITLE
Validation with process-exclusive devices

### ISSUE THREAD

**Issue by bricksdont** [awslabs/sockeye#221]
Most GPUs on our servers are process-exclusive. If I specify a process-exclusive GPU as a sockeye `--device` for training, the validation step throws an error:

    cudaMalloc failed: all CUDA-capable devices are busy or unavailable

Presumably because I have specified a single device to be aquired and it's in Exclusive Mode.

With Nematus, I usually use a different device for the validation process. With sockeye, as far as I can see, I cannot specify a device that would only be used for the purpose of validation, is that correct?

Do you have a recommendation to deal with this? Thanks!

**Comment by fhieber** [comment]
that is a good point, we should add arguments for this (or even allow CPU validation decoding if necessary). Probably named similar to `--monitor-bleu` to make clear that they are related.

**Comment by bricksdont** [comment]
A separate option for this would make sense yes. In the meantime, I have a related question:

If I specify several devices, which of them will be used for the validation process? The first one? Arbitrary choice?

**Comment by fhieber** [comment]
It will use the last device in the context list (see here: https://github.com/awslabs/sockeye/blob/master/sockeye/training.py#L254). Which device is the last may depend on the order in which GPUs were acquired, so this is effectively arbitrary; we should have more control over this.

**Comment by tdomhan** [comment]
huh, I didn't know a CUDA device could be restricted to a single process. The validation runs in a separate background process. I guess it would make sense to give the option to specify a separate GPU (or run validation on the GPU). In the mean time you could turn off `--monitor-bleu`, as without that option there are no background processes.

**Comment by fhieber** [comment]
I created a PR that would allow you to use the CPU for decoding or any other (separate) GPU device (which might also be useful in cases where memory is sparse on the GPU).

**Comment by fhieber** [comment]
#228 was merged, closing this issue. Feel free to reopen if your issue persists.
