### ISSUE TITLE
monitor-bleu option does not exist anymore

### ISSUE THREAD

**Issue by mkolod** [awslabs/sockeye#256]
The WMT15 English-German translation [example](https://github.com/awslabs/sockeye/blob/master/tutorials/wmt/README.md) seems to be having issues. I can't run it exactly as described in the README and successfully run training. 

For instance, that example uses --monitor-bleu arg, which no longer exists in top-of-tree Sockeye.

I'm not sure if the solution is to change the metric from perplexity to BLEU for monitoring (that would be very slow), or keep monitoring perplexity, and report BLEU after training,  by post-processing the inference output (fast but doesn't give useful feedback during training, since perplexity and BLEU are very loosely correlated). However, the example won't work in its current state.

Also, running the example as-is, by just removing --monitor-bleu from the command line args, fails due to a diagreement in the number of source and target text lines (see below). It seems to me that the data preprocessing does not clean up empty lines. That's at least how Sockeye used to fail for me before removing empty lines from the parallel corpora. See the example of [my solution](https://github.com/mkolod/sockeye/blob/wmt15_master/preprocess_raw_data.py). It's kind of simplistic compared to the byte-pair encoding and other preprocessing steps used in the official Sockeye example, but it runs at least.

```
[INFO:sockeye.vocab] Building vocabulary from dataset(s): ['corpus.tc.BPE.de']
[INFO:sockeye.vocab] Vocabulary: types: 22305/22305/22305/22309 (initial/min_pruned/max_pruned/+special) [min_frequency=1, max_num_types=50000]
[INFO:sockeye.vocab] Building vocabulary from dataset(s): ['corpus.tc.BPE.en']
[INFO:sockeye.vocab] Vocabulary: types: 22662/22662/22662/22666 (initial/min_pruned/max_pruned/+special) [min_frequency=1, max_num_types=50000]
[INFO:sockeye.data_io] ===============================
[INFO:sockeye.data_io] Creating training data iterator
[INFO:sockeye.data_io] ===============================
[INFO:sockeye.utils] Releasing GPU 0.
[ERROR:__main__] Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/sockeye-1.16.0-py3.5.egg/sockeye/train.py", line 822, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/sockeye-1.16.0-py3.5.egg/sockeye/train.py", line 746, in main
    output_folder=output_folder)
  File "/usr/local/lib/python3.5/dist-packages/sockeye-1.16.0-py3.5.egg/sockeye/train.py", line 362, in create_data_iters_and_vocab
    bucket_width=args.bucket_width)
  File "/usr/local/lib/python3.5/dist-packages/sockeye-1.16.0-py3.5.egg/sockeye/data_io.py", line 736, in get_training_data_iters
    max_seq_len_source, max_seq_len_target)
  File "/usr/local/lib/python3.5/dist-packages/sockeye-1.16.0-py3.5.egg/sockeye/data_io.py", line 230, in analyze_sequence_lengths
    "Different number of lines in source and target data.")
  File "/usr/local/lib/python3.5/dist-packages/sockeye-1.16.0-py3.5.egg/sockeye/utils.py", line 117, in check_condition
    raise SockeyeError(error_message)
sockeye.utils.SockeyeError: Different number of lines in source and target data.

```

**Comment by fhieber** [comment]
We will take a look at the preprocessing in the WMT example. Meanwhile I fixed the tutorial to use `--decode-and-evaluate` instead of `--monitor-bleu`: #257

**Comment by tdomhan** [comment]
Just to clarify `--monitor-bleu` was just renamed to `--decode-and-evaluate` to make the parameter clearer, see: https://github.com/awslabs/sockeye/blob/master/CHANGELOG.md#changed-6. The behavior of the CLI parameter did not change. Namely, when you specify the parameter sockeye will decode the given number of sentences in a separate decoder process. If `--optimized-metric` is set to bleu as well that bleu will be used for early stopping. Otherwise the BLEU scores are just reported but early stopping is done based on the perplexity values.

**Comment by tdomhan** [comment]
I just reran the WMT example and I do not observe any error. Could you double check that the source and target data have the same number of lines?

**Comment by mkolod** [comment]
@tdomhan It seems like it's working OK now. I'm not sure why I was able to find that issue before, and now I can't repro it.

**Comment by tdomhan** [comment]
glad it's working now.  :)
