### ISSUE TITLE
examples for s2s distributed training with --kvstore=dist_async/dist_sync

### ISSUE THREAD

**Issue by chenzhehuai** [awslabs/sockeye#259]
hi all,

can u provide some examples about distributed training especially with --kvstore=dist_async/dist_sync ?

I succeed in using: --kvstore=device  --device-ids -4 --batch-size 486, and the speed is fine.
but failed in: --kvstore=dist_sync--device-ids -4 --batch-size 162, complaining: "can't find DMLC_WORKER .. " (while i have compiled with USE_DIST_KVSTORE=1, mxnet_cu80-1.0.0, sockeye-1.15.8)

then i try several methods as below, it can run but the speed is slow: 
 python3 ../incubator-mxnet/tools/launch.py --cluster=local -n 1 ' python3 -m sockeye.train --device-ids -3 --kvstore dist_sync  --batch-size 162... '
 python3 ../incubator-mxnet/tools/launch.py --cluster=local -n 3 ' python3 -m sockeye.train --device-ids -1 --kvstore dist_sync  --batch-size 162... '
 python3 ../incubator-mxnet/tools/launch.py --cluster=local -n 3 -s 1 ' python3 -m sockeye.train --device-ids -1 --kvstore dist_sync  --batch-size 162 ... '

Thus I think I might not use it properly. 
Thanks.

**Comment by tdomhan** [comment]
Hi!
as you discovered you will either need to use the launch script provided by MXnet or write a custom script that launches the schedulers and servers as described here: https://blog.kovalevskyi.com/mxnet-distributed-training-explained-in-depth-part-1-b90c84bda725 

Are you running on a single machine? If so the overhead of running multiple training processes will most likely slow training down in comparison to just using multiple GPUs in a single Sockeye process with `--decide-ids`.

**Comment by chenzhehuai** [comment]
Thanks. I run in a single machine. 

Then my question is: how can i run async parallel training efficiently in a single machine with multiple gpus?

**Comment by tdomhan** [comment]
I mean you can run async parallel training the way you did with the launch script. Whether or not that is efficient is very model dependent. There are parameters such as gradient compression which were recently added to Sockeye that might help. If you do not see any performance gains, than the best use of multiple GPUs is training with synchronous SGD with multiple devices with a large enough batch size to fully utilize the GPUs. I hope that helps.
