### ISSUE TITLE
Sockeye's translation of the text of the command

### ISSUE THREAD

**Issue by yapingzhao** [awslabs/sockeye#261]
Hello, I would like to ask what is the command to translate a text using the Sockeye model.
Not echo "er ist so ein toller Kerl und ein Familienvater." | \
   python -m apply_bpe -c bpe.codes --vocabulary bpe.vocab.en \
                                    --vocabulary-threshold 50 | \
   python -m sockeye.translate -m wmt_model 2> / dev / null | \
   sed -r 's / @@ (| $) // g'
Hope to give the answer, thank you

**Comment by bricksdont** [comment]
Hi, Your question is a bit unclear. Do you mean how you would translate a _file_?

You can simply `cat` the file instead of echo:

    cat translate_this.txt | python -m sockeye.translate -m model

**Comment by yapingzhao** [comment]
This is the answer I want, thank you very much. I would like to ask two more questions:
1, the translation of the results of the document where the path
2, how to get translation of the BLEU value, the command format
Hope to give answers, thank you!

**Comment by bricksdont** [comment]
`--output` lets you specifiy an output file. Type

    python3 -m sockeye.translate --help

to find out about all other options and read https://github.com/awslabs/sockeye/blob/master/docs/user_documentation.md.

For BLEU scores, the repository contains `sacrebleu`, read the docs here:

https://github.com/awslabs/sockeye/tree/master/contrib/sacrebleu

**Comment by yapingzhao** [comment]
Hi,Excuse me, I still have a question,the last question about subword-nmt.
python -m learn_joint_bpe_and_vocab --input corpus.en corpus.ch -s 30000 -o bpe.codes --write-vocabulary bpe.vocab.en bpe.vocab.ch
After running the above command, the following hints appear: 
no pair has frequency> = 2. Stopping.
I do not understand what this message means. Hope to give answer, thank you very much.
