### ISSUE TITLE
CNN Decoder only supports a maximum length of 128, but 130 was requested....

### ISSUE THREAD

**Issue by M4t1ss** [awslabs/sockeye#265]
Hi! When I try to train (and translate with) a CNN encoder & decoder, I constantly get a maximum length error like

> sockeye.utils.SockeyeError: Decoder only supports a maximum length of 128, but 130 was requested. Note that the maximum output length depends on the input length and the source/target length ratio observed during training.

I did get it to work when specifying a small enough length
```
python -m sockeye.translate --models . \
                            --use-cpu \
                            --max-input-len 97 \
                            < decode.source \
                            > decode.output
```

Training parameters I used:
```
python -m sockeye.train --prepared-data data-prepared \
                        -vs newsdev2017.bpe.en \
                        -vt newsdev2017.bpe.lv \
                        --batch-size 128 \
                        --num-embed 512 \
                        --decode-and-evaluate -1 \
                        --checkpoint-frequency 3000 \
                        --use-tensorboard \
                        -o wmt_conv_model \
                        --encoder cnn \
                        --decoder cnn \
                        --num-layers 6:6 \
                        --max-seq-len 128
```

**Comment by tdomhan** [comment]
any specific reason you are specifying the maximum input length at decoding time? It's usually best to leave this parameter out and let the model pick a maximum input length automatically based on the constraints (due to the learned positional embeddings) and the length ratio statistics observed during training.

**Comment by tdomhan** [comment]
Also this mainly comes from using learned positional embeddings (the default), which limits both the source and target maximum length at inference time. If you used fixed positional embeddings this would not be the case.

**Comment by M4t1ss** [comment]
This error first came up during training after saving the first checkpoint when it wanted to translate the dev set to get a BLEU score for the checkpoint. And then again after each following checkpoint 😀 
Nothing got translated, so I ran `sockeye.translate` myself, without specifying `--max-input-len` at first - got the same error. Tried to set `--max-input-len 128` and got 
>supports a maximum length of 128, but 167 was requested 

🤔 after trying other lower values, I found the 97 which worked to get a translation with the trained model, but it still keeps complaining during training...
Before this I trained a few transformer models with the same data and similar parameters and they all worked fine.

**Comment by tdomhan** [comment]
sockeye.translate without `--max-input-len` should always works, so this is definitely not the intended behavior. In order to get to the bottom of this could you share:

- Sockeye version.
- The model config file (in the config folder)
- The training and translation logs.

**Comment by M4t1ss** [comment]
Just noticed that my version is a few weeks old 1.15.7
I think that the next version fixed this
```
## [1.15.8]
### Fixed
 - Taking the BOS and EOS tag into account when calculating the maximum input length at inference.
```
I'll try to update and check if it helps...

[log.txt](https://github.com/awslabs/sockeye/files/1618223/log.txt)
[config.txt](https://github.com/awslabs/sockeye/files/1618224/config.txt)

**Comment by M4t1ss** [comment]
Works with Sockeye version 1.16.2 commit 762ce78e4e49b9ba5d14eb0a48d97f19c8807707 and MXNet version 1.0.0
Thanks! 👍
