### ISSUE TITLE
python versioning

### ISSUE THREAD

**Issue by pensalea** [awslabs/sockeye#267]
I was wondering if anyone is working on a Python 2.7 version of the sacrebleu library? If not, are there any particular roadblocks I should be aware of if I try to convert it myself?

**Comment by tdomhan** [comment]
I'm not aware of particular blockers, but I also don't think anyone is working on this at the moment. Asking the other way around: What are the blockers for using Python 3?

**Comment by pensalea** [comment]
I'm working on a project that relies on 2.7. It'd be cool to support both, but am a little wary of converting sacrebleu in case that approach might result in bugs or other issues.

**Comment by tdomhan** [comment]
I was just wondering whether independent of the project code you could run python 3 just for running scarebleu. Having both python 2.7 and python 3 installed along each other shouldn't be a problem.

**Comment by mjpost** [comment]
I'm happy to take a PR for 2.7 support (with test cases), but am not planning to do it myself. Please feel free to re-open this and reference it should you decide to.
