### ISSUE TITLE
Unsolicited acquisition of GPU device

### ISSUE THREAD

**Issue by bricksdont** [awslabs/sockeye#273]
For some reason, sockeye acquires a device I did not ask for. For the following training command:

```sh
python3 -m sockeye.train \
--decode-and-evaluate-device-id 1 \
--device-ids 5 6 7 \
--lock-dir /var/tmp \
[...]
```
(Includes all relevant options, I just omitted them because I suspect they do not matter.) After the devices are acquired, the output of gpustat is:

```
[0] GeForce GTX TITAN X | 40'C, 0 % | 217 / 12207 MB | mmueller(213M)
[1] GeForce GTX TITAN X | 42'C, 0 % | 2 / 12207 MB |
[2] GeForce GTX TITAN X | 66'C, 85 % | 11146 / 12207 MB | [not me]
[3] GeForce GTX TITAN X | 62'C, 87 % | 9995 / 12207 MB | [not me]
[4] GeForce GTX TITAN X | 68'C, 81 % | 11231 / 12207 MB | [not me]
[5] GeForce GTX TITAN X | 77'C, 60 % | 6631 / 12207 MB | mmueller(6627M)
[6] GeForce GTX TITAN X | 70'C, 95 % | 6095 / 12207 MB | mmueller(6091M)
[7] GeForce GTX TITAN X | 67'C, 92 % | 6094 / 12207 MB | mmueller(6090M)
```

Everything as expected, GPU 1 is not showing up yet because it is the validation device, but on device 0, 213 MB are occupied. And nvidia-smi shows that the same Python 3 process has taken those 213 MB on device 0:

```
+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|
| 0 14929 C python3 213MiB |
| 2 8981 C python 11144MiB |
| 3 18504 C python 9993MiB |
| 4 5915 C python 11229MiB |
| 5 14929 C python3 6627MiB |
| 6 14929 C python3 6091MiB |
| 7 14929 C python3 6090MiB |
+-----------------------------------------------------------------------------+
```

In my lock directory, gpu0 does not even have a lock:

```
$ ll /var/tmp/sockeye.*.lock
-rw-r--r-- 1 mmueller users 6 Jan 17 17:37 /var/tmp/sockeye.gpu5.lock
-rw-r--r-- 1 mmueller users 6 Jan 17 17:37 /var/tmp/sockeye.gpu6.lock
-rw-r--r-- 1 mmueller users 6 Jan 17 17:37 /var/tmp/sockeye.gpu7.lock
```

Any idea why this is happening? Thanks!

**Comment by fhieber** [comment]
Hi @bricksdont 
I think I have seen this before too and I suspect this is an MXNet issue. I haven't looked into this further yet but maybe we should investigate it a bit more.

**Comment by tdomhan** [comment]
yeah, I think this is an issue with certain versions of MXNet and we should file an issue with MXNet in order to fix it there :/

**Comment by tdomhan** [comment]
If you need a workaround in the meantime you can use the environment variable `CUDA_VISIBLE_DEVICES`. Before posting this issue as an MXNet issue I would like to confirm this is an issue with some other than an MT.

**Comment by tdomhan** [comment]
this seems to have been fixed in MXNet: https://github.com/apache/incubator-mxnet/pull/11146

**Comment by fhieber** [comment]
closing for now. Feel free to reopen if the issue persists with the next MXNet version that includes the referenced commit.
