### ISSUE TITLE
About pretrained models

### ISSUE THREAD

**Issue by sxjscience** [awslabs/sockeye#298]
Thanks for this amazing package! I'd like to ask if there is any pretrained models available to replicate the results described in the Sockeye paper?

**Comment by fhieber** [comment]
Hi @sxjscience,
we have not released any pre-trained models, but you should be able to re-create them using the scripts provided in the [arxiv_1217 branch](https://github.com/awslabs/sockeye/tree/arxiv_1217/arxiv/code).
Note that the paper is using an older version of Sockeye (1.12).

**Comment by sxjscience** [comment]
Thanks a lot! I will then try to train the models myself first.
