### ISSUE TITLE
Can't resume training

### ISSUE THREAD

**Issue by franckbrl** [awslabs/sockeye#301]
Hello,

I have killed the training of a model and I can't resume it in the way described here : http://sockeye.readthedocs.io/en/latest/user_documentation.html#training (not using --params argument).

The first lines from the log file let me think that everything is OK :

`Found partial training in directory /home/franck/sockeye/en2fr/model.s-transfo.en2fr/training_state. Resuming from saved state.`

`Loaded params from "/home/franck/sockeye/en2fr/model.s-transfo.en2fr/training_state/params"`

Next, this raises suspicions:

`Saved params to "/home/franck/sockeye/en2fr/model.s-transfo.en2fr/params.00000"`

since I've already have `params.00013` and `params.best` is linked to checkpoint #12.

Finally, I get a FileExistsError:

```
os.symlink(initial_params_fname, os.path.join(output_folder, C.PARAMS_BEST_NAME))
FileExistsError: [Errno 17] File exists: 'params.00000' -> '/home/franck/sockeye/en2fr/model.s-transfo.en2fr/params.best'
```

Here is my args.json file: [args.txt](https://github.com/awslabs/sockeye/files/1751360/args.txt)

I wish I did not have to use the `--params` argument. Any idea what's wrong here?

Best,
Franck

**Comment by davvil** [comment]
This is indeed a bug. Can you try #302?

You do not need to specify `--params` on the command line, it will find the last training state automatically.

**Comment by franckbrl** [comment]
#302 solved the problem, thank you!
