### ISSUE TITLE
Transformer configuration example

### ISSUE THREAD

**Issue by SamuelLarkin** [awslabs/sockeye#308]
First of all, nice work!
I'm currently playing with sockeye and I successfully trained a simple RNN with 3 layers and got really nice perplexities out of it.  I'm now trying to train a transformer (encoder & decoder) on the same data but I can't get nearly the same perplexity.  RNN's perplexity started a ~400 and quickly dropped to ~4 within a couple of updates and eventually ended ~1.3.  My Transformer run started at ~700 and is now stuck at ~270 which is far from ~1.3.  I'm not expecting both models to get to the same perplexity but at least in the same range.

I searched the net to find an example of a transformer configuration for sockeye and couldn't find any.  Would it be possible to have an example of minimum/good enough configuration of transformer in sockeye?

Here's my current sockeye command line:
```
python \
   -m sockeye.train \
      --source $corpora/train_en.bpe \
      --target $corpora/train_fr.bpe \
      --validation-source $corpora/dev1_en.bpe \
      --validation-target $corpora/dev1_fr.bpe \
      --encoder transformer \
      --decoder transformer \
      --num-layers 6:6 \
      --max-seq-len 60 \
      --decode-and-evaluate 500 \
      --decode-and-evaluate-use-cpu \
      --metrics perplexity \
      --optimizer adam \
      --use-tensorboard \
      -o model \
   2> log.train
```
Should I had residual connection ?

Thanks for your help.

Suggestion: I think it would be quite useful to have an option that take a yaml file as a configuration.  Having a way to pass a full configuration of sockeye via a yaml file would make experimentation easier and would also make sharing sockeye configuration easier.

**Comment by fhieber** [comment]
Hi @SamuelLarkin , thanks for trying out Sockeye!

Residual connections are always added to the transformer model, but there are some other options that can be relevant for successfully training transformers. You can take a look at the training script we published for the arxiv paper in the arxiv branch: https://github.com/awslabs/sockeye/blob/arxiv_1217/arxiv/code/transformer/sockeye/train-transformer.sh

These are some parameters that worked well on the WMT17 dataset in the paper:
```
--batch-type=word \
--batch-size=4096 \
--embed-dropout=0:0 \
--encoder=transformer \
--decoder=transformer \
--num-layers=6:6 \
--transformer-model-size=512 \
--transformer-attention-heads=8 \
--transformer-feed-forward-num-hidden=2048 \
--transformer-preprocess=n \
--transformer-postprocess=dr \
--transformer-dropout-attention=0.1 \
--transformer-dropout-relu=0.1 \
--transformer-dropout-prepost=0.1 \
--transformer-positional-embedding-type fixed \
--label-smoothing 0.1 \
--weight-tying \
--weight-tying-type=src_trg_softmax \
--num-embed 512:512 \
--clip-gradient=-1 \
--initial-learning-rate=0.0001 \
--learning-rate-reduce-num-not-improved=8 \
--learning-rate-reduce-factor=0.7 \
--weight-init xavier --weight-init-scale 3.0 \
--weight-init-xavier-factor-type avg
```

**Comment by SamuelLarkin** [comment]
Thanks for the super quick response.
I'll look at your script and I'll also give it a try with your suggested configuration.

**Comment by SamuelLarkin** [comment]
I've trained using @fhieber 's configuration and indeed, I've got much better perplexity.  Once you have the magical incantation, you can get transformer to work.  Training is not yet done but perplexity hovers around ~1.3, just like my RNN run.

Thanks for your help!

**Comment by fhieber** [comment]
Glad to hear that this works.
I will close this for now, but feel free to reopen if needed.
