### ISSUE TITLE
How is BLEU score defined in Sockeye?

### ISSUE THREAD

**Issue by ArmageddonKnight** [awslabs/sockeye#309]
Hi there,

I have a question on how BLEU score is defined in Sockeye. When I ran the application, I noticed that although the perplexity is really low, the BLEU score remains low as well (around `0.22`). Does this mean that there is something wrong with my model or should I multiply this result by `100`?

Also, I am just wondering whether there is any time estimate on how much the model is going to run on the full training of WMT 17 English-German dataset using a 2-layer RNN encoder-decoder architecture.

Thanks you so much for your precious time.

**Comment by fhieber** [comment]
Hi,

What the BLEU score means depends what you are computing it on. If you are referring to the BLEU scores logged during training, these are BLEU values computed on the preprocessed representation of your data (possibly byte-pair encoded), so they should not be compared to 'official scores' such as generated by sacrebleu on detokenized (and then internally tokenized) data.

Orthogonally to this, BLEU scores reported by Sockeye during training are in `[0,1]`, so `0.22` doesn't sound too bad (i.e. 22 BLEU).

Training time depends on a variety of factors, such as the number and type of GPUs, stopping criteria, and validation data. If you train on a single K80 for example, you should probably expect at least 3-4 days I would say.

**Comment by ArmageddonKnight** [comment]
Hi @fhieber ,

Thank you for your response. But if I do not do any preprocessing on the dataset (i.e. no BPE, I know this will have an impact on the final training results), does this mean that the BLEU score will represent my training quality?

**Comment by fhieber** [comment]
Yes, regardless of your preprocessing, the BLEU score represents your training progress, as you can compare the scores over multiple checkpoints.

My point was about comparing these BLEU values with scores from other people/publications:
you are probably at least tokenizing your data which might differ from 'official BLEU score tokenization', so you should not use the scores reported during training in a paper, for example.

**Comment by ArmageddonKnight** [comment]
Thank you so much. This is really helpful.

**Comment by ArmageddonKnight** [comment]
Sorry for bothering again, but I noticed you reported several results on the training English-German dataset in the published Arxiv paper. Could you please explain how to reproduce the results?

This is the command line I am using for now:

```
python3 -m sockeye.train --source $SOCKEYE_ROOT/dataset/corpus.tc.BPE.en \
                         --target $SOCKEYE_ROOT/dataset/corpus.tc.BPE.de \
                         --validation-source $SOCKEYE_ROOT/dataset/newstest2016.tc.BPE.en \
                         --validation-target $SOCKEYE_ROOT/dataset/newstest2016.tc.BPE.de \
                         --output $SOCKEYE_ROOT/models --overwrite-output \
                         --max-seq-len 100:100 \
                         --num-embed 512:512 \
                         --encoder rnn --decoder rnn --num-layers 2:2 --rnn-cell-type lstm --rnn-num-hidden 512 \
                         --rnn-attention-type mlp --rnn-attention-num-hidden 512 \
                         --batch-size 128 --bucket-width 10 \
                         --metrics perplexity \
                         --weight-init uniform --weight-init-scale 0.1 \
                         --max-num-epochs 10
```

**Comment by ArmageddonKnight** [comment]
I am hoping to train on the English-German dataset and achieve a BLEU score at around `0.20`, yet with the hyperparameters above, I never get above `0.10`. Is this caused by the dataset? Could you please provide the command line options you used to report the BLEU score in your paper.

Thank you so much for your precious time.

**Comment by fhieber** [comment]
Hi,

the parameters of the models for the results in the arXiv paper can be found in the `arxiv_1217` [branch](https://github.com/awslabs/sockeye/tree/arxiv_1217). The parameters for the RNN model for example are here: https://github.com/awslabs/sockeye/tree/arxiv_1217/arxiv/code/rnn/sockeye.

Note that the paper used the 1.12 version of Sockeye (where the `arxiv_1217` branch is at), so you might not get the exact same results if you use latest master (including the latest version of MXNet). But the differences should be negligible.

**Comment by tdomhan** [comment]
Note also that you should preprocess your data in the same way (tokenization + BPE), see https://github.com/awslabs/sockeye/blob/arxiv_1217/arxiv/code/prepare_train.sh

**Comment by xinyu-intel** [comment]
Hi, I have trained GNMT model with the following command:

```
python -m sockeye.train -s corpus.tc.BPE.de \
                        -t corpus.tc.BPE.en \
                        -vs newstest2016.tc.BPE.de \
                        -vt newstest2016.tc.BPE.en \
                        --num-embed 256 \
                        --rnn-num-hidden 512 \
                        --rnn-attention-type dot \
                        --max-seq-len 60 \
                        --decode-and-evaluate 500 \
                        --batch-size 512 \
                        --use-tensorboard \
                        -o wmt_model_beam_3 \
                        --num-layers 8 \
                        --device-ids 0 1 2 3
```

I've tried different beam size and finally got bleu both around 0.03 which are confused to me. Is this good result compared to the paper?

Below is valid bleu log while training.

![image](https://user-images.githubusercontent.com/17897736/40219594-a3b883d8-5aa8-11e8-8c1b-0b4ccc3c85cf.png)
