### ISSUE TITLE
multi-cpu decoding

### ISSUE THREAD

**Issue by chanberg** [awslabs/sockeye#313]
Hi,

is there a way to decode on multiple CPU cores?

Thanks!

**Comment by fhieber** [comment]
Hi,

currently the decoding context for sockeye.translate is limited to a single device (GPU or CPU), as we do not support model parallelism.
However, the MXNet backend will anyway use multiple threads when using a CPU context (for more information on how to configure this, see here: https://mxnet.incubator.apache.org/faq/env_var.html).

You could also tools like GNU [parallel](https://www.gnu.org/software/parallel/) to shard input data and stream it to multiple decoding processes to parallelize.

**Comment by chanberg** [comment]
Thank you very much. I'll try this 👍
