### ISSUE TITLE
Recurrent Dropout

### ISSUE THREAD

**Issue by ArmageddonKnight** [awslabs/sockeye#334]
Hi there,

I have a question about your implementation on recurrent dropout:

https://github.com/awslabs/sockeye/blob/ad990095a2fe84dbf84b72b886a4c7f66d31f648/sockeye/rnn.py#L341

It seems that you defined recurrent dropout as the dropout performed on `in_transform`, but should it be performed on `h2h`? Because in my opinion, recurrent dropout corresponds exactly to input dropout, which performs on `i2h`.

Thank you.

**Comment by fhieber** [comment]
Hi,
the implementation is based on Semeniuta et al, Recurrent Dropout without Memory Loss (https://aclanthology.coli.uni-saarland.de/pdf/C/C16/C16-1165.pdf). If you look at Equation 9 in the paper, you see that they apply dropout on g_t, which corresponds to `in_transform` in the code.
