### ISSUE TITLE
sacrebleu downloads wmt16 en-de with only 154 lines for en instead of 2999

### ISSUE THREAD

**Issue by roeeaharoni** [awslabs/sockeye#337]
Hi!

For some reason, the English part of WMT16 downloaded by SacreBleu is too short, with only 154 lines.

Running the following commands:

`sacrebleu.py -t wmt16 -l en-de --echo src > valid.en`
`wc -l valid.en`
Results in:
`154 valid.en`
While:
`sacrebleu.py -t wmt16 -l en-de --echo ref > valid.de`
`wc -l valid.de`
Results in:
`2999 valid.de`

Thanks!

**Comment by mjpost** [comment]
What probably happened is the download and unprocessing got interrupted. Try this:

    rm -rf ~/.sacrebleu/wmt16
   sacrebleu -t wmt17 -l en-de --echo src | wc -l

You should get 2999 this time. I really need to add an MD5 checksum or something...

**Comment by roeeaharoni** [comment]
That worked, thanks!
