### ISSUE TITLE
Example of using pre-trained embeddings

### ISSUE THREAD

**Issue by tuglat** [awslabs/sockeye#357]
In issue #231 there was some discussion of using pre-trained word embeddings. Is this a built-in facility of sockeye, or was it a personal extension?

It would be helpful if this were more fully documented, and a simple example presented.

**Comment by tdomhan** [comment]
There is indeed a lack of documentation for this at the moment. This is definitely a supported feature. In order to use pretrained embeddings you need to call `python -m sockeye.init_embedding`.

Quoting from the CLI documentation:
```
Initializing Sockeye embedding weights with pretrained word representations.
It also supports updating vocabulary-sized weights for a new vocabulary.
Quick usage:
    python3 -m sockeye.init_embedding        \
            -w embed-in-src.npy embed-in-tgt.npy    \
            -i vocab-in-src.json vocab-in-tgt.json   \
            -o vocab-out-src.json vocab-out-tgt.json  \
            -n source_embed_weight target_embed_weight \
            -f params.init
Optional arguments:
    --weight-files, -w
        list of input weight files in .npy, .npz or Sockeye parameter format
        .npy: a single array with shape=(vocab-in-size, embedding-size/hidden-size)
        .npz: a dictionary of {parameter_name: array}
              parameter_name is given by "--names"
        Sockeye parameter: the parameter name is given by "--names"
    --vocabularies-in, -i
        list of input vocabularies as token-index dictionaries in .json format
    --vocabularies-out, -o
        list of output vocabularies as token-index dictionaries in .json format
        They can be generated using sockeye.vocab before actual Sockeye training.
    --names, -n
        list of Sockeye parameter names for embedding weights (or other vocabulary-sized weights)
        Most common ones are source_embed_weight, target_embed_weight, source_target_embed_weight,
        target_output_weight and target_output_bias.
    Sizes of above 4 lists should be exactly the same - they are vertically aligned.
    --file, -f
        file to write initialized parameters
    --encoding, -c
        open input vocabularies with specified encoding (default: utf-8)
```

This gives you a file `params.init`, which you then in turn can use in `sockeye.train` through the `--params` parameter. I hope this helps.

**Comment by davvil** [comment]
In addition to that: if you want to keep the embeddings fixed during training, you can use the parameter `--fixed-param-names` in sockeye. To find out what the parameter names are, you can start sockeye with `--dry-run` and it will show the parameter names for your model, among other output.

Please don't hesitate to ask further questions if something is unclear. The tool can be a bit confusing at first.

**Comment by fhieber** [comment]
Closing this for now, feel free to reopen if you have more questions!

**Comment by mjpost** [comment]
While this is fresh in our minds we should add a quick doc for this under `tutorials` in preparation for the web page.

**Comment by asdassZY** [comment]
Hi, thank you for your great work ! I follow tdomhan's suggestions to generate the param.init with glove embedding. But when I use it in sockeye.train through the --params parameter, some error happens:

[INFO:__main__] Training will initialize from parameters loaded from 'params.init'
[INFO:sockeye.utils] Releasing GPU 7.
[ERROR:__main__] UNCAUGHT EXCEPTION
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/zuozhu/sockeye/sockeye/train.py", line 794, in <module>
    main()
  File "/root/anaconda3/zuozhu/sockeye/sockeye/train.py", line 745, in main
    resume_training, training_state_dir)
  File "/root/anaconda3/zuozhu/sockeye/sockeye/train.py", line 659, in create_training_model
    training_model.load_params_from_file(args.params)
  File "/root/anaconda3/zuozhu/sockeye/sockeye/training.py", line 525, in load_params_from_file
    super().load_params_from_file(fname)  # sets self.params & self.aux_params
  File "/root/anaconda3/zuozhu/sockeye/sockeye/model.py", line 152, in load_params_from_file
    self.params = cell.pack_weights(self.params)
  File "/root/anaconda3/lib/python3.6/site-packages/mxnet/rnn/rnn_cell.py", line 792, in pack_weights
    return _cells_pack_weights(self._cells, args)
  File "/root/anaconda3/lib/python3.6/site-packages/mxnet/rnn/rnn_cell.py", line 48, in _cells_pack_weights
    args = cell.pack_weights(args)
  File "/root/anaconda3/lib/python3.6/site-packages/mxnet/rnn/rnn_cell.py", line 288, in pack_weights
    weight.append(args.pop(wname))
KeyError: 'decoder_rnn_l0_i2h_i_weight'

May I ask if you can help to solve this issue? Thanks!

**Comment by davvil** [comment]
Can you give more details about how you created your params.ini and about your model configuration? Sockeye is complaining about not finding decoder_rnn_l0_i2h_i_weight which is a parameter matrix for the RNN model, which is not known if you are using a transformer model (the default).

**Comment by Cartus** [comment]
Hi, Thank you for your great works!

According to the Quick Usage, --weight-files should have the shape=(vocab-in-size, embedding-size/hidden-size). However, there exist some specific words, which only appear in the vocabulary (built during training) but not show up in the pretrained-embeddings. May I ask how to deal with such words? Should we simply randomly initialize it or there is a better way?

**Comment by asdassZY** [comment]
Hi @davvil, thanks for looking into this issue and sorry for my late reply. Actually, I just follow the @tdomhan 's instruction to generate the init embedding. When I apply it into the training, error happens. Cartus above list more details.

**Comment by SamuelLarkin** [comment]
Hi,
I am also trying to use fasttext to pretrain my embeddings.  I would like to use `--weight-tying-type=src_tgt_softmax` but I think `python -m sockeye.init_embedding` doesn't support that mode.

```
--names, -n
        list of Sockeye parameter names for embedding weights (or other vocabulary-sized weights)
        Most common ones are source_embed_weight, target_embed_weight, source_target_embed_weight, target_output_weight and target_output_bias.
```

I'm getting the following error:

`RuntimeError: decoder_transformer_0_att_enc_h2o_weight is not presented`

Note that I've created my `params.init` with the following command:
```
python3 \
   -m sockeye.init_embedding \
      --weight-files $corpora/fasttext/embed.npy \
      --vocabularies-in $corpora/fasttext/vocab.json \
      --vocabularies-out $corpora/fasttext/vocab.json \
      --names source_target_embed_weight \
      --file params.init
```

**Comment by SamuelLarkin** [comment]
Humm,
  I thought that if I init_embedding for src_tgt I would be able to train using `weight_tying_type: src_trg` but I still get `RuntimeError: decoder_transformer_0_att_enc_h2o_weight is not presented`

```
python3 \
   -m sockeye.init_embedding \
      --weight-files $corpora/fasttext/embed.npy \
      --vocabularies-in $corpora/fasttext/vocab.json \
      --vocabularies-out $corpora/fasttext/vocab.json \
      --names source_target_embed_weight \
      --file params.init
```

**Comment by Cartus** [comment]
@tdomhan Thank you for the reply. It works!

**Comment by fhieber** [comment]
This issue seems solved so I am closing this. If there are more questions, please reopen.

**Comment by nellywilson** [comment]
How long does `python3 -m sockeye.init_embredding` usually take? Looks like it's just stuck on `[INFO:__main__] Initializing parameter: source_embed_weight` I'm new to using sockeye. 

My full command: 
`python3 -m sockeye.init_embedding        \
            -w ./data/embed-in-src.npy     \
            -i vocab.src.0.json   \
            -o vocab.trg.0.json \
            -n source_embed_weight \
            -f params.init`
where the -w is made simply from transforming a glove pretrained .txt file into .npy
