### ISSUE TITLE
Baseline results for cross-checking

### ISSUE THREAD

**Issue by fiqas** [awslabs/sockeye#358]
Hi,
I am playing around with your WNMT18 (https://github.com/awslabs/sockeye/tree/wnmt18/wnmt18) example. Could you add or provide baseline results (BLEU/time) for cross-checking?
Thanks a lot!

**Comment by mjdenkowski** [comment]
Thanks for the feedback!  Pre-generated models and full evaluation results are available at the link in the README.  I copied the results to the end so people can check without downloading the tarball.
