### ISSUE TITLE
Not waiting for the last decoder to be finished

### ISSUE THREAD

**Issue by xingniu** [awslabs/sockeye#367]
I was using Sockeye 1.18.4. This version was not waiting for the last decoder to be finished after finishing training -- no BLEU scores inserted into the last line of metrics.
I am also wondering why the following entry was removed from the traning log:
`INFO:sockeye.callback:_empty_decoder_metric_queue] Checkpoint [33]: Decoder finished ({'bleu-val': 0.3261684350253957, 'chrf-val': 0.5191681893124609, 'avg-sec-per-sent-val': 0.09754898762702942})`

**Comment by fhieber** [comment]
Hi @xingniu , thanks for noticing this! This bug must have sneaked in with the recent re-factor.
#368 should fix this.

**Comment by fhieber** [comment]
I am closing this after #368 was merged. If you encounter more problems related to this, feel free to reopen.
