### ISSUE TITLE
sockeye.utils.SockeyeError when train WMT

### ISSUE THREAD

**Issue by huangzhiyuan** [awslabs/sockeye#383]
The version I used is Sockeye 1.18.9, command I used to train is below:

`
python -m sockeye.train -s corpus.tc.BPE.de.tmp \
                        -t corpus.tc.BPE.en.tmp \
                        -vs newstest2016.tc.BPE.de \
                        -vt newstest2016.tc.BPE.en \
                        --bucket-width 5 \
                        --embed-dropout 0.2 \
                        --optimized-metric bleu \
                        --decode-and-evaluate 500 \
                        --optimizer sgd \
                        --max-seq-len 50 \
                        --batch-size 128 \
                        -o 8-layer_wmt_model \
                        --num-layers 8 \
                        --use-cpu
`

And I got the following errors.
`[INFO:sockeye.checkpoint_decoder] Created CheckpointDecoder(max_input_len=-1, beam_size=5, model=8-layer_wmt_model, num_sentences=500, context=cpu(0))
[ERROR:__main__] Uncaught exception
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/virtu_gnmt/lib/python3.6/site-packages/sockeye/train.py", line 837, in <module>
    main()
  File "/home/ubuntu/virtu_gnmt/lib/python3.6/site-packages/sockeye/train.py", line 833, in main
    existing_parameters=args.params)
  File "/home/ubuntu/virtu_gnmt/lib/python3.6/site-packages/sockeye/training.py", line 493, in fit
    self._check_args(metrics, early_stopping_metric, lr_decay_opt_states_reset, lr_decay_param_reset, decoder)
  File "/home/ubuntu/virtu_gnmt/lib/python3.6/site-packages/sockeye/training.py", line 883, in _check_args
    utils.check_condition(early_stopping_metric in metrics, "Early stopping metric must be tracked.")
  File "/home/ubuntu/virtu_gnmt/lib/python3.6/site-packages/sockeye/utils.py", line 117, in check_condition
    raise SockeyeError(error_message)
sockeye.utils.SockeyeError: Early stopping metric must be tracked.`

While it works when use old version, for example 1.16.2 , but why?  @rongzha1, @pengzhao-intel

**Comment by fhieber** [comment]
Hi @huangzhiyuan , indeed that is a bug that was introduced with the Trainer refactoring.
I created a fix here: #384

**Comment by spandanagella** [comment]
I was able to train the model with --optimized_metric bleu. However, my computed bleu score is always 0 and it quits after 10 epochs since I have set --max-num-checkpoint-not-improved to 10. Any idea why the computed bleu score is 0? I have double checked my validation files and they seem right. Also my perplexity scores are looking reasonable.

I'm using lexical_constraints branch.

**Comment by spandanagella** [comment]
Hi @fhieber, I got the newest version and its working. The problem was if you are using older sockeye version. Thank you for respsonding.

Actually @mjpost helped me with making lexical constraints work with new master.

Thanks

**Comment by fhieber** [comment]
Glad to hear it now works!
