### ISSUE TITLE
Lots of GPU memory used briefly when plateau-reduce reduces learning rate

### ISSUE THREAD

**Issue by sliedes** [awslabs/sockeye#389]
I have often seen that my model fits in the GPU memory quite reasonably otherwise, but the training process crashes with cudaMalloc failure immediately after the plateau LR scheduler has decided to halve the learning rate (using the default scheduler parameters).

[Speculation:] Could it be that at that point GPU memory is allocated for the model twice for a very short period?

I have seen this with recent HEAD. If you have trouble reproducing, I can try to get more logs and an exact git revision.

**Comment by tdomhan** [comment]
Thanks for reporting! The learning rate scheduler shouldn't have an impact on memory usage. What are the parameters you are using for training?
If you use `--learning-rate-decay-param-reset`  this could have an impact on memory consumption as it will load the best parameters into memory. In general however the parameters only take up a small amount of memory compared to the rest of the computation graph so I would not expect the memory consumption to double.

**Comment by fhieber** [comment]
closing as there are no updates. Feel free to reopen if issue turns up again.
