### ISSUE TITLE
Error while training with multi GPUs

### ISSUE THREAD

**Issue by xinyu-intel** [awslabs/sockeye#400]
Hi all, I came across errors while training GNMT with four Tesla P100s using the following command:

```
python -m sockeye.train -s corpus.tc.BPE.de \
                        -t corpus.tc.BPE.en \
                        -vs newstest2016.tc.BPE.de \
                        -vt newstest2016.tc.BPE.en \
                        --num-embed 256 \
                        --rnn-num-hidden 512 \
                        --rnn-attention-type dot \
                        --max-seq-len 60 \
                        --decode-and-evaluate 500 \
                        --batch-size 512 \
                        --use-tensorboard \
                        -o wmt_model_beam_3 \
                        --num-layers 8 \
                        --device-ids 0 1 2 3
```

sockeye version: 1.16.2
mxnet version: master(1.2.0 rc3)
Default beam size is set to 10.

The problem is that it stuck and could not move on when docoding:

```
[2018-05-17:23:46:30:INFO:sockeye.utils:log_gpu_memory_usage] GPU 0: 7013/16280 MB (43.08%) GPU 1: 7041/16280 MB (43.25%) GPU 2: 7081/16280 MB (43.50%) GPU 3: 7111/16280 MB (43.68%)
[2018-05-17:23:46:30:INFO:sockeye.training:_fit] Checkpoint [8]	Updates=8000 Epoch=0 Samples=4096000 Time-cost=561.911
[2018-05-17:23:46:30:INFO:sockeye.training:_fit] Checkpoint [8]	Train-perplexity=255.463719
[2018-05-17:23:46:32:INFO:sockeye.training:_evaluate] Checkpoint [8]	Validation-perplexity=422.777642
[2018-05-17:23:46:32:INFO:sockeye.callback:_empty_decoder_metric_queue] Checkpoint [7]: Decoder finished ({'bleu-val': 0.002235456319813008, 'chrf-val': 0.078263341811670134, 'avg-sec-per-sent-val': 0.2690639548301697})
[2018-05-17:23:46:32:INFO:sockeye.callback:_start_decode_process] Starting process: Decoder-8
```

Also, from `nvidia-smi`, it still occupy GPU memory with no changes.

And I find that it determined the last GPU as the decode node while training. So, is it possible that this GPU was OOM?

```
[2018-05-17:22:30:45:INFO:__main__:determine_decode_and_evaluate_context] Decode and Evaluate Device(s): gpu(3)
```

Personally, I guess it is not very easy for GPU to handle multi instance task(training and decoding). Is it possible for users to determine which GPU for training and which for decoding manually?

Thanks!

+@pengzhao-intel @TaoLv for comments.

**Comment by fhieber** [comment]
Hi @xingniu, you can put the checkpoint decoder on a CPU by adding the `--decode-and-evaluate-use-cpu` flag.
You can also use a specific device for checkpoint decoding with `--decode-and-evaluate-device-id`.
I am not sure if Sockeye 1.16 already has these flags.

Regarding your problem, if the GPU device with the checkpoint decoder process would be OOM you should see that in the logs so I don't think thats the problem.
Older versions of Sockeye (maybe 1.16) theoretically allowed more than one concurrent CheckpointDecoder process, but would wait if there is more than n concurrent ones. I think n was set to 1 anyway but there was no logging about the waiting being shown.
In the latest version of Sockeye there can only be one CheckpointDecoder and if you have to wait for it at a checkpoint before spawning a new one, there is a logging message about the waiting time. Given your large model, I assume that this is the problem. You can decrease the frequency of checkpoints to avoid this, or decrease the size of the validation data sample you are decoding maybe.
In any case, I would suggest updating to a later version of Sockeye (~1.18).

**Comment by xingniu** [comment]
I am not @xinyu-intel , :P

**Comment by xinyu-intel** [comment]
Okay, thanks for your answer and I'll try to use these flags.

**Comment by fhieber** [comment]
closing for now, feel free to reopen if your problem remains.
