### ISSUE TITLE
Training a big transformer fails

### ISSUE THREAD

**Issue by alexeib** [awslabs/sockeye#410]
Hello! I am trying to train a big transformer using sockeye. Here's the command that I used:

python -m sockeye.train -s train.en -t train.de -vs newstest2013.en -vt newstest2013.de --shared-vocab --num-words 32768:32768 --encoder transformer --decoder transformer --num-layers 6:6 --transformer-model-size 1024 --transformer-attention-heads 16 --transformer-feed-forward-num-hidden 4096 --transformer-positional-embedding-type fixed --num-embed 1024:1024 --weight-tying --weight-tying-type src_trg --min-updates 300000 --max-updates 300000 --embed-dropout 0.3:0.3 --transformer-dropout-prepost 0.3 --initial-learning-rate 0.0005 --learning-rate-warmup 4000 --learning-rate-scheduler-type fixed-rate-inv-sqrt-t --batch-size 3500 --batch-type word --checkpoint-frequency 4000 --device-ids 1 --max-seq-len 128 -o ~/model

I have two problems trying to run this:

1. Training on multiple GPUs (by changing --device-ids above to, for example, -1) does not work. Although training starts successfully, once it gets to saving the model (at batch 4000) it fails when trying to clone the model with an illegal cuda operation error. I tried rebuilding mxnet with dmshadow_use_pascal = 1 but while the stack trace changed, the fact that it would crash when trying to save the model (somewhere in save()) did not. Unfortunately I don't have stack traces now, but I can try to recreate them if you think it would be helpful.

2. Training on a single GPU also does not work. Again, it trains successfully but once it gets to saving the model it crashes with:

```
[INFO:sockeye.training] Epoch[0] Batch [4000]	Speed: 123.76 samples/sec 4001.26 tokens/sec 1.00 updates/sec	perplexity=565.674783
[INFO:sockeye.utils] Releasing GPU 1.
[ERROR:__main__] Uncaught exception
Traceback (most recent call last):
  File "/private/home/abaevski/.conda/envs/sockeye/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/private/home/abaevski/.conda/envs/sockeye/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/home/abaevski/sockeye/sockeye/train.py", line 837, in <module>
    main()
  File "/private/home/abaevski/sockeye/sockeye/train.py", line 833, in main
    existing_parameters=args.params)
  File "/private/home/abaevski/sockeye/sockeye/training.py", line 565, in fit
    self._save_params()
  File "/private/home/abaevski/sockeye/sockeye/training.py", line 915, in _save_params
    self.model.save_params_to_file(self.current_params_fname)
  File "/private/home/abaevski/sockeye/sockeye/training.py", line 333, in save_params_to_file
    super().save_params_to_file(fname)
  File "/private/home/abaevski/sockeye/sockeye/model.py", line 160, in save_params_to_file
    utils.save_params(self.params.copy(), fname, self.aux_params.copy())
  File "/private/home/abaevski/sockeye/sockeye/utils.py", line 154, in save_params
    mx.nd.save(fname, save_dict)
  File "/private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/ndarray/utils.py", line 273, in save
    keys))
  File "/private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/base.py", line 210, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:40:33] src/storage/./pooled_storage_manager.h:108: cudaMalloc failed: out of memory

Stack trace returned 10 entries:
[bt] (0) /private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x5b) [0x7fc311e2980b]
[bt] (1) /private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7fc311e2a378]
[bt] (2) /private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/libmxnet.so(mxnet::storage::GPUPooledStorageManager::Alloc(mxnet::Storage::Handle*)+0x154) [0x7fc31479b9a4]
[bt] (3) /private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/libmxnet.so(mxnet::StorageImpl::Alloc(mxnet::Storage::Handle*)+0x5d) [0x7fc31479d94d]
[bt] (4) /private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/libmxnet.so(mxnet::NDArray::CheckAndAlloc() const+0x1b1) [0x7fc311f07fa1]
[bt] (5) /private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/libmxnet.so(+0x30a9453) [0x7fc31430a453]
[bt] (6) /private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/libmxnet.so(mxnet::imperative::PushFCompute(std::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&)::{lambda(mxnet::RunContext)#1}::operator()(mxnet::RunContext) const+0x1d5) [0x7fc314334405]
[bt] (7) /private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/libmxnet.so(+0x3523acb) [0x7fc314784acb]
[bt] (8) /private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x8e5) [0x7fc31477f955]
[bt] (9) /private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/libmxnet.so(void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<dmlc::ManualEvent> const&)+0xeb) [0x7fc3147961fb]
```
I don't really know what's going on but one guess is that it tries to clone the model when saving it and runs out of memory as 2 models don't fit into gpu memory.

I tried both the master branch as of last week and the latest tagged release at the time (1.18.10). I also tried latest mxnet-cuda90 and also built it from source.

Any idea what's wrong and how I can get past these errors? 

Thanks!

**Comment by alexeib** [comment]
BTW i tried getting the latest master and trying to run a transformer with default everything and it just consistently crashes with

```
  File "/private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 1894, in asscalar
    return self.asnumpy()[0]
  File "/private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 1876, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/private/home/abaevski/.conda/envs/sockeye/lib/python3.6/site-packages/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [08:39:47] src/storage/./pooled_storage_manager.h:108: cudaMalloc failed: out of memory
```

even if i set batch size to something very small. this is on machines with 16gb of gpu memory

**Comment by fhieber** [comment]
Hi @alexeib this is strange.

I don't know exactly if a big transformer with this batch size (and max sequence length) would fit on a single GPU, but the defaults should definitely fit.
Regarding the 'model', i.e. the parameters: The actual parameters are not that big (maybe a couple hundred MB). What uses most of the GPU memory is the storage for intermediate outputs in the computation graph.

Your errors sound like a problem with mxnet and/or cuda drivers. For example, changing device ids from `1` to `-1` shouldn't change anything in terms of data parallel training, but just give Sockeye the ability to acquire any available GPU instead of the second one (index 1).
Have you tried it with pip-installed mxnet (`pip install mxnet-cu90==1.2.0`)? Also, you may want to make sure to uninstall any other mxnet version (self-compiled or pip-installed) first before doing this.

Also, could you give the full stacktrace of the error in your last comment, i.e. indicating at which point in Sockeye code `asscalar()` is called?

**Comment by alexeib** [comment]
ok with the latest code it seems that it doesnt crash at checkpointing anymore, even with the big transformer. so i can train successfully, but i have to keep one gpu just for decoding and not use it for training

**Comment by fhieber** [comment]
Ok, so you maximum sequence length is very long (256). Along with this batch size on a single GPU (even with 16GB) I doubt that this can fit.

A 'big' 6-layer transformer on 4 GPUs with word-based batch size and max-len 100 should probably be fine (I haven't tested this myself in a while).

If you have a machine with multiple GPUs (say 4), use `--device-ids -4` not `--device-ids 4` (the latter means 'use only GPU with id 4 - which wouldn't exist on a 4 GPU machine (0-indexed)).

I suggest reducing the batch size and/or the maximum sequence length.

**Comment by fhieber** [comment]
not exactly. The maximum sequence length determines the largest bucket (i.e. the default bucket) for the BucketingModule in MXNet. While the actual batch sizes with that sequence length may be small (as stated in the log which outputs the 'bucket batch sizes we compute to', I think MXNet still initially allocates the default (sub)module with the largest batch size and the largest sequence length (the default bucket key). 
I think this has to do with memory sharing, but I am not an expert in memory planning in MXNet to be honest.
Can you try if changing `--max-seq-len` while keeping the word-based batch size constant has an effect on overall memory usage?

**Comment by tdomhan** [comment]
just as a comment: If you have 4 GPUs, I'd probably use all 4 of them for training and decode either on the CPU or share a GPU for decoding. Having a GPU dedicated for training will most likely result in it being idle for a large time.
