### ISSUE TITLE
Running sockeye using multiple CPUs

### ISSUE THREAD

**Issue by SamuelLarkin** [awslabs/sockeye#429]
Hi,
  I need to run sockeye.translate using multiple CPUs.  I've tried adding --use-cpu and --device-ids -20 hoping to use 20 CPUs but it doesn't seem to be using more than 2 as per top saying that the process is using ~200% CPU usage.  The way I read the documentation, --devices-ids -20 in conjunction with --use-cpu should make my translation run use 20 CPUs.

Note that my installation is through conda and it is cu80 based.  Should I create a separate conda environment with mxnet-mkl and `pip install sockeye`?

**Comment by tdomhan** [comment]
The ```--device-ids ``` argument actually refers to GPUs no CPUs. For using the CPU you only need to the ```--use-cpu``` flag. When running on the CPU MKL is definitely recommended (a separate environment with MKL is one way). Then there are some additional MXNet flags you can set. @mjdenkowski  can share more about that.

**Comment by asmushetzel** [comment]
Just to avoid confusion: I assume you want to run on multiple CPU-cores, not on physically different CPU-devices/chips. Correct?
If above is correct, and then the system will use automatically multiple cores. MXNet as the underlying DL-framework uses OpenMP as the parallelization framework, so the number of threads can be controlled by usual OpenMP-environment variables e.g.  OMP_NUM_THREADS.
Though this should be unnecessary as the system will automatically figure that out internally. 

If you see something like 200% CPU usage in "top" when running on a 20-core machine, then certainly something is not working as expected. It looks as if the BLAS library that is part of the installation works just single threaded (the bulk of the computation in Sockeye is matrix-matrix multiplies and the key to speedup is to parallelize internally each matrix-matrix multiply).
 
My first advice would be to install the MKL version in a clean separate conda environment and give it a try.

**Comment by mjdenkowski** [comment]
+1 to Asmus's advice.  There is a PyPI version of MXNet that uses the open source [MKL-DNN](https://github.com/intel/mkl-dnn), mxnet-mkl (or mxnet-cu80mkl, mxnet-cu90mkl, etc.).  This is easy to install but not currently as fast as MXNet built from source with the [full version if Intel MKL](https://software.intel.com/en-us/mkl).  For CPU mode, you can also try setting the environment variable MXNET_ENGINE_TYPE=NaiveEngine for better performance.

**Comment by tdomhan** [comment]
closing for now, feel free to reopen if you have additional questions or problems.

**Comment by SamuelLarkin** [comment]
Working recipe to create a conda environment to run sockeye in CPU mode.

```
conda create --name ubuntu_sockeye_cpu python=3  --yes
conda activate ubuntu_sockeye_cpu
pip install sockeye==1.18.20 mxnet-cu80mkl
```
