### ISSUE TITLE
Memory issues with batch-type = word

### ISSUE THREAD

**Issue by slyforce** [awslabs/sockeye#437]
Batch sizes are estimated per bucket in order to have roughly the same amount of words per bucket when using the batching by words option.
However the last bucket always tends to have a higher batch size than the second-to-last bucket and ends up with a relatively higher number of tokens per batch (up to 20% more in my case), which provides an upper bound for the memory consumption during training.

This is caused by the last section of code in data_io.define_bucket_batch_sizes lines 193-203. 
Could you explain the reasoning behind this behaviour and if it's OK to leave to toggle off for training?

**Comment by tdomhan** [comment]
The reason for the is the way memory sharing works in the BucketingModule in MXNet. Namely, it works by creating a computation graph defined through the default bucket key and then reuses memory from that computation graph for all other computation graphs of other buckets. Now one needs to make sure that all NDArrays used by the smaller buckets fit into the ones used by the default (largest bucket). We adjust the batch size of the last bucket accordingly and make it the default. Doing this will actually reduce the overall memory usage as this allows for memory sharing.
I hope that makes sense.

**Comment by slyforce** [comment]
Alright, I understand. Thanks for the explanation!
