### ISSUE TITLE
Obtaining second-order derivatives for the loss wrt arbitrary parameters in the computation graph

### ISSUE THREAD

**Issue by noisychannel** [awslabs/sockeye#438]
Hello! 

We're trying to obtain the second-order derivatives of the loss wrt all parameters in the computation graph. This is so that we can regularize some of these parameters. 

Is this possible to do in Sockeye/MXnet?

**Comment by mjdenkowski** [comment]
Hi Gaurav,

The answer appears to be that it's under development but not high priority (see [https://github.com/apache/incubator-mxnet/issues/10002](this MXNet issue).  If this is something important for your work, you may want to follow up on that issue to see how progress is going.

**Comment by noisychannel** [comment]
Thanks, Michael. We're trying to figure out a workaround for now.
