### ISSUE TITLE
Enhance Sockeye translation time 

### ISSUE THREAD

**Issue by fture-tm** [awslabs/sockeye#443]
After training my machine according to this tut https://github.com/awslabs/sockeye/tree/master/tutorials/wmt 
and with training arguments --seed=1 --batch-type=word --batch-size=2000 --checkpoint-frequency=4000 --embed-dropout=0:0 --encoder=transformer --decoder=transformer --num-layers=6:6 --transformer-model-size=512 --transformer-attention-heads=8 --transformer-feed-forward-num-hidden=2048 --transformer-preprocess=n --transformer-postprocess=dr --transformer-dropout-attention=0.1 --transformer-dropout-prepost=0.1 --transformer-positional-embedding-type fixed --fill-up=replicate --max-seq-len=100:100 --label-smoothing 0.1 --num-embed 512:512 --num-words 50000:50000 --word-min-count 1:1 --optimizer=adam --optimized-metric=perplexity --initial-learning-rate=0.0001 --learning-rate-reduce-num-not-improved=8 --learning-rate-reduce-factor=0.7 --learning-rate-scheduler-type=plateau-reduce --learning-rate-warmup=0 --max-num-checkpoint-not-improved=32 --min-num-epochs=0 --max-updates 1001000 --weight-init xavier --weight-init-scale 3.0 --weight-init-xavier-factor-type avg -o /home/ubuntu/main_train_v2/train_data/wmt_model

when I need to translate from english to arabic , it took a total time **1.8 seconds** , **so how can I enhance the time of translation**

**Comment by mjdenkowski** [comment]
Are you asking about speeding up translation?

If you're running on GPUs, make sure you install the CUDA version of MXNet (mxnet-cu91 or similar).  You can also translate much faster in batch mode (`--batch-size 32 --chunk-size 1000`).

On CPUs, you can install the MKL version of MXNet (mxnet-mkl).  You can also use target vocabulary selection:
1. [Learn a lexical table](https://github.com/awslabs/sockeye/tree/master/contrib/fast_align) with fast_align.
2. Convert it to a top-k lexicon (run `python -m sockeye.lexicon create -h` for info).
3. Translate with the `--restrict-lexicon` option.

**Comment by mjdenkowski** [comment]
Closing for now.  Hopefully these changes allow you to decode fast enough for your use case.
