### ISSUE TITLE
Adding metadata for source sentences as arguments

### ISSUE THREAD

**Issue by beckdaniel** [awslabs/sockeye#45]
Greetings,

Some published NMT architectures rely on adding extra linguistic information to the source sentence. Examples include POS tags (https://www.aclweb.org/anthology/U/U16/U16-1001.pdf) and syntactic trees (http://www.aclweb.org/anthology/P16-1078 https://arxiv.org/pdf/1704.04675.pdf). This issue is an enhancement idea to add provisions to sockeye to read this kind of metadata into the toolkit.

At least initially, the idea is *not* to implement any of these encoders, but just make sure the metadata is properly read and propagated all the way to the encoder interface. I was thinking about having an optional keyword "metadata" to the "encode" method in the Encoder interface. Then users can extend or implement their own encoders while safely assuming the metadata (POS, syntactic trees, etc.) will be available in that metadata field.

I started to implement this idea in the context of adding semantic graphs to the input. Code is being hosted here:
https://github.com/ws17mt/sockeye/tree/source_metadata

I am happy to keep working on this but some feedback would be appreciated. Specifically:
- Is the "metadata keyword" approach the best?
- How does this would affect bucketing? Right now I am just propagating the metadata through the bucketing interface to make sure everything reaches the decoder but the bucketing approaches might not be useful in this setting anymore.
- How to make things work at decoding time?
- I am assuming tokens in the metadata are separated by spaces so I can just reuse the data reading methods. Not sure if this is the best approach though.

**Comment by fhieber** [comment]
Hi Daniel,

thanks for bringing this up!
Let me try to answer your questions and bring up a couple of suggestions to discuss.

Bucketing is only a problem, if the metadata sequence length is different to the input sequence length, as then the bucket key would need to be made 3-dimensional: (source length, metadata length, target length). In the case of word-level features, such as POS tags, bucketing can remain as is. Does your use case with GCNs fall into the latter category?

An alternative to modifying the encoder interface to allow for additional metadata, could be to make the source input tensor to the Embedding encoder 3-dimensional: batch, time, channels, where channel represents the word sequence, and the others metadata or word-level features. Similarly, the label tensor would have an additional dimension.
This would keep the interface clean and unchanged, but would only work if the additional features are only required in the embedding (which would concatenate the separate embeddings into a single vector, to be passed into the RNN encoders).

Regarding data I/O, I think it would make sense to build something similar to what OpenNMT does (http://opennmt.net/OpenNMT/data/word_features/) and append features directly to tokens in the input data with a special separator token. One would then also make sure to share that I/O logic in the inference/translate CLI.

We are happy to discuss this in more detail in this issue!

**Comment by beckdaniel** [comment]
Hi Felix, thanks for your feedback.

At least for the semantic graphs we cannot assume the length of the metadata matches the length of the input sentence. In this specific case, the metadata is a graph currently represented as an adjacency list. This means that, in theory, the "length" in terms of number of edges can vary between n and n^2, where n is the length of the sentence. I think this rules out the approach used by OpenNMT, unfortunately.

I also think extending the input tensor might not be enough. Specifically for the semantic graphs (but also for syntactic trees), the idea is that the structure provided by the metadata will guide operations in their respective encoder. For instance, a GCN encoder would use the graph information to perform convolutions on word embeddings according to their neighbours in the graph. This means that operations happen on upper layers beyond the Embedding one.

**Comment by fhieber** [comment]
Hi Daniel,

I see. In this case I think you won't get around either adding a third dimension to the bucket_key, or changing the bucket sizes for source so that adjacency lists fit in. In any case, this looks like an entirely different data iterator and encoder implementation so I would say this should stay separate from the current encoder interface. Introducing an entirely new type of encoder might make more sense.

On a related note: MXNet developers are working on dynamic graphs as part of a new API (curently named foo). Here is a PR that showcases how to implement a child-sum tree lstm with it: https://github.com/dmlc/mxnet/pull/6921

**Comment by beckdaniel** [comment]
Hi Felix,

Sorry for the late reply. I managed to create a new iterator for the metadata and I am trying to propagate that to the encoder. Right now, I just want the metadata to reach the default sockeye encoder (BiRNN) and let the encoder simply ignore it. However, I a running into the following error:

```
ValueError: You created Module with Module(..., data_names=['source', 'source_length', 'target', 'source_metadata']) but input with name 'source_metadata' is not found in symbol.list_arguments(). Did you mean one of:
	target
	source_length
	source
	target_label
```

To replicate this fully, you can checkout my branch:

https://github.com/beckdaniel/sockeye/tree/source_metadata

and run

`sh data/toy/run_ignore.sh`

I am not 100% sure but it seems like MXNet somewhat expects 'source_metadata' to be used somewhere in the graph. It seems that the '_build_module' method gives the 'data_names' according to the iterators I used to read all the data. Simply removing 'source_metadata' from 'data_names' does not work because then MXNet complains about the iterator having a 'source_metadata' DataDesc which is not in 'data_names'.

It seems to me that it is going to be hard to decouple reading extra data without actually using it in the graph. Unless I am missing something and there is an easy way to bypass this check?

**Comment by fhieber** [comment]
Hi Daniel,

yes it looks like your graph does not contain this node.
Looking at your branch here: https://github.com/beckdaniel/sockeye/blob/source_metadata/sockeye/encoder.py#L443
it seems that the metadata passed in here is not used in any way to interact with the source argument. 
Hence it wont be included in the graph and the resulting module does not expect such a data_name or data from the iterator.

**Comment by fhieber** [comment]
@beckdaniel  Given our offline discussion we had in Pittsburgh, I am closing this for now. Feel free to re-open if you have new questions or suggestions.
