### ISSUE TITLE
pip installs test/ and contrib/ directories

### ISSUE THREAD

**Issue by mjpost** [awslabs/sockeye#453]
When installing via pip, it creates a sockeye/ directory (as it should), but also creates our test/ and contrib/ directories, e.g.,

    $ ls /usr/local/lib/python3.6/site-packages
    [snip]
    contrib/
    sockeye/
    test/

Our `setup.py` script has "test" in the ignore list but it is clearly not being ignored. We shouldn't be including these files.

**Comment by tdomhan** [comment]
thanks for bringing this up! We should make sure to not include the `test` package and consider renaming `contrib` to `sockeye_contrib` as we're otherwise polluting people's `site-packages` with a very generic package name.

**Comment by mjdenkowski** [comment]
Autopilot should be fine with a batch find-and-replace `contrib` -> `sockeye_contrib`.

**Comment by mjpost** [comment]
I don't see any problems, but what's the reason for this change? Just a preference?

**Comment by fhieber** [comment]
@mjpost the reason is this issue that you created :) installing a generically named package called 'contrib' to users' site-packages doesn't sound like a good idea.

**Comment by mjpost** [comment]
Oh, I see, you’re still installing contrib. Another option would be to remove contrib entirely. I don’t think autopilot needs to be included (you could turn it into its own separate pypi module), and sacrebleu could also be used only via import as a standard external module.

**Comment by fhieber** [comment]
There is more things in contrib than autopilot and sacrebleu and if I remember correctly we had talked about a separate install of sacrebleu and concluded that it would make things more complicated.
If renaming contrib to sockeye_contrib would be an option, I would suggest even go further and just move contrib into sockeye: `sockeye.contrib.{autopilot,sacrebleu,rouge,vis_tool}`
This would lead to a single folder created during pip install for users.

**Comment by tdomhan** [comment]
would this work with sacrebleu? Either `sockeye_contrib` or merging everything into one package sounds good. I think I'd slightly favor keeping a separate folder.

**Comment by fhieber** [comment]
ok, I'll create a PR with the rename

**Comment by fhieber** [comment]
#537

**Comment by mjpost** [comment]
Sounds good to me.
