### ISSUE TITLE
Sockeye translate api

### ISSUE THREAD

**Issue by nabawy-abbas** [awslabs/sockeye#463]
We have implemented out MT using sockeye, is there any available API to communicate with sockeye translate?

**Comment by omarkaraksi** [comment]
I also have the same problem I needed a REST API.

**Comment by tdomhan** [comment]
There are no REST API as part of Sockeye and you would need to implement REST model serving manually (integrating with whatever pre-processing you're doing before you model) and using the `load_models` and `Translator` mentioned above. Defining the Python level translation API more explicitly is something that might make sense to add in the future.

**Comment by mjpost** [comment]
I think we do have something close to a formal API. The preferred approach is to construct [inference.TranslatorInput](https://github.com/awslabs/sockeye/blob/3df3e50be89793a416de8111003da1473a0685bb/sockeye/inference.py#L569) objects, which are then passed to [Translator.translate()](https://github.com/awslabs/sockeye/blob/3df3e50be89793a416de8111003da1473a0685bb/sockeye/inference.py#L1070), which will translate a list of such objects as a batch. There are a handful of convenience functions for building these objects from [plain text](https://github.com/awslabs/sockeye/blob/3df3e50be89793a416de8111003da1473a0685bb/sockeye/inference.py#L660), from [tab-delimited input](https://github.com/awslabs/sockeye/blob/3df3e50be89793a416de8111003da1473a0685bb/sockeye/inference.py#L706) (for source factors), and from [JSON strings](https://github.com/awslabs/sockeye/blob/3df3e50be89793a416de8111003da1473a0685bb/sockeye/inference.py#L671). You can see how this is done in [translate.py](https://github.com/awslabs/sockeye/blob/master/sockeye/translate.py), the command-line API.

**Comment by fhieber** [comment]
closing, feel free to reopen if you have more questions about the existing API.
