### ISSUE TITLE
Attention probabilities and word alignments.

### ISSUE THREAD

**Issue by tomsbergmanis** [awslabs/sockeye#469]
Are you planning to implement functionality to get word alignments out of transformer attention matrices?
Word alignments are often important to restore the source side document markup.

**Comment by tdomhan** [comment]
We don't currently support this. The additional complication with the transformer is that you have 8 attention matrices (heads) per layer. So with 6 layers you have 48 matrices. How do you plan on using these?

**Comment by tomsbergmanis** [comment]
I was asked to figure out if it is possible to get word alignments from attention matrices, but thus far in sockeye it has been a bit challenging to get attention matrices themselves. Or is it just me?

**Comment by tomsbergmanis** [comment]
@mjpost
Thank you for your input! 
I agree, but I still need to convince other people about it :)
The problem with post-processing is that unlike SMT, NMT can easily produce translations that are unlikely to be aligned correctly with fastalign, for example. That is - sometimes translations are A1A2B1B2->T(A1)T(B1)T(A2)T(B2) which then breaks SMT assumptions.

**Comment by mjpost** [comment]
I agree that fast_align is unlikely to be perfect, either. But I don't understand your objection. Fast align can handle that permutation fine, and so can SMT.

**Comment by bricksdont** [comment]
@tomsbergmanis Soft attention weights from an NMT system are not a drop-in replacement for word alignments. For instance, there are cases where most of the attention "lags behind" the token it should place the most emphasis on. For an example, see Figure 9 here:

http://www.aclweb.org/anthology/W17-3204

For tag handling (i.e. reinsertion of markup into translations) you should not rely on attention weights. The recommended method is to train a separate word alignment model (external to the NMT system), for instance `fast_align` as mentioned by @mjpost. Then use those external alignments to guide reinsertion / injection of tags.

**Comment by fhieber** [comment]
Closing for now. Feel free to reopen if this discussion should be continued.
