### ISSUE TITLE
How to measure the performance of translation when inference?

### ISSUE THREAD

**Issue by huangzhiyuan** [awslabs/sockeye#475]
As I know, when run inference with command python3 -m sockeye.translate ---- only can get the total time and speed as below:
```
[INFO:__main__] Translating...
[INFO:__main__] Processed 2999 lines in 94 batches. Total time: 176.0704, sec/sent: 0.0587, sent/sec: 17.0330
```
While the model has Validation-perplexity and bleu-val to measure performance in the process of training. But how to score the performance of translation, anything I missed?

**Comment by bricksdont** [comment]
The translation interface does not evaluate the translations, because you do not always have a reference translation.

If you have a reference, you can use the `evaluate` CLI for that, after translation:

    python -m sockeye.evaluate --help

**Comment by xinyu-intel** [comment]
@bricksdont I just trained a 8 layer rnn model and got the following result:
```
[INFO:sockeye.training] Starting process: Decoder-52
[INFO:sockeye.inference] Loading 1 model(s) from ['gnmt_model'] ...
[INFO:sockeye.training] Validation-bleu has not improved for 8 checkpoints, best so far: 0.729169
```
Evaluate:
```
[INFO:__main__] bleu	(s_opt)	chrf	(s_opt)
0.165	(-)	0.479	(-)
```
Is this bleu value correct? It is far away from the bleu value from the [paper](https://arxiv.org/abs/1712.05690).

By the way, how to use sockeye to build a GNMT model to align with the tensorflow's [config](https://github.com/tensorflow/nmt/blob/master/nmt/standard_hparams/wmt16_gnmt_8_layer.json)?

**Comment by bricksdont** [comment]
This is a different question, please open a new issue for that.

**Comment by tdomhan** [comment]
closing this issue. We can discuss this further on issue https://github.com/awslabs/sockeye/issues/479.
