### ISSUE TITLE
pylint==2.0.0 complains about bare `except` statement

### ISSUE THREAD

**Issue by fhieber** [awslabs/sockeye#478]
travis has updated pylint to verison 2.0.0 which [complains](https://travis-ci.org/awslabs/sockeye/builds/404257699) about the following:
```
************* Module sockeye.utils
sockeye/utils.py:632:16: E0705: The except handler raises immediately (try-except-raise)
pylint found errors in the sockeye package
```

The corresponding line of code in `acquire_gpus()` is::
```python
[...]
            if master_lock is not None and not any_failed:
                try:
                    yield acquired_gpus
                except:
                    raise
                return
[...]
```
@tdomhan do you know what kind of exceptions to expect here? Changing to `except Exception` is equally objectionable for pylint.

**Comment by fhieber** [comment]
intermediate "solution" in #481

**Comment by tdomhan** [comment]
I wonder if the raise is actually necessary. I remember running into some unintuitive behavior when exceptions were thrown in the generator.

**Comment by fhieber** [comment]
no objections from my side to removing it :)

**Comment by tdomhan** [comment]
ok, let's test if we can potentially remove it.

**Comment by mjpost** [comment]
travis is now at pylint==2.0.1, which returns a number of new errors in the image_captioning module:

```bash
sockeye/image_captioning/train.py:268:20: E1101: Instance of 'Namespace' has no 'seed' member (no-member)
sockeye/image_captioning/train.py:271:36: E1101: Instance of 'Namespace' has no 'output' member (no-member)
sockeye/image_captioning/train.py:277:43: E1101: Instance of 'Namespace' has no 'quiet' member (no-member)
sockeye/image_captioning/train.py:282:45: E1101: Instance of 'Namespace' has no 'max_seq_len' member (no-member)
sockeye/image_captioning/train.py:290:53: E1101: Instance of 'Namespace' has no 'device_ids' member (no-member)
sockeye/image_captioning/train.py:291:50: E1101: Instance of 'Namespace' has no 'use_cpu' member (no-member)
sockeye/image_captioning/train.py:292:65: E1101: Instance of 'Namespace' has no 'disable_device_locking' member (no-member)
sockeye/image_captioning/train.py:293:51: E1101: Instance of 'Namespace' has no 'lock_dir' member (no-member)
sockeye/image_captioning/train.py:295:11: E1101: Instance of 'Namespace' has no 'batch_type' member (no-member)
sockeye/image_captioning/train.py:296:28: E1101: Instance of 'Namespace' has no 'batch_size' member (no-member)
```

**Comment by tdomhan** [comment]
we should probably also fix our pylint version and try to update manually in order to prevent a specific version of pylint from blocking Travis completely.

**Comment by mjpost** [comment]
I've played around with this and am unable to fix it. I thought it might have something to do with the fact that the image captioner creates `params` ([line 108](https://github.com/awslabs/sockeye/blob/3280f7b0111b705d2218096121a20f6471f1f4e8/sockeye/image_captioning/captioner.py#L108)) with the code in `sockeye/arguments.py` and then fills the arguments with code from `sockeye/image_captioning/arguments.py`, but merging them didn't fix the problems. It is strange that this shows up only in the image captioner, however.

I [filed a bug report](https://github.com/PyCQA/pylint/issues/2349); maybe they can help us.

**Comment by tdomhan** [comment]
this should fix the issue: https://github.com/awslabs/sockeye/pull/493 (at least it works locally).

**Comment by tdomhan** [comment]
it's basically doing what we do in `train.py`, where we have a separate function taking `args` as an argument.

**Comment by fhieber** [comment]
closing for now. I don't think we will have to come back to this.
