### ISSUE TITLE
Load symbol file in model dictionary for inderence

### ISSUE THREAD

**Issue by xinyu-intel** [awslabs/sockeye#501]
Hi, I found that there are symbol files and param files in model dictionary but only param files will be loaded when inference. Is there any solution to load symbol files directly for inference? Because I want to do some offline graph replacement experiments. Thanks:)

**Comment by fhieber** [comment]
Hi,

the symbol saved to disk at training time is the training computation graph (using teacher forcing on already known target sequences). It is not suitable for inference. At this point there is no single computation graph generated for inference/beam search; we use a combination of modules and imperative logic to implement beam search.

**Comment by fhieber** [comment]
Closing for now. Feel free to reopen if you have more questions regarding this.
