### ISSUE TITLE
where could I get `query_max_length` size? 

### ISSUE THREAD

**Issue by tomsbergmanis** [awslabs/sockeye#503]
Hi, 
I am trying to work out how to obtain alignment matrices from transformer models. I managed to get a satisfying solution when batch size = 1, however, I would like to find a more general solution. For that, I need to do a reshape of this sort: 
`attention_probs = mx.sym.reshape(data=probs, shape=(-4, -1, self.heads, 0, query_max_length))` 
The question I have is: where could I get `query_max_length` size? 
(you can see the code [here](https://github.com/tilde-nlp/sockeye/blob/b6ed3e8a7093e71f9c023c8639fd4a1823b80d36/sockeye/layers.py#L635))
Thank you, 
T.

**Comment by fhieber** [comment]
What is the supposed input shape of `probs` and what is the shape you would like to obtain?

**Comment by tomsbergmanis** [comment]
Thank you, I found what I needed.

**Comment by fhieber** [comment]
Great to hear!
