### ISSUE TITLE
Training on CPU can only utilize 1 physical core when using autopilot

### ISSUE THREAD

**Issue by juliusshufan** [awslabs/sockeye#510]
I am trying to train wmt using the tranformer model via autopilot on a CPU machine. However, I noticed,

1. After the data (pre-)processing completes, and the training session starts, only one CPU core is unitilized.
(I observe this by using htop/top command, and only one core is 100% loaded, even the machine equipped with Xeon processor and 40 physical cores).

2. If the training session is initiated via sockeye.train, after the data (pre-)processing completes, all the CPU cores are utilized and via htop/top command, and the training speed is much faster than which achived via method 1.

3. I also try initializing the training session via the command generated by "call_sockeye_train" functions implemented in autopilot.py, similiar phenomenon and CPU loads observed as which achived via method 2. 

May I know this is the expected result when start a CPU training session via autopilot? 
Thanks.

**Comment by mjdenkowski** [comment]
Hi Shufan,

CPU mode should use all available cores by default.  There are no explicit options in Sockeye to control the number of CPU threads, but MXNet should respect the `OMP_NUM_THREADS` environment variable.  If you're using the recommended version `mxnet-mkl`, it should automatically choose the optimal number of threads.

**Comment by mjdenkowski** [comment]
Hi Shufan,

Autopilot is just calling `sockeye.train` as a subprocesses using the same Python executable from the Autopilot invocation ([code](https://github.com/awslabs/sockeye/blob/master/contrib/autopilot/autopilot.py#L328-L374)).  We haven't observed this issue--the subprocess should inherit the current environment and behave as if it was called directly by the user.

Typically, GPUs are used for training except for small test models.  Are you actively exploring using CPUs for general model training?

**Comment by mjdenkowski** [comment]
Closing for now.  Feel free to reopen if you have more questions.
