### ISSUE TITLE
Using already available source feature vocabularies when training a new model

### ISSUE THREAD

**Issue by franckbrl** [awslabs/sockeye#527]
Hello,

I have a `params` file, as well as vocabulary files, and I want to us them to continue the training on new data (for fine-tuning).

With `sockeye.train`, I can do:

```
--source-vocab vocab.src.0.json
--target-vocab vocab.trg.0.json
```

But I also have a `vocab.src.1.json` that I can't pass as argument, and therefore needs to be recomputed on the data. This is risky, since the vocabulary frequencies can be different given different data, which could lead to different indexes than the ones in my initial `vocab.src.1.json`.

I guess what I'm looking for is something like:

```
--source-vocabs vocab.src.0.json vocab.src.1.json
--target-vocab vocab.trg.0.json
```

I have seen the use of `sockeye.prepare_data` [here](https://github.com/awslabs/sockeye/tree/master/tutorials/adapt), but this module also takes one single source vocabulary file.

Is there a way to do this right?

**Comment by tdomhan** [comment]
You are right, this is currently not supported.

What would be needed to change is to make `source_vocabs` a variable length argument and modifying these two locations:
https://github.com/awslabs/sockeye/blob/master/sockeye/train.py#L304
https://github.com/awslabs/sockeye/blob/master/sockeye/prepare_data.py#L49

**Comment by franckbrl** [comment]
Thank you for your answer!

I could work on it and make a PR, if you want.

**Comment by tdomhan** [comment]
Perfect, thanks a lot!
