### ISSUE TITLE
MIXER implementation

### ISSUE THREAD

**Issue by jsedoc** [awslabs/sockeye#536]
Hi,

I was wondering if anyone had reimplemented [Sequence Level Training with Recurrent Neural Networks](https://arxiv.org/abs/1511.06732) or some form of reinforcement learning in Sockeye?

If not, I'm guessing that the path forward is to augment eye inspired by the reinforcement learning code in the MxNet tutorial. 

Thanks!

**Comment by tdomhan** [comment]
We have an implementation of Minimum Risk Training in a separate branch:
https://github.com/awslabs/sockeye/tree/mrt
It's now about a year old and hasn't been ported to a current version of Sockeye. It might be worth checking out for you though.

**Comment by jsedoc** [comment]
Thanks! This is a great starting point that we will add too.
