### ISSUE TITLE
Memory not being freed after translation

### ISSUE THREAD

**Issue by sukhanovaa** [awslabs/sockeye#539]
Hello!
I'm currently trying to implement a simple server around sockeye.inference.Translator that loads the model, passes it data to translate and returns the result. My main concern is that after calling translation (inference.Translator.translate()) there's additional GPU memory that is consumed in the process but never freed.

When the server is freshly started, my model takes up around 1169 mb of GPU memory. Using batch_size = 4 and the same test file for translation:
after 1st translation call, 4509 mb is used
after 2nd translation call, 4565 mb is used,
after 3rd translation call, 4621 mb is used,
after 4th translation call, 4677 mb is used and does not increase after that. 

Ideally, after a translation round only model parameters should stay in memory, especially since MXNet does not allow to specify a certain constant amount of memory to be used (as far as I learned from the forums).
So, I realized one approach would be to spawn translate() as a separate process (like is done during training when checkpoint decoder is started), but it is a bit tricky since my server uses threads for handling requests already. Is there any other option to free this GPU memory?

**Comment by tdomhan** [comment]
Do you create a new `sockeye.inference.Translator` for every request?

In any case the reason for the increase in memory usage is the use of the bucketing module, which lazily creates computation graphs for different buckets, which in turn depend on the length of the input. While the graphs share memory there is still some overhead for each graph that gets generated.

In order to better understand the issue you're facing: Why is it problematic that the memory grows after the first request, as long as it does not grow infinitely (mainly it will stop growing as soon as all buckets have been seen)?

**Comment by sukhanovaa** [comment]
I do not create `Translator` every time anew, it is only loaded once.
Currently, I found out that the memory usage still grows, and after translating several large files the model used 5233 mb with a humble `batch_size` of 4, although this seems to be its final size. This means that the number of sockeye models my gpu (11gb DDR) can handle is 2 at most, while with e.g. Marian it is more since Marian servers release back all the memory consumed during translation while keeping parameters loaded. If my server handled requests linearly, I could poll several Marian models consecutively since they 'inflate' but then always 'deflate'.
Of course, I could always clean up by just reloading `Translator` after each translation round, but this seems somewhat impractical.

**Comment by tdomhan** [comment]
Generally memory allocation is quite expensive, so for that reason I think mxnet holds on to the memory. In general this is a issue about memory use inside of mxnet, over which we have only limited control in sockeye.

That said, to understand your use case better: would you like to host several distinct models on the same gpu or run several processes serving the same model? For the first we should see if we can bring down inference time memory usage and for the second we could see if we can maybe work with multiple threads.
Also note that any memory which is freed and not part of a computation graph from a bucket will be returned to an internal mxnnet memory pool. This means that the memory won't appear as freed to the OS but can be reused within the same python process.

**Comment by sukhanovaa** [comment]
After some more reading, yes, it seems like MXNet has a lot of issues with memory, which is sad. Memory being only released into the pool is pragmatic when one uses solely MXNet. What if there is one model per server and several servers are running, does each of them have its own pool?

> would you like to host several distinct models on the same gpu
Yes, this actually seems to be the ultimate form of my issue since I also use other frameworks for NMT. In case you refer to inference.Translator._beam_search(), I've looked at the code there and have no immediate ideas about its optimization, but I could try harder.
> or run several processes serving the same model
I believe that this could be a convenient feature, especially nice for production usage, although not the one I'm interested in at the moment.

**Comment by tdomhan** [comment]
> What if there is one model per server and several servers are running, does each of them have its own pool?
There is one pool per python/MXNet process. Currently each Sockeye Translator object holds on to its memory for its lifetime. The BucketingModule that is used internally, in principle allows for memory sharing among the buckets, but not across BucketingModules. If many models should be loaded on the same device, one would need to modify the BucketingModule to support memory sharing across different instantiations of the BucketingModule.
