### ISSUE TITLE
Is there a website for sockeye?

### ISSUE THREAD

**Issue by eric-haibin-lin** [awslabs/sockeye#540]
opennmt has a website to guide ppl through their APIs, pretrained models and tutorials. Does sockeye have that?

**Comment by pengzhao-intel** [comment]
Hope the website online soon and we'd like to contribute to the new models and tutorials for the hardware-specific tips/flow, like INT8 :)

**Comment by mjpost** [comment]
Okay, it's live: [https://awslabs.github.io/sockeye/](https://awslabs.github.io/sockeye/)

**Comment by tdomhan** [comment]
closing.
