### ISSUE TITLE
Warnings with latest pytest

### ISSUE THREAD

**Issue by bricksdont** [awslabs/sockeye#542]
With current master and latest pytest, I get warnings of this kind:

    /Users/mathiasmuller/miniconda2/envs/py36/lib/python3.6/site-packages/_pytest/python.py:198:
    RemovedInPytest4Warning: Fixture "mock_translator" called directly.
    Fixtures are not meant to be called directly, are created automatically when test functions request them as parameters.
    See https://docs.pytest.org/en/latest/fixture.html for more information.

It's a recent addition to pytest, for context:

https://github.com/pytest-dev/pytest/issues/3661

Perhaps the requirements should specify a slightly older version of pytest (I can open a PR for that), or we should add ignore statements in the code (if that is possible in this case, I have no idea)?

Pytest version:

```sh
$ pip freeze | grep pytest
pytest==3.8.1
pytest-cov==2.6.0
```

**Comment by fhieber** [comment]
These style checkers get more and more annoying :)
We are already fixing a version of mypy because of similar issues. Please go ahead with a PR that locks pytest to a certain version.

**Comment by mjdenkowski** [comment]
Do we like fixing the version of pytest versus adding an ignore statement to the code?  Either way, the warning is ignored and we might want positive features of future versions of pytest.

**Comment by fhieber** [comment]
good point. If its easy enough to add an ignore statement, lets prefer that. (In the case of mypy this was pretty hard so we opted for the version fixture.)

**Comment by fhieber** [comment]
For some reason I read this whole issue as related to pylint...
I was able to reproduce the warnings and will take a look.

**Comment by fhieber** [comment]
In #543 I just remove the fixture annotation and everything still passes.

**Comment by tdomhan** [comment]
well I guess the point of fixing to a certain version, at least for Travis, was to avoid the case where a version bump in a dependency could suddenly block our CI pipeline.  For a particular warning in this case it could be fine to add a ignore statement though.

**Comment by bricksdont** [comment]
Fixed by 3e554adc30c0495c5939f94ccdf940c11d9d6421, closing.
