### ISSUE TITLE
Inconsistencies with scoring and inference

### ISSUE THREAD

**Issue by mjpost** [awslabs/sockeye#545]
There are a few inconsistencies related to inference that have come up in evaluating scoring (#538). However, these are corner cases that could arise in other settings, as well. The problem is:

- Length normalization is only applied to completed hypotheses on the beam. However, if the beam hits the maximum sequence length before generating `</s>`, it will still return, with the unnormalized score.
- This is a general problem for scoring: when retrieving a score from the Sockeye inference CLI (via `--output-type translation_with_score`), there is no way to know whether `</s>` was generated and therefore whether length normalization was applied (since `</s>` is stripped before returning to the user).
- Sockeye's scores are therefore underspecified.

This is a problem for evaluating scoring. Scoring takes raw text and will therefore always append </s>, just as is done in training. I am running into this problem because sometimes the outputs haven't actually finished but have just hit the maximum output length and are unnormalized. This could be a problem more generally.

I am not sure of the correct solution, but I propose this:

- In inference, `--maximum-output-length` should refer to the hypothesis *excluding* `</s>`. The reasoning is that this flag is a user-facing feature, and users do not see the `</s>` since it is stripped off.
- Beam search stops at the max output length. If there are unfinished hypotheses, however, the decoder should take one more step and force each the selection of `</s>` for all unfinished hypotheses. It will then apply length normalization, too.
- Length normalization should be computed *including* `</s>`, since it is generated by the decoder.

This way, the user can be guaranteed that every hypothesis actually finished, and that all obtained scores are comparable.

**Comment by bricksdont** [comment]
What was the rationale originally to not apply length normalization for unfinished hypotheses that hit maximum length?

**Comment by fhieber** [comment]
We used to apply length normalization at every time step for all hypotheses, but afaik this was changed when beam pruning was added.

**Comment by mjpost** [comment]
Even without this change to pruning, the user calling `sockeye.translate` wouldn't know whether `</s>` had been generated in a sentence that was returned (and thus, wouldn't know what the value of `N` was in computing the length calculation), because it might just have been a hypothesis that got truncated when it hit the max length. So I think this could all be fixed if we guaranteed that hypotheses returned have had `</s>` generated.

**Comment by fhieber** [comment]
not sure I follow this logic. I think we should return what the model predicted, optionally truncated because of maximum length. Of course we should make sure that the score comes out normalized, but I don't think we should manually force/add a `</s>`.

**Comment by mjpost** [comment]
The issue is that length norm includes end of sentence, but that is stripped off before being returned to the user (as it should be). So the user doesn’t know whether the score of the sentence was normalized by the number of words present (N) or by N+1. 

matt (from my phone)

**Comment by mjpost** [comment]
Is that clear? Another option that would retain normalization consistency is to apply normalization only to user-visible words, i.e., excluding `</s>`. However, this seems a little strange since the score includes the cost of generating `</s>`.

**Comment by fhieber** [comment]
Yes its clear now, thanks!
In that case I think that the approach of forcing truncated hypotheses to end with `</s>` might be the way to go. I need to think about this a little bit though :)

**Comment by tdomhan** [comment]
yeah, that's a good point. So I guess we could always take the probability of `</s>` as the last token for truncated hypothesis. This is effectively anyway what we do: we force the model to stop.

**Comment by fhieber** [comment]
Sockeye 2 addresses this issue, see #719.
