### ISSUE TITLE
Load model once and use to translate multiple queries

### ISSUE THREAD

**Issue by kamalg92** [awslabs/sockeye#548]
How to keep sockeye trained model in memory and reuse it ? I don't want to reload the model in memory for each sentence that I enter through a user interface. Reloading model each time increases response time for each input sentence.

**Comment by mjpost** [comment]
What is your use case? `sockeye.translate` waits to read from STDIN, which is exactly what you want. You could also write a server around that.

**Comment by bricksdont** [comment]
Adding to what @mjpost said already: You could write your own code that loads models (for instance via `inference.load_models`) and creates an `inference.Translator` instance - both can be kept alive as long as needed.

**Comment by fhieber** [comment]
Closing this for now due to inactivity, feel free to reopen if you have more questions.
