### ISSUE TITLE
passing source factors in JSON file triggers error

### ISSUE THREAD

**Issue by edwdh** [awslabs/sockeye#554]
When specifying source factors using the "factors" field in a JSON file, `translate.py` shows an error suggesting source factor files are not provided.

This seems to be triggered by line 147 in `translate.py`:

```
check_condition(translator.num_source_factors == len(inputs),  "Model(s) require %d factors, but %d given (through --input and --input-factors)." % (translator.num_source_factors, len(inputs)))
```

After commenting out this line, the inference is performed properly with lexical constraints and source factors. This might be cause by a lack of official support for JSON file input -- right now, passing a file containing serialized JSON objects works as intended with "--json-input".

**Comment by tdomhan** [comment]
good point. This change only makes sense, when the input is not json.
