### ISSUE TITLE
what's the format of the '--input' when I use "sockeye.image_captioning.extract_features"?

### ISSUE THREAD

**Issue by nwpuhq** [awslabs/sockeye#565]
Following is my commands,and it always says whith a error "extract_features.py: error: argument --input/-i: must exist and be a regular file. "

python -m sockeye.image_captioning.extract_features \
        --image-root /home/hq/IC/ \
        --input training_set.images \
        --output-root /home/hq/IC/feature-cache/ \
        --output training_set.features \
        --device-id 0 \
        --batch-size 128 \
        --source-image-size 3 224 224 \
        --image-encoder-model-path /home/hq/inception-bn/synset.txt \
        --image-encoder-layer stage4_unit3_conv3

HELP ME!Thanks very much!

**Comment by nwpuhq** [comment]
OK,I have already solved it..

**Comment by lorisbaz** [comment]
It is a plain text file containing the filename of the images including relative path. E.g.:
image1.png
image2.png
...

The path is relative to `--image-root /home/hq/IC/`
