### ISSUE TITLE
ModuleNotFoundError: No module named 'contrib'

### ISSUE THREAD

**Issue by pengxin99** [awslabs/sockeye#569]
when i run the code `sockeye-autopilot` , program exit with an error:

> Traceback (most recent call last):
>   File "/home/pengxin/anaconda3/envs/gluonnlp/bin/sockeye-autopilot", line 7, in <module>
>     from contrib.autopilot.autopilot import main
> ModuleNotFoundError: No module named 'contrib'

then i found there is an error import module name in the file "/home/pengxin/anaconda3/envs/gluonnlp/bin/sockeye-autopilot" 
```
import re
import sys

from contrib.autopilot.autopilot import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
we should change the `contrib` import code to this, and and it works. :)
 
`from sockeye_contrib.autopilot.autopilot import main`

---
system : ubuntu 18.04 LTS
python version: 3.6
Mxnet version: 1.3.0
sockeye:  `pip install sockeye`

**Comment by tdomhan** [comment]
I tagged a release (see https://github.com/awslabs/sockeye/releases/tag/1.18.57). This should trigger a pypi release.

**Comment by pengxin99** [comment]
Thanks for your information  : ) @artemsok @tdomhan
