### ISSUE TITLE
Character-level output with RNN decoder

### ISSUE THREAD

**Issue by msemikin** [awslabs/sockeye#570]
Hello, I am trying to replicate the results of the paper [Fully Character-Level Neural Machine Translation
without Explicit Segmentation](https://aclweb.org/anthology/Q17-1026) using Sockeye. I haven't found any information in the documentation on how to specify that the model output is over character vocabulary, not over word vocabulary. I am using a CNN+RNN encoder and RNN decoder. Thank you!

**Comment by bittlingmayer** [comment]
Well there is always the trick of inserting spaces between every characters (perhaps after replacing space with a symbol like underscore).

**Comment by fhieber** [comment]
Thanks for your question @msemikin. Currently, the suggestion by @bittlingmayer would be the easiest and fastest way to build a character-based model with Sockeye. Sockeye reads whitespace-separated data, and each all non-whitespace characters between whitespaces represent a single token. If you want tokens to be characters, insert whitespaces into your data and model word boundaries with another symbol (e.g. underscore).

**Comment by tdomhan** [comment]
That would probably be the best way to do this. Sockeye in general assumes the data has already been preprocessing, e.g. split into tokens. In the case of character models one would just see each character as a token and handle the splitting/merging and word boundaries outside of Sockeye.

**Comment by tdomhan** [comment]
Also note that you can use `--encoder rnn-with-conv-embed` or `--encoder transformer-with-conv-embed` in order to add convolutions + pooling, as described in Lee et al. (2017).

**Comment by bittlingmayer** [comment]
@msemikin Happy I could help.

Did you end up needing to change some parameter to increase the maximum sequence width?

**Comment by tdomhan** [comment]
I would definitely be advisable to increase the maximum length (`max-seq-len`) from 100 to something larger, say 400, as otherwise you will discard a lot of samples during training.

**Comment by bittlingmayer** [comment]
Right, rule of thumb for English is ~5 chars per word.
