### ISSUE TITLE
Test failed: test/integration/test_seq_copy_int.py

### ISSUE THREAD

**Issue by xingniu** [awslabs/sockeye#573]
It failed since commit 5144d25 (Update to MXNet 1.3.0)
```
test/integration/test_seq_copy_int.py::test_seq_copy[--encoder rnn --decoder rnn --num-layers 3:2 --rnn-cell-type lstm --rnn-num-hidden 8 --rnn-residual-connections --num-embed 8 --rnn-attention-type coverage --rnn-attention-num-hidden 8 --weight-tying --rnn-attention-use-prev-word --rnn-context-gating --layer-normalization --batch-size 2 --loss cross-entropy --label-smoothing 0.1 --loss-normalization-type batch --optimized-metric perplexity --max-updates 2 --checkpoint-frequency 2 --optimizer adam --initial-learning-rate 0.01 --rnn-dropout-inputs 0.5:0.1 --rnn-dropout-states 0.5:0.1 --embed-dropout 0.1 --rnn-decoder-hidden-dropout 0.01 --rnn-decoder-state-init avg --rnn-encoder-reverse-input --rnn-dropout-recurrent 0.1:0.0 --rnn-h2h-init orthogonal_stacked --batch-type sentence --decode-and-evaluate 0 --learning-rate-decay-param-reset --weight-normalization --source-factors-num-embed 5---beam-size 2 --beam-search-stop first-False-True-True] FAILED
```
```
...
>               assert all(a == b for a, b in zip(lines, lines_equiv))
E               AssertionError

test/common.py:532: AssertionError
```

**Comment by tdomhan** [comment]
Thanks for reporting! Mhh that is strange. On Travis and locally the tests seem to be running fine, [see](https://travis-ci.org/awslabs/sockeye/builds/451670369?utm_source=github_status&utm_medium=notification). I wonder how we could reproduce this.

**Comment by xingniu** [comment]
Right. I also don't know which information I can provide is useful.
I try to give as much configuration details as possible.

Sockeye is installed via virtualenv and with the following steps:
```
git clone https://github.com/awslabs/sockeye.git
cd sockeye
pip install -e . --no-deps
pip install -r requirements/requirements.gpu-cu90.txt
pip install -r requirements/requirements.dev.txt
```
I use Python3/3.6.4, cuda/9.0.176, cudnn/v7.2.1

The AssertionError came from producing an unexpected `<unk>`.

**Comment by tdomhan** [comment]
Thanks for looking into this! We do use `--use-cpu` during these tests, so they should indeed use the CPU. I will try see if I can reproduce this running on different hardware.

**Comment by xingniu** [comment]
Thanks! BTW, it doesn't mater which type of GPUs are used. It failed on two gtxtitanx cards, or two gtxtitanxp cards, or two gtx1080ti cards, in our cluster.

**Comment by fhieber** [comment]
Closing. Feel free to reopen if this issue surfaces again.
