### ISSUE TITLE
[doc] link lost

### ISSUE THREAD

**Issue by pengzhao-intel** [awslabs/sockeye#574]
https://awslabs.github.io/sockeye/inference.html

> CPU process per core translation
> On multi-core computers, translation per core separately can speedup translation performance, due to some operation can’t be handled parallel in one process. Using this method, translation on each core can be parallel.
> 
> One **python script example** is given and you can run it as follows:
> 
> > python cpu_process_per_core_translation.py -m model -i input_file_name -o output_file_name -bs batch_size -t true
> Options:
> 
> -t true: each core translate the whole input file.
> 
> -t false: each core translate (input file line/core number) lines , then merge the translated file into one complete output file.

The link of example is 404
https://raw.githubusercontent.com/awslabs/sockeye/master/tutorials/process_per_core_translation/cpu_process_per_core_translation.py

**Comment by tdomhan** [comment]
thanks for reporting. The link should indeed be to `https://raw.githubusercontent.com/awslabs/sockeye/master/docs/tutorials/cpu_process_per_core_translation.py`.

**Comment by tdomhan** [comment]
https://github.com/awslabs/sockeye/pull/576

**Comment by pengzhao-intel** [comment]
Thanks for the fix :)
