### ISSUE TITLE
use_mxnet_topk still necessary?

### ISSUE THREAD

**Issue by mjpost** [awslabs/sockeye#585]
Do we know yet whether MXNet has a decent non-GPU version of `topk()`, such that we could get rid of this variable? I can run my own tests but thought I'd ask first.

I'm asking because I have a use case that made a change to a topk argument format, and in the current state, this requires updating four separate implementations (`inference.TopK`, `inference.Top1`, and `utils.topk()` for `use_mxnet_topk` in `{True, False}`).

**Comment by fhieber** [comment]
Good question! According to https://github.com/apache/incubator-mxnet/issues/10205, there was some update to the CPU-version of MXNets topk op with 1.3 and we changed the value of `use_mxnet_top` to `True` by default. So without having any numbers at the top of my head, I'd say its no longer required to have the numpy version of topk lying around. `test_inference.py` uses it to compare outputs between both implementations. Maybe we can move the Numpy topk implementation into `test_inference.py` as a reference implementation to compare to and remove the variable from the function itself.

**Comment by mjpost** [comment]
I wrote a test and ran it on MXNet 1.3.1 (CPU version) and Sockeye 1.18.60. The results show MXNet is now much better:

```bash
for use_mxnet in 0 1; do 
    python3 test_mxnet_topk.py 1000 $use_mxnet
done
use_mxnet_topk=0 278.19987893104553
use_mxnet_topk=1 104.7317283153534
```
The code for posterity:

```python
#!/usr/bin/python3

import argparse
import sockeye
import sockeye.utils
import time

import mxnet as mx
import numpy as np

def test_topk_func(batch_size, beam_size, target_vocab_size, use_mxnet_topk):
    # Random model scores. Shape: (batch_size * beam_size, target_vocab_size)
    scores = mx.nd.random.uniform(0, 1, (batch_size * beam_size, target_vocab_size))
    # offset for batch sizes > 1
    offset = mx.nd.array(np.repeat(np.arange(0, batch_size * beam_size, beam_size), beam_size), dtype='int32')

    np_hyp, np_word, np_values = sockeye.utils.topk(scores, k=beam_size,
                                                    offset=offset, use_mxnet_topk=use_mxnet_topk)

test_settings = [(1, 5, 30000),
                 (1, 10, 30000),
                 (1, 20, 30000),
                 (10, 5, 30000),
                 (32, 5, 30000)
]

parser = argparse.ArgumentParser()
parser.add_argument('times', type=int)
parser.add_argument('use_mxnet', type=int)
args = parser.parse_args()

start = time.time()
for i in range(args.times):
    for test_setting in test_settings:
        test_topk_func(*test_setting, args.use_mxnet)
stop = time.time()
print('use_mxnet_topk={} {}'.format(args.use_mxnet, stop - start))
```
