### ISSUE TITLE
Errors are incomplete ("Differing Arguments" with what?)

### ISSUE THREAD

**Issue by ukamath** [awslabs/sockeye#600]
Shouldn't the error tell you what two arguments are not compatible? I tried to do an apple to apple comparison of sockeye with Pytorch https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb
I get "differing arguments" but don't know what to change? 

python3 -m sockeye.train -s train-small.de -t train-small.en -vs newstest2016.tc.de -vt newstest2016.tc.en --encoder rnn --decoder rnn --rnn-num-hidden 1024 --batch-size 64 --batch-type sentence --rnn-attention-in-upper-layers --rnn-attention-type=dot --num-layers=1:1  -o test4 --use-cpu
/Users/udaykamath/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[ERROR:__main__] Mismatch in arguments for training continuation.
[ERROR:__main__] Differing arguments: batch_size, rnn_num_hidden.

**Comment by ukamath** [comment]
Ok I debugged it and found the answer. It should be different than old similar parameter if the "-o filename" is same. Phew! thanks

**Comment by fhieber** [comment]
I am not sure I understand how your Sockeye error relates to Pytorch or the tensorflow link, but by default `sockeye.train`' tries to resume training if the path given to `-o` already exists (i.e. a previous Sockeye training has been started there). Training resumption only works if the arguments to your 2nd invocation of `sockeye.train` are equal or compatible to the 1st. This is the error you are seeing.
If you want to start training from scratch and save the model to the same output folder, use the `--overwrite-output` flag.
