### ISSUE TITLE
Finetune Model

### ISSUE THREAD

**Issue by Cartus** [awslabs/sockeye#614]
Hi. Thanks for sharing this great framework.

May I ask if Sockeye supports finetune the pretrained model? Here is my situation. I want to first pretrain a model based on a larger corpus. Then save the model and finetune it by using another smaller dataset. I couldn't find a proper way to do this. 

Thank you!

**Comment by fhieber** [comment]
Hi @Cartus,
thanks for asking. This is easily done with the `--params` argument for `sockeye.train`:
First train the baseline model on your large corpus:
```
python -m sockeye.train -s <largeSource> -t <largeTarget> [...] -o <baselineModel>
```
Then use its parameters on a second training run:
```
python -m sockeye.train -s <smallSource> -t <smallTarget> [...] --params <baselineModel>/params.best -o <finetunedModel>
```
This is also described in the Domain Adaptation tutorial: https://awslabs.github.io/sockeye/tutorials/adapt.html

**Comment by Cartus** [comment]
Hi @fhieber ,

Thank you so much for the prompt reply!

**Comment by fhieber** [comment]
You can see the names of the model parameters in the log file from training. They look like this:
```
[INFO:sockeye.training] Model parameters: decoder_rnn_att_e2h_weight: (32, 64), decoder_rnn_att_h2s_weight: (1, 32), decoder_rnn_att_q2h_weight: (32, 64), decoder_rnn_enc2decinit_0_bias: (64,), decoder_rnn_enc2decinit_0_weight: (64, 64), decoder_rnn_enc2decinit_1_bias: (64,), decoder_rnn_enc2decinit_1_weight: (64, 64), decoder_rnn_hidden_bias: (64,), decoder_rnn_hidden_weight: (64, 128), decoder_rnn_l0_h2h_bias: (256,), decoder_rnn_l0_h2h_weight: (256, 64), decoder_rnn_l0_i2h_bias: (256,), decoder_rnn_l0_i2h_weight: (256, 96), encoder_birnn_forward_l0_h2h_bias: (128,), encoder_birnn_forward_l0_h2h_weight: (128, 32), encoder_birnn_forward_l0_i2h_bias: (128,), encoder_birnn_forward_l0_i2h_weight: (128, 32), encoder_birnn_reverse_l0_h2h_bias: (128,), encoder_birnn_reverse_l0_h2h_weight: (128, 32), encoder_birnn_reverse_l0_i2h_bias: (128,), encoder_birnn_reverse_l0_i2h_weight: (128, 32), source_embed_weight: (15, 32), target_embed_weight: (15, 32), target_output_bias: (15,), target_output_weight: (15, 64), target_output_wn_scale: (15, 1)
[INFO:sockeye.training] Total # of parameters: 81022
```

**Comment by davvil** [comment]
You can use the option `--dry-run` and sockeye will print all the initial statistics but will not perform any operation.

**Comment by ykl7** [comment]
@fhieber I'm trying to do something similar. I extracted the parameter names I want to freeze using ```--dry-run```. I'm unsure of the format of the command. Should it be ```python -m sockeye.train -s <smallSource> -t <smallTarget> [...] --params <baselineModel>/params.best --fixed-param-names [param1 [param2 [param3] ] ] -o <finetunedModel>```?

**Comment by fhieber** [comment]
@ykl7 Yes, that seems right. The list of `fixed-param-names` should just be space-separated, i.e. `--fixed-param-names source_embed_weight encoder_layerX_bias` etc.
