### ISSUE TITLE
Decoder length at inference/training

### ISSUE THREAD

**Issue by lambdaofgod** [awslabs/sockeye#616]
Is there a way to restrict decoder output length? I use `--max-seq-len source_length:target_length` parameter when training.
Still when I run sockeye.translate I get output longer than `target_length`. Is this also the case when calculating validation metrics?

If it's the case that maximum target length isn't enforced at inference time, then it would be problematic for ROUGE, because adding more words can only improve, and never deteriorate ROUGE.

**Comment by fhieber** [comment]
Hi @lambdaofgod, thanks for the question.

Sockeye stores the average length ratio between source and target during training in the model folder. At inference time, we allow use this average length ratio (plus 2 standard deviations from it by default) as a factor to compute the maximum output length. That is, the maximum number of beam search iterations allowed. If the model ends all hypotheses in beam search before reaching that maximum output length, search is stopped before of course.

You can control that heuristic to some extent with the `--max-output-length-num-stds` parameter: set it to 0, and the output length constraint will be a bit more strict.
However, there is also an option to `load_models()` to [force a certain maximum output length](https://github.com/awslabs/sockeye/blob/master/sockeye/inference.py#L375), independent of the source. This is currently not exposed to the CLI, but we could add it if needed.

During training, validation metrics are computed as follows:
- token-level metrics such as perplexity/cross-entropy are computed on the teacher forced target sequence
- sequence-level metrics such as ROUGE or BLEU are computed by the CheckpointDecoder which runs at every checkpoint and corresponds to the sockeye.translate CLI. As such it uses the default behavior described above:
```
max_output_length=int(ceil(factor * input_length))
```
where `factor` is 
```
factor = length_ratio_mean + (length_ratio_std * num_stds)
```
