### ISSUE TITLE
serve sockeye using mxnet-model-server

### ISSUE THREAD

**Issue by boliangz** [awslabs/sockeye#618]
Hello!

mxnet-model-server seems to be a neat way to serve MXNET model. Does sockeye have a plan to add a serving function using mxnet-model-server? 

Besides the mxnet model parameter file and the symbol.json, mxnet-model-server requires a customized data preprocessing and postprocessing pipeline, if I want to write the code myself, is it feasible to do it with sockeye? Would you have some suggestions for that?

**Comment by fhieber** [comment]
I am not familiar with the mxnet-model-server, but if it only works with exported symbols and parameters than its unlikely to be easy to use with Sockeye. Sockeye's inference logic is not implemented in the symbol itself, so you would have to port sockeye/inference.py to the model server somehow.

There was a similar issue recently: https://github.com/awslabs/sockeye/issues/615

**Comment by jamesewoo** [comment]
It's definitely feasible. Your custom handler would define how to configure and initialize Sockeye with a model. Loading the model and running inference can be delegated to Sockeye. Pre and post processing would depend on your input language and encoding.

**Comment by boliangz** [comment]
thanks! @fhieber and @jamesewoo 

I basically split the model load and translate sections in translate.py. I put model load part into mxnet-model-server init function and translate part into inference function. After adding some preprocessing and post-processing scripts, I managed to run sockeye in mxnet-model-server.

To maximize GPU usage, what are the best options to choose for sockeye inference?

**Comment by jamesewoo** [comment]
If you have more than one GPU you can scale up the number of workers or change the batch size for requests using the model server's management API. You should pass the gpu_id property from the MMS context to Sockeye during initialization.

**Comment by fhieber** [comment]
Great to hear that this works, thanks @jamesewoo!

**Comment by jamesewoo** [comment]
Take a look at the repo I've been working on: https://github.com/jamesewoo/sockeye-serving. It shows an example of how to serve Sockeye with MMS.

**Comment by ddavydenko** [comment]
This is quite awesome! @jamesewoo , would you consider submitting your work as an example to mxnet-model-server repo?

**Comment by jamesewoo** [comment]
@ddavydenko Certainly!

**Comment by ddavydenko** [comment]
Thanks a lot, @jamesewoo. If you don't mind could you please package this up as example and submit as PR against our (MMS repo)[https://github.com/awslabs/mxnet-model-server]?

**Comment by ddavydenko** [comment]
ah, NVM, just noticed you already submitted https://github.com/awslabs/mxnet-model-server/pull/736. Awesome work, much appreciated!

**Comment by lupesko** [comment]
@jamesewoo what about blogging about it in the MXNet blog? Would love to collaborate on that!

**Comment by jairsan** [comment]
Thanks a lot @jamesewoo, I have played with the code and it works like a charm.

**Comment by jamesewoo** [comment]
@lupesko Sounds interesting, let me know how I can help.

**Comment by lupesko** [comment]
@jamesewoo message me on my github alias name at gmail - we can continue the conversation there.

**Comment by fhieber** [comment]
This is issue was great to share knowledge and experience regarding the topic. I am closing this for now, but if more discussion on this is needed, feel free to reopen.
