### ISSUE TITLE
How to disable attention?

### ISSUE THREAD

**Issue by hanayashiki** [awslabs/sockeye#619]
I do not want to use attention for my RNN. Is there any function to disable that? Thank you.

**Comment by hanayashiki** [comment]
Well, I read through the code, and it seems this option is not provided, so I edit a few lines and now attention mechanism can be optional.

**Comment by tdomhan** [comment]
I feel like `--rnn-attention-type fixed` is what you're looking for. This feeds the last encoder state as the context vector into the decoder. Is that what you're looking for?

**Comment by hanayashiki** [comment]
> I feel like `--rnn-attention-type fixed` is what you're looking for. This feeds the last encoder state as the context vector into the decoder. Is that what you're looking for?

That is what I want, thank you! Is there any more extensive documentation for the parameters? Sometimes I do not understand them.

**Comment by tdomhan** [comment]
That was definitely not very self-explanatory. For other arguments we tried to provide descriptions directly on the arguments. Then there's also https://awslabs.github.io/sockeye/. However we do not go into great detail regarding all the parameters we have. Do feel free to open more github issues for clarifying questions though.
