### ISSUE TITLE
num_unks and vocabulary types

### ISSUE THREAD

**Issue by lambdaofgod** [awslabs/sockeye#625]
What is the relation `num_unks` parameter and number vocabulary types? 
Intuitively it seems like they should be related (since unknown words are out of vocabulary), but these two numbers seem to not be even the same order of magnitude.

My preprocessing (I took 50k as vocabulary size) `sockeye.prepare_data` code outputs

```
414755/414755/50000/50004
```
Whereas
```
num_unks_source=1657, num_unks_target=1
```

**Comment by fhieber** [comment]
Hi @lambdaofgod,
I am not sure I understand

**Comment by tdomhan** [comment]
`num_unks_source ` are the number of UNKs occurrences in the source.  

For the vocabulary types we have: initial/min_pruned/max_pruned/+special.

Initial: The number of vocabulary entries before pruning with a minimum count.
min_pruned: The vocabulary size after pruning.
max_pruned: The vocabulary size after constraining to the maximum vocabulary size specified on the CLI (apparently you set this to 50,000. The default is to turn this off, which would be recommended when using any kind of sub-word units).
+special: The size after adding special symbols (e.g. beginning of sentence etc). In total 4 special symbols were added to your vocab.

As for the connection: Your vocabulary was cut down from 400k to 50,000. Therefore I'd expect a lot of UNK occurrences. 1657 seems quite low. So something doesn't add up.
What's your output for "Vocabulary coverage"?

Does that help?

**Comment by fhieber** [comment]
Closing for now, feel free to reopen if you have more questions on the topic.
