### ISSUE TITLE
Checkpoints for trained models

### ISSUE THREAD

**Issue by sundeepteki** [awslabs/sockeye#632]
Hi,
Does Sockeye provide trained models with BLEU benchmarks on WMT for any of the following language pairs: EN to DE/FR/IT/ES and vice-versa?

Thanks,
Sundeep

**Comment by tdomhan** [comment]
At this point we do not offer trained WMT models. We have an example of how to train a WMT model here:
https://awslabs.github.io/sockeye/tutorials/wmt.html
