### ISSUE TITLE
Can't train without --use-cpu

### ISSUE THREAD

**Issue by aijanai** [awslabs/sockeye#633]
Hi, when launching my training on a GPU, I get:
```
[ERROR:sockeye.train] Mismatch in arguments for training continuation.
[ERROR:sockeye.train] Differing arguments: use_cpu.
```

The command is
```
python3 -m sockeye.train \
  --batch-size 80 \
  --batch-type sentence \
  --checkpoint-frequency 30000 \
  --decode-and-evaluate 100 \
  --decoder rnn \
  --embed-dropout 0.2 \
  --encoder rnn \
  --initial-learning-rate 0.0001 \
  --keep-last-params 4 \
  --learning-rate-reduce-factor 0.7 \
  --learning-rate-reduce-num-not-improved 2 \
  --max-num-checkpoint-not-improved 4 \
  --max-seq-len 100 \
  --num-embed 512:512 \
  --num-layers 8:8 \
  --optimized-metric bleu \
  --optimizer adam \
  --rnn-attention-in-upper-layers \
  --rnn-attention-type bilinear \
  --rnn-decoder-hidden-dropout 0.2 \
  --rnn-num-hidden 1024 \
  --use-cpu \
  --weight-init xavier \
  --weight-init-scale 3.0 \
  --weight-init-xavier-factor-type avg \
  -d train_data \
  -o sockeye-commit-suggester \
  -vs test.3000.bpe.diff \
  -vt test.3000.bpe.msg
```

What am I doing wrong?
Many thanks to everybody

**Comment by tdomhan** [comment]
Do you have a partially trained model in `sockeye-commit-suggester`? Unless training continuation is what you want to do I'd suggest deleting `sockeye-commit-suggester` and then trying again.

As for training continuation: We have a list of parameters which we allow to differ between runs. Intuitively the `--use-cpu` should maybe be part of that. However, we need to have some level of caution as the MXNet optimizer state are for example tied to a specific context.

**Comment by aijanai** [comment]
Reading the code at https://github.com/awslabs/sockeye/blob/master/sockeye/train.py, it looks like it happens only when resuming a training.
Perhaps a better informative message about a leftover training dir?

**Comment by tdomhan** [comment]
When you run Sockeye multiple times with the same arguments then it will try to resume training. Do you think a message that just prints something like:
```
Trying to resume training from existing directory %s.
```
would make this clearer?

**Comment by fhieber** [comment]
This already exists:
```
[INFO:sockeye.training] Found partial training in <X>. Resuming from saved state.
```

**Comment by tdomhan** [comment]
True. Maybe we could additionally extend the `Mismatch in arguments for training continuation.` message though to tell the user that the existing directory should be deleted if training continuation is not intended.
