### ISSUE TITLE
Wrong scores from sockeye.translate in test cases

### ISSUE THREAD

**Issue by mjpost** [awslabs/sockeye#639]
I have encountered an issue when trying to debug [the new scorer](https://github.com/awslabs/sockeye/pull/593). Tests seem to randomly fail when the scorer is used to evaluate translator output. I think this may relate to #545.

I've attached a model generated by the integration tests ([example.zip](https://github.com/awslabs/sockeye/files/2842146/example.zip)). If you unpack it, and then run

    echo '{"text": "4 0 6 2 9 0 4"}' | PYTHONPATH=$(pwd) python3 -m sockeye.translate -m model --beam-size 3 --output-type translation_with_score --length-penalty-alpha 1 --use-cpu --batch-size 1 --json-input

You get this output:

    2.249	5 6 2 5 5 5 6 5

Now, if you run again, with that same output as a constraint:

    echo '{"text": "4 0 6 2 9 0 4", "constraints": ["<s> 5 6 2 5 5 5 6 5 </s>"]}' | PYTHONPATH=$(pwd) python3 -m sockeye.translate -m model --beam-size 3 --output-type translation_with_score --length-penalty-alpha 1 --use-cpu --batch-size 1 --json-input

You get a different output:

    2.262	5 6 2 5 5 5 6 5

**Note** that this different output (with a score of 2.262) is the same you get from scoring. So scoring and forced decoding produce the same result, and unconstrained decoding produces a different one.

I am investigating, but my guess is that the `</s>` character is not being generated in the first output.

**Comment by mjpost** [comment]
My hypothesis was correct: in this simple test case, the unconstrained system produces `C.PAD_ID` without ever producing `</s>`. Here is a trace. At each timestep, this produces:

- the accumulated score
- whether each hypothesis is finished
- the hyp IDS
- the word IDS

both before (a) and after (b) normalization. You can see in step 9a that the third hypothesis selects 0 and then normalizes, without ever having generated `</s>`.

```
STEP 1a ACCUM [2.0751374, 2.1165216, 2.3479793] FINISHED [0 0 0] HYPS [0 0 0] WORDS [10  3  4]
STEP 1b ACCUM [2.0751374, inf, 2.3479793] FINISHED [0 1 0] HYPS [0 0 0] WORDS [10  3  4]
STEP 2a ACCUM [4.0901737, 4.245805, 4.3240795] FINISHED [0 0 0] HYPS [0 0 2] WORDS [11  3 10]
STEP 2b ACCUM [4.0901737, 4.245805, 4.3240795] FINISHED [0 1 0] HYPS [0 0 2] WORDS [11  3 10]
STEP 3a ACCUM [4.245805, 6.1991305, 6.2728653] FINISHED [1 0 0] HYPS [1 0 0] WORDS [ 0 10  4]
STEP 3b ACCUM [4.245805, 6.1991305, 6.2728653] FINISHED [1 0 0] HYPS [1 0 0] WORDS [ 0 10  4]
STEP 4a ACCUM [4.245805, 7.936099, 8.1894655] FINISHED [1 0 0] HYPS [0 2 1] WORDS [ 0 10  0]
STEP 4b ACCUM [4.245805, 7.936099, 2.729822] FINISHED [1 0 1] HYPS [0 2 1] WORDS [ 0 10  0]
STEP 5a ACCUM [2.729822, 4.245805, 9.972357] FINISHED [1 1 0] HYPS [2 0 1] WORDS [ 0  0 10]
STEP 5b ACCUM [2.729822, 4.245805, 9.972357] FINISHED [1 1 0] HYPS [2 0 1] WORDS [ 0  0 10]
STEP 6a ACCUM [2.729822, 4.245805, 12.064625] FINISHED [1 1 0] HYPS [0 1 2] WORDS [ 0  0 10]
STEP 6b ACCUM [2.729822, 4.245805, 12.064625] FINISHED [1 1 0] HYPS [0 1 2] WORDS [ 0  0 10]
STEP 7a ACCUM [2.729822, 4.245805, 13.989123] FINISHED [1 1 0] HYPS [0 1 2] WORDS [ 0  0 11]
STEP 7b ACCUM [2.729822, 4.245805, 13.989123] FINISHED [1 1 0] HYPS [0 1 2] WORDS [ 0  0 11]
STEP 8a ACCUM [2.729822, 4.245805, 15.929425] FINISHED [1 1 0] HYPS [0 1 2] WORDS [ 0  0 10]
STEP 8b ACCUM [2.729822, 4.245805, 15.929425] FINISHED [1 1 0] HYPS [0 1 2] WORDS [ 0  0 10]
STEP 9a ACCUM [2.729822, 4.245805, 17.995995] FINISHED [1 1 0] HYPS [0 1 2] WORDS [0 0 0]
STEP 9b ACCUM [2.729822, 4.245805, 2.2494993] FINISHED [1 1 1] HYPS [0 1 2] WORDS [0 0 0]
BEST 0 [0]
2.249	5 6 2 5 5 5 6 5
```

This is a problem for scoring against translation output, because scoring always scores `</s>`. Pursuant to the discussion in #545, it seems that inference should do the same.

As a temporary workaround for the scoring branch, I'll take the translation outputs, force decode them (so as to get `</s>` included in the score), and check `sockeye.score` against those numbers.

**Comment by fhieber** [comment]
Yeah, we've also talked about something related to this: depending on the batch-size you also might get different results because we break out of beam search earlier in batch-size 1 situations than in batch-size > 1 cases (where longer sentences in the batch can cause beam search to run for more iterations). In the latter case the shorter sentence is properly ended with `</s>`, but in the former case not. Our beam search logic on finished hypotheses (newly finished, somehow finished, finished but not normalized, finished but not sorted etc) has become way too complicated. This is something we will have to address at some point, probably by making sure again that all hypotheses are normalized at all times.

**Comment by mjpost** [comment]
I agree the logic is becoming unwieldy. Always normalizing could help. Constraints are responsible for a lot of the complexity; maybe we should branch on that instead of trying to have a single general solution.

**Comment by tdomhan** [comment]
For the problem with scoring and batching this would be solved by making sure by making sure that the final token always is `</s>` in beam search in the maximum iteration, right?

**Comment by mjpost** [comment]
I think it would, yes.

**Comment by bricksdont** [comment]
Could this issue be related to the following: attention weight matrix output (https://github.com/awslabs/sockeye/blob/master/sockeye/output_handler.py#L230) does not output valid probability distributions:

```
4 ||| system Organ Class </s> ||| 1.107796 ||| Kl@@ assen@@ hier@@ ar@@ ch@@ ie ||| 6 ||| 4
0.250257 0.085057 0.068153 0.022506
0.390398 0.122760 0.126535 0.135602
0.097477 0.170234 0.149181 0.042531
0.058781 0.013876 0.028575 0.016816
0.004925 0.000685 0.001663 0.011022
0.011384 0.011746 0.009078 0.019487
```
Vertically, weights do not sum to 1 because attention on `</s>` in the source sentence is not included.

**Comment by mjpost** [comment]
I think you mean to tag #639. I think these issues are independent—this deals with target sequences, and #639 with attentions over source sequences.

**Comment by bricksdont** [comment]
Yes, it should have been #637 - sorry, I should have read more carefully!

**Comment by tdomhan** [comment]
yeah, I think these are two different issues. Once we just truncate the attention matrix too much, but the scores + translations should be correct (#637) and for the other issue we do not terminate the target sentence with a `</s>` when running into the maximum sentence length.

**Comment by fhieber** [comment]
Sockeye 2 addresses this issue, see #719.

**Comment by tdomhan** [comment]
Shouldn't we leave this open until we release Sockeye 2? ;)
