### ISSUE TITLE
skip_blank has different values during data preparation

### ISSUE THREAD

**Issue by franckbrl** [awslabs/sockeye#649]
I'm running a standard training with parallel sentences containing empty source or target lines and  `data_io.py` returns an error while building buckets:

```
IndexError: index 897268 is out of bounds for axis 0 with size 897268
```
The `parallel_iter()` function in `data_io.py` is always called with the `skip_blank` argument set as `True`, except [right here](https://github.com/awslabs/sockeye/blob/master/sockeye/data_io.py#L475). This line makes us keep the sentence pairs containing "blanks", which seems to bring the mismatch reflected in the error above. I don't get the error anymore when I set `skip_blank` to `True` (or when I remove the sentence pairs containing blanks in the data).

@mjpost This line came with [this PR](https://github.com/awslabs/sockeye/commit/02ff337e3370b351b5e2d0c19bbe80a9df8445ec#diff-6f5897a736e94787b26bb894b706251cR475). Would it be an issue to let the default `skip_blank` value here ?

**Comment by mjpost** [comment]
Yeah, [this line](https://github.com/awslabs/sockeye/blob/86b8175e304a02b1c4cac4012a5776b686470478/sockeye/data_io.py#L475) seems like a bug. It should be

```python
        for sentno, (sources, target) in enumerate(parallel_iter(source_iterables, target_iterable, skip_blanks=self.skip_blanks), 1):
```

**Comment by mjpost** [comment]
Amazon folks, I can put in a PR with a test case that exercises this, but not until tonight at least.

And @franckbrl, in the long tradition of blaming the user for design problems—why aren't you cleaning your training data?!

**Comment by franckbrl** [comment]
:laughing: Fair enough!

**Comment by mjpost** [comment]
I should also have written, thanks for tracking this down and filing a perfect bug report. It seems you covered a real hole in my use cases :)

**Comment by franckbrl** [comment]
Always a pleasure!

**Comment by tdomhan** [comment]
Thanks for reporting! This indeed doesn't seem right.
