### ISSUE TITLE
Question: a single bias for all Transformer's layers?

### ISSUE THREAD

**Issue by SamuelLarkin** [awslabs/sockeye#653]
Question for my understanding.
Sorry, I'm not sure what is the official mechanism to ask a question about sockeye.

Looking at, https://github.com/awslabs/sockeye/blob/master/sockeye/encoder.py#L1029, we see the definition of the method `TransformerEncoder.encode()`.  Why are we reusing the same bias for all layers.  Shouldn't we use a different bias per layer?  May be I read the code wrong.

**Comment by fhieber** [comment]
Hi @SamuelLarkin, thanks for your question.

'bias' is probably a slightly misleading name. It represents the **mask** we use to mask out invalid sequence positions in the self attention layers for the batch of variable-length sequences.
For example, if you have a sequence length of 4 and a batch size of 3, the mask/bias might look like this:
```
1 1 1 0
1 1 0 0
1 1 1 1
```
This mask is the same for all layers in the encoder.

**Comment by fhieber** [comment]
Closing for now. Feel free to reopen if you have more questions.
