### ISSUE TITLE
ModelConfig getting cluttered with parameters

### ISSUE THREAD

**Issue by fhieber** [awslabs/sockeye#66]
With more and more flags being added to training, the ModelConfig object gets cluttered with parameters (and their default settings) that are often not even used as their are conditional parameters.
It would be much better to have hierarchical configs that are put together in a composite configuration. We could split configurations into
- encoder
- decoder
- attention
configurations, each of one being an individual configuration object.

Configuration objects should support JSON serialization, ideally also for nested configurations.

We might not be able to continue to use a NamedTuple for a config object as it may contain another config object as a member and this can be easily serialized.

Lets discuss if we should come up with our own ConfigObject implementation or use some existing library.

**Comment by fhieber** [comment]
How about we create a simple class like this, which would already support most of our use cases:

```python3
import jsonpickle
jsonpickle.set_encoder_options('json', sort_keys=True, indent=4)


class Config:
    _frozen = False

    def __init__(self, **kwargs):

        self.__dict__.update(kwargs)

    def __setattr__(self, key, value):
        if self._frozen:
            raise TypeError("Cannot set '%s' in frozen Config" % key)
        object.__setattr__(self, key, value)

    def freeze(self):
        self._frozen = True

    def __repr__(self):
        return "Config: %s" % str(self.__dict__)

    def save(self, fname):
        with open(fname, 'w') as fout:
            fout.write(jsonpickle.encode(self))

    @staticmethod
    def load(fname: str):
        with open(fname) as fin:
            return jsonpickle.decode(fin.read())


# main config with a couple of params
config = Config(num_hidden=4, rnn=True)
# set values afterwards if not frozen
config.filters = [1, 2, 3]
# nested config
config.encoder = Config(max_seq_len=100)

print(config)

config.save("config")
config2 = Config.load("config")

print(config2.encoder.max_seq_len)

config2.freeze()
# throws
config2.decoder = None
```

which returns this:
```
Config: {'num_hidden': 4, 'rnn': True, 'filters': [1, 2, 3], 'encoder': Config: {'max_seq_len': 100}}
100
Traceback (most recent call last):
  File "/Users/fhieber/workspace/nmt/src/sockeye-github/sockeye/config.py", line 65, in <module>
    config2.decoder = None
  File "/Users/fhieber/workspace/nmt/src/sockeye-github/sockeye/config.py", line 29, in __setattr__
    raise TypeError("Cannot set '%s' in frozen Config" % key)
TypeError: Cannot set 'decoder' in frozen Config
```

This would allow us to have a main configuration with nested configs for core parts of the models (encoder, decoder, attention). Factory functions for these classes (get_encoder, get_decoder_ get_attention, get_coverage etc.) could just take the respective config object to create an instance. This would reduce the amount of arguments we need to pass around.

**Comment by fhieber** [comment]
@davvil @tdomhan @mjdenkowski

**Comment by davvil** [comment]
Looks good to me, except for the frozen mechanism.

I assume you made _frozen a class var in order to freeze the config and all its nested configs, but freeze actually sets an object specific var, it doesn't affect the nested ones. You can test it e.g. by setting `config2.encoder.max_seq_len = 10` after freezing, it will happily set the new value. We can set the class variable as `Config._frozen = True`. But this will also freeze independent configs, not elegant and may be problematic in the future. Or we can make _frozen a normal attribute and freeze recursively:

```
    def freeze(self):
        self._frozen = True
        for v in self.__dict__.values():
            if isinstance(v, Config):
                v.freeze()
```

**Comment by davvil** [comment]
Minor: I would raise an AttributeError instead of TypeError: "Raised when an attribute reference (see Attribute references) or assignment fails." https://docs.python.org/3/library/exceptions.html#concrete-exceptions

**Comment by fhieber** [comment]
Yes agreed, frozen recursively would make sense. The problem is that if _frozen is not a class variable, it doesn't seem to be accessible in __setattr__. I will leave it out for now.

**Comment by fhieber** [comment]
Actually I figured it out by using this:
```python
class Config:
    """
    Configuration object that supports freezing of members and JSON (de-)serialization.
    """

    def __init__(self, **kwargs) -> None:
        self.__dict__.update(kwargs)
        self._frozen = False

    def __setattr__(self, key, value):
        if hasattr(self, '_frozen') and self._frozen:
            raise AttributeError("Cannot set '%s' in frozen config" % key)
        object.__setattr__(self, key, value)

    def freeze(self):
        """
        Freezes this Config object, disallowing modification or addition of any parameters.
        """
        self._frozen = True
        for v in self.__dict__.values():
            if isinstance(v, Config):
                v.freeze()
```

**Comment by fhieber** [comment]
A PR that showcases this: #69

**Comment by fhieber** [comment]
PR #72
