### ISSUE TITLE
Training Throughput in Multi-GPU Training

### ISSUE THREAD

**Issue by ArmageddonKnight** [awslabs/sockeye#667]
Hi,

Thanks for developing this very nice NMT toolkit. I have a question about the training throughput reported in the context of multi-GPU training. When we are using multi-GPU, is the throughput number shown by `mxnet.callback.Speedometer` showing the overall throughput across all the devices? 

Thank you.

**Comment by fhieber** [comment]
Yes it's the overall speed. For multi-GPU training gradients are computed for separate subsets of the batch on separate GPUs and then communicated to the master GPU for a synchronous update.
