### ISSUE TITLE
Unimplemented device on flask

### ISSUE THREAD

**Issue by ktoetotam** [awslabs/sockeye#671]
I am trying to run sockeye from Flask. 
`app = Flask(__name__)

@app.route('/api/predict', methods=['POST'])
def predict():

    X = request.get_json()
    text = X['text']
    translations = tr.translate_with_gt(text)
    text = " ".join(translations)
    return jsonify([{'text':  " ".join(tr.translate_with_gt(text))}])

context = mx.cpu()
tr = Translator(context)
print(str(context), file=sys.stderr)

if __name__ == '__main__':
    with app.app_context():
        app.run(host=HOST,
                debug=True,  # automatic reloading enabled
                port=PORT)`

where Translator is:

`class Translator():

    def __init__(self):
        self.params = arguments.ConfigArgumentParser(description='Translate CLI')
        arguments.add_translate_cli_args(self.params)
        self.args = self.params.parse_args(["--models", "sockeyepack/model",
                                  "--beam-size", "10",
                                  "--beam-prune", "10",
                                  "--use-cpu",
                                  "--json-input",
                                  "--input", "hi",
                                  "--output", "test_rest.txt"])
        self.translator, self.output_handler = run_translate(self.args)`

The first request is always ok but on the second request, sockeye throws an exception:

``

> > backend-app | [INFO:sockeyepack.sockeye.translate] Translating...
> backend-app | [INFO:sockeyepack.sockeye.translate] Processed 1 lines in 1 batches. Total time: 0.8835, sec/sent: 0.8835, sent/sec: 1.1318
> backend-app | [INFO:werkzeug] 172.21.0.3 - - [27/Mar/2019 16:09:16] "POST /api/predict HTTP/1.1" 200 -
> backend-app | ['{"text":"test te"}']
> backend-app | [INFO:sockeyepack.sockeye.translate] Translating...
> backend-app | /usr/local/lib/python3.6/dist-packages/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
> backend-app |   BrokenFilesystemWarning,
> backend-app | [INFO:werkzeug] 172.21.0.3 - - [27/Mar/2019 16:09:20] "POST /api/predict HTTP/1.1" 500 -
> backend-app | Traceback (most recent call last):
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
> backend-app |     return self.wsgi_app(environ, start_response)
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
> backend-app |     response = self.handle_exception(e)
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
> backend-app |     reraise(exc_type, exc_value, tb)
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
> backend-app |     raise value
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
> backend-app |     response = self.full_dispatch_request()
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
> backend-app |     rv = self.handle_user_exception(e)
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
> backend-app |     reraise(exc_type, exc_value, tb)
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
> backend-app |     raise value
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
> backend-app |     rv = self.dispatch_request()
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
> backend-app |     return self.view_functions[rule.endpoint](**req.view_args)
> backend-app |   File "/app/app.py", line 18, in predict
> backend-app |     translations = tr.translate_with_gt(text)
> backend-app |   File "/app/sockeyepack/sockeye/translate.py", line 306, in translate_with_gt
> backend-app |     input_is_json=self.args.json_input)
> backend-app |   File "/app/sockeyepack/sockeye/translate.py", line 207, in read_and_translate
> backend-app |     chunk_time, translation = translate(output_handler,  c, translator)
> backend-app |   File "/app/sockeyepack/sockeye/translate.py", line 234, in translate
> backend-app |     trans_outputs = translator.translate(trans_inputs)
> backend-app |   File "/app/sockeyepack/sockeye/inference.py", line 1450, in translate
> backend-app |     batch_translations = self._translate_nd(*self._get_inference_input(translator_inputs))
> backend-app |   File "/app/sockeyepack/sockeye/inference.py", line 1594, in _translate_nd
> backend-app |     max_output_lengths))
> backend-app |   File "/app/sockeyepack/sockeye/inference.py", line 1908, in _beam_search
> backend-app |     if finished.sum().asscalar() == self.batch_size * self.beam_size:  # all finished
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/mxnet/ndarray/ndarray.py", line 1990, in asscalar
> backend-app |     return self.asnumpy()[0]
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/mxnet/ndarray/ndarray.py", line 1972, in asnumpy
> backend-app |     ctypes.c_size_t(data.size)))
> backend-app |   File "/usr/local/lib/python3.6/dist-packages/mxnet/base.py", line 251, in check_call
> backend-app |     raise MXNetError(py_str(_LIB.MXGetLastError()))
> backend-app | mxnet.base.MXNetError: [16:09:20] src/storage/storage.cc:141: Unimplemented device 0
>

**Comment by ktoetotam** [comment]
The problem was in the multithreading and the solutions is to set the flask not to use multiple threads:

```
if __name__ == '__main__':
    with app.app_context():

        global context
        context = mx.cpu()
        global tr
        tr = Translator(context)
        app.run(host=HOST,
                threaded=False,
                debug=True,  # automatic reloading enabled
                port=PORT)
```

**Comment by tdomhan** [comment]
thanks for posting the solution after you found it! This will help others running into similar issues.
