### ISSUE TITLE
tokens/batch in `describe_data_and_buckets` seems to only report target tokens statistics without source tokens statistics

### ISSUE THREAD

**Issue by bikestra** [awslabs/sockeye#676]
Currently, we log statistics about buckets as follows:

```
[2019-03-17:13:55:15:INFO:sockeye.data_io:describe_data_and_buckets] Bucket (6, 10): 51381 samples in 155 batches of 332, ~2046.1 tokens/batch.
```

I thought `tokens/batch` means the average (number of source tokens + number of target tokens) per batch, but it seems like we are only taking the target sequence length into account. 

https://github.com/awslabs/sockeye/blob/27b27f71775dff7398c807106012949fe13b6ab2/sockeye/data_io.py#L175

The code is very confusing because it is now saved as `average_words_per_batch` member of `BucketBatchSize`,

https://github.com/awslabs/sockeye/blob/27b27f71775dff7398c807106012949fe13b6ab2/sockeye/data_io.py#L189

which is described as 'Approximate number of non-padding tokens in each batch', not really distinguishing whether we are talking about source tokens or target tokens.
https://github.com/awslabs/sockeye/blob/27b27f71775dff7398c807106012949fe13b6ab2/sockeye/data_io.py#L134

But if I am reading the code correctly, we the member variable `average_words_per_batch` is actually `average_target_tokens_per_batch`, and `tokens/batch` reported in https://github.com/awslabs/sockeye/blob/27b27f71775dff7398c807106012949fe13b6ab2/sockeye/data_io.py#L1023 is actually `target tokens/batch`.

Am I reading this correctly? If so, why are we focused on reporting target token statistics, and are not reporting source token statistics? At the least, shouldn't we change the name of the member variable and the log message? 

As a user, I was thinking the purpose of computing these statistics and logging them is to help users understand the efficiency of bucketization, but since we only report target token statistics, the log message does not seem to be useful for this purpose.

**Comment by bikestra** [comment]
Thanks for the reply! I will do the change and submit a PR.

**Comment by fhieber** [comment]
Closing for now, feel free to reopen if you have more questions.
