### ISSUE TITLE
Fused Bidirectional Encoder

### ISSUE THREAD

**Issue by mkolod** [awslabs/sockeye#68]
Hi,

The fused bidirectional encoder seems to be disabled at all times ([code snippet](https://github.com/awslabs/sockeye/blob/master/sockeye/encoder.py#L281:L299)), even when the user specifies that they prefer a bidirectional encoder, as well as fusion (via cuDNN). Is this something that is known to be problematic and is hence turned off?

Mentioning @fhieber here since this is probably of interest.

**Comment by fhieber** [comment]
Hi Marek,

yes, thats intentional since to our knowledge the bidirectional version of cuDNN RNN  (at least how it is exposed in MXNet) does not respect variable sequence lengths in batches, or features an argument like mx.sym.SequenceReverse. The same applies afaik to the BidirectionalCell in MXNet. 
We need to make sure that shorter sequences in a batch are correctly traversed in reverse order from the last non-pad symbol to the first symbol so that state concatenation of forward/reverse RNNs is correct.
However, we haven't really looked at that recently so if there are changes in cuDNN RNN that we could leverage, let us know :)

**Comment by mkolod** [comment]
Hi Felix,

Thanks so much for the clarification! That makes perfect sense. I'll investigate this and will let you know what I find regarding whether cuDNN supports what you need.

Marek

**Comment by fhieber** [comment]
Fantastic, thanks!

**Comment by mkolod** [comment]
@fhieber Here's the response I got from the folks in the know about the cuDNN details.

```
cudnn does not have a notion of padding, and it does not put padding anywhere. cudnn knows the length of each sequence in a batch, and operates only on valid entries. The input to cudnn is not a 3d padded tensor, but a list of 2d tensors with progressively smaller batch sizes (because shorter sequences drop out). Same for the output.

```
It's not a padded tensor, really, but more like a jagged tensor (analogous to a jagged matrix). In that case, if you want padding, then it will not be reversed, since there is either no padding (jagged tensor) or a padded tensor where padding is seen as valid entries.

Would it be possible at all to use jagged/unpadded tensors in MxNet and Sockeye somehow, or would that complicate things? If not, then SequenceReverse and non-cuDNN RNNs (RNNs at the graph level) may be the only way to deal with the current situation. It would be nice if padding could be completely removed, then cuDNN could handle "valid" (unpadded) sequence reversion.

**Comment by fhieber** [comment]
@mkolod thanks for investigating this! I am not aware of 'jagged tensors' in MXNet but there seems to be some work on sparse tensors, maybe that could be relevant. I'd say this is something to discuss with the MXNet folks whether they would like to support this feature from cuDNN in the future and if and how it fits into their APIs.

I think submitting an issue on this could get such a discussion started.

**Comment by mkolod** [comment]
Thanks @fhieber, I will submit the issue to MxNet directly.

**Comment by mkolod** [comment]
@fhieber, Eric suggested that it might be still better to use two FusedRNNCells that are unidirectional for the first layer, combined with the now-optimized SequenceReverse operator to feed the unidirectional "reverse" FusedRNNCell. Then merging them would still possibly give a speedup over the first layer having all operations unfused at all.

Also, I'd like to confirm my understanding here. If the first layer is bidirectional, and the user specified a FusedRNNCell, then are layers 2+ of the encoder fused right now? That's what I think it's happening looking at the code, but I'd like to confirm. Thanks!

**Comment by fhieber** [comment]
@mkolod yes, exactly, if we created fused cells, they are independent for each layer and direction.
I think the reason for creating stacked FusedRNNCells is that MXNet can compute gradients faster, whereas if one would use a single FusedRNNCell for multiple layers, MXNet has can not parallelize gradient computation. But I am not an expert on this.

Right now, we should measure speed & quality on this:
- using the optimized SequenceReverse operator vs. the old version
- additionally adding --fused to use two FusedRNNCells, one for the forward and one for the reverse pass in the BidirectionalEncoder layer.

For multiple encoder layers we should probably also create a SequentialCell with FusedRnnCells in it for the same reason as mentioned above. We might see bigger speedups for such complex models.
One thing that is noteworthy though is that I am not sure FusedRNNCells respect our mixed initialization scheme, where Xavier is used for all weights except .*h2h.* parameters, for which we use mxnet.initializer.Orthogonal.
