### ISSUE TITLE
What are the parameters for the cnn encoder-decoder model?

### ISSUE THREAD

**Issue by jiang2764** [awslabs/sockeye#686]
@fhieber  @tdomhan Can you point me the parameter setting for training the CNN encoder & decoder? Thank you.

**Comment by fhieber** [comment]
@jiang2764 What do you mean by parameter setting? The commandline parameters to train a CNN encoder/decoder model? In that case you should use `--encoder cnn --decoder cnn`.

**Comment by jiang2764** [comment]
> @jiang2764 What do you mean by parameter setting? The commandline parameters to train a CNN encoder/decoder model? In that case you should use `--encoder cnn --decoder cnn`.
@fhieber Thanks for the reply.
Sorry for the confusion. I know i should use `cnn` flag for the encoder and decoder. The issue is that I don't know the other parameter setting. Have you or your colleague tested the cnn method and got similar results to those reported in the original paper? I like the branch for the transformer model. Do you have a branch specifically for the cnn model?

**Comment by fhieber** [comment]
I never ran experiments with convolutional models myself. I thought the default parameters from the CLI are reasonable. 

Not sure which transformer branch you mean, but we also evaluated CNN models in our arxiv paper. The script to train the models from back then can be found here: https://github.com/awslabs/sockeye/blob/arxiv_1217/arxiv/code/cnn/sockeye/train.sh I'd try these parameter settings.
@tdomhan do you know more?

**Comment by jiang2764** [comment]
> Not sure which transformer branch you mean, but we also evaluated CNN models in our arxiv paper

@fhieber I mean the `arxiv_1217 branch`. Thanks.

**Comment by fhieber** [comment]
Feel free to reopen if you have more questions.
