### ISSUE TITLE
Why does dot_attention() requires lengths or bias?

### ISSUE THREAD

**Issue by SamuelLarkin** [awslabs/sockeye#688]
Hi,
I'm currently  modifying sockeye and I would like to use `MultiHeadAttention` without bias nor lengths.  I get an assertion under `dot_attention()` since I'm not providing neither bias nor lengths.
```
utils.check_condition(lengths is not None or bias is not None,
                          "Must provide either length or bias argument for masking")
```
Why do we have to provide either `lenghts` or `bias`?  The message implies an exclusive or between having `lengths` or `bias` but not both.

How can I use `MultiHeadAttention` with either `lengths` or `bias`?  I was trying to use `lengths` where `lengths` would a constant.

```
a = layers.MultiHeadAttention(depth_att=config.model_size,
                              heads=config.attention_heads,
                              depth_out=config.model_size,
                              dropout=config.dropout_attention,
                              prefix="%s_enc_attn_" % prefix)
memory_lengths= 4 * mx.nd.ones((source.shape[0]), dtype=source.dtype, ctx=source.context)
r = a(queries=queries,
   memory=memories,
   memory_lengths=memory_lengths)
```
but this fails with the following error message `AttributeError: 'Symbol' object has no attribute 'shape'` .  In general, I'm struggling with tensor shape. Is there an easy way to get the tensor's shape without invoking `.infer_shape()`?
Since my `memory` is of shape `(batch_size, 4)`, what I need is something like `memory_lengths = mx.sym.full(shape=(-1, 1), 4))` where `-1` would be automatically inferred as the `batch_size`.

May be a  more efficient way of achieving the same thing would be to create a `bias=0`?
```
a = layers.MultiHeadAttention(depth_att=config.model_size,
                              heads=config.attention_heads,
                              depth_out=config.model_size,
                              dropout=config.dropout_attention,
                              prefix="%s_enc_attn_" % prefix)
bias = mx.sym.zeros(shape=(1,1,1))
r = a(queries=queries,
   memory=memories,
   bias=bias)
```

**Comment by fhieber** [comment]
The layer requires either a bias or a length argument to do proper masking for variable sequence lengths. If your batch of memory is all of the same length, then you can either supply a `(batch_size,)` symbol containing with value of of the length dimension of your memory, or a bias that is all zero: `mx.sym.zeros_like(memory)`.

Also, I think you are mixing symbolic and imperative API here. the MultiHeadAttention layer only accepts symbols as input, not NDArrays. You cannot retrieve the shape of a symbol.

**Comment by SamuelLarkin** [comment]
Thanks!
I ended up trying `bias = mx.sym.zeros(shape=(1,1,1))` and it seems to be working, at least for now.

How would I proceed to create a `lengths` of `(batch_size,)` without having to bind it later to a value?  How do I declare a symbolic variable that contains a constant?

**Comment by fhieber** [comment]
It's a bit tricky in MXNet, but you could use `x = mx.sym.Variable('x', shape=<your_shape>, init=mx.init.Constant(value=4)`

**Comment by SamuelLarkin** [comment]
For sake of completion, `<our_shape>` implies knowing `batch_size`?  Is there a mechanism like tensorflow where you specify `None` for `batch_size`?

**Comment by fhieber** [comment]
You can try to use 0: `shape=(0, 1, 1)` and it may be able to infer it.

**Comment by SamuelLarkin** [comment]
Thanks a lot for your help.

**Comment by fhieber** [comment]
Closing, feel free to reopen if you have more questions on this.
