### ISSUE TITLE
PyYAML upgrade

### ISSUE THREAD

**Issue by jamesewoo** [awslabs/sockeye#689]
Any plans to upgrade to the latest PyYAML? GitHub is complaining about security issues with `pyyaml==3.12`.

Maybe `yaml.FullLoader` or `yaml.UnsafeLoader` would work:
https://github.com/yaml/pyyaml/issues/265

**Comment by fhieber** [comment]
Thanks for the pointer. I was thinking about this a while and now the `Loader` solution from PyYAML seems like a good way to go. see #690
