### ISSUE TITLE
"Illegal instruction(core dumped)"

### ISSUE THREAD

**Issue by DarrenZhang01** [awslabs/sockeye#692]
"Illegal instruction(core dumped)" when trying to run "python -m sockeye.train" ... on GPU. Could you help me analyze the possible reasons? Thanks!

The error message:
<img width="339" alt="屏幕快照 2019-05-06 23 25 07" src="https://user-images.githubusercontent.com/29133834/57269686-61186d80-7056-11e9-8da2-240bb5b3e2e2.png">

**Comment by bricksdont** [comment]
Can you please give more context? Such as
- What version of Sockeye and MXnet you are running, how you installed them
- What machine you are on, what operating system
- the training command you executed
- If this behaviour is consistent, i.e. if you can reproduce it

Thanks!

**Comment by DarrenZhang01** [comment]
> Can you please give more context? Such as
> 
> * What version of Sockeye and MXnet you are running, how you installed them
> * What machine you are on, what operating system
> * the training command you executed
> * If this behaviour is consistent, i.e. if you can reproduce it
> 
> Thanks!

It is solved! Thanks so much for reply. It is basically some installation issues.
