### ISSUE TITLE
Problem while loading existing params

### ISSUE THREAD

**Issue by bricksdont** [awslabs/sockeye#693]
With newest pip version of Sockeye (1.18.97), when resuming a partial training I am experiencing the following error:

    ValueError: Object arrays cannot be loaded when allow_pickle=False

Here are the scripts that lead to this error:

https://github.com/bricksdont/sockeye-toy-models/tree/u6

Specifically, running the script `train.sh` twice. I'm on a Google Cloud Compute instance, Tesla K80 GPUs, Linux, CUDA 10.0.

I think this is related to a numpy version, see e.g.

https://stackoverflow.com/questions/55890813/how-to-fix-object-arrays-cannot-be-loaded-when-allow-pickle-false-for-imdb-loa

and I've seen this happen in different contexts lately, for instance inside official Tensorflow Colab notebooks.

Could you check whether you can reproduce , and whether the solution is to downgrade numpy?

**Comment by tdomhan** [comment]
Thanks for reporting. I'll try to reproduce.

**Comment by bricksdont** [comment]
I am also getting the same error while running unit tests; downgrading numpy fixes the problem:

```
$ pip freeze | grep numpy
numpy==1.16.1
$ pip install --upgrade numpy==1.16.1
```

**Comment by fhieber** [comment]
Sockeye 2 updates various dependencies and has rewritten parameter loading logic.
The original issue also seemed to be solved with a different version of numpy. Closing.
