### ISSUE TITLE
BLEU for early stopping doesn't work?

### ISSUE THREAD

**Issue by msrivast-bbn** [awslabs/sockeye#695]
It seems that using  `BLEU` (or `ROUGE`) as early stopping metric does not work as expected. I tried running `sockeye.train` module with the following additional parameters:

```
--optimized-metric bleu --monitor-pattern bleu
```

(replacing 'bleu' with 'rouge' had the same issue)

The BLEU score on the validation set was always calculated to be `0.0`, and the training would stop after  5 checkpoints (by default):

```
[INFO:sockeye.training] Validation-bleu has not improved for X checkpoints, best so far: 0.000000
```
It looks like when `_create_metrics` method is called from the following line:

https://github.com/awslabs/sockeye/blob/master/sockeye/training.py#L634

In line no. [1019](https://github.com/awslabs/sockeye/blob/master/sockeye/training.py#L1019), instead of using `metrics` in the call to `_create_eval_metric`:

```python
metric_val = self._create_eval_metric_composite(metrics)
```

we should use `self.state.early_stopping_metric`:

```python
metric_val = self._create_eval_metric_composite(self.state.early_stopping_metric)
```

I am not sure if this may have repercussions elsewhere tho. Just wanted to raise this issue with other developers.

Let me know if there's something that I am missing, or if you would need more information.

**Comment by msrivast-bbn** [comment]
I was wondering if anybody got a chance to see this issue, and has any comments. Thanks!

**Comment by fhieber** [comment]
Hi @msrivast-bbn, apologies for the very delayed reply. I was trying to reproduce your issue, but couldn't. 
When I use `--optimized-metric bleu` for `sockeye.train`, it correctly monitors BLEU scores at every checkpoint and determines early stopping from that. A few notes on that feature:
- it will automatically enable the CheckpointDecoder which spawns a subprocess at every checkpoint to decode the full validation set using sockeye.translate and compute BLEU. The training will stop at the next checkpoint to wait for the concurrently running subprocess if not yet finished. Are you sure this works in your case?
- This means that the BLEU score for checkpoint 1 will only be available at checkpoint 2). It is admittedly a bit confusing that the `validation-bleu` log message at the first checkpoint says `0.0`. In my test however, the second checkpoint correctly identifies the BLEU score and denotes an improvement (so do later checkpoints).
- Your use of `monitor-pattern` will not do what you intend to do. It is a (quite outdated) feature to log data from a computation graph in MXNet. We should probably remove that feature.

**Comment by fhieber** [comment]
Closing for now, if you have more questions feel free to reopen.
