### ISSUE TITLE
Resource deadlock avoided

### ISSUE THREAD

**Issue by MichaelZhouwang** [awslabs/sockeye#700]
I tried to train a transformer model with 
python -m sockeye.train -d train_data -vs dev.src -vt dev.trg -o gec_model --lock-dir var\tmp And then I met an error :
 [INFO:sockeye.utils] Attempting to acquire 1 GPUs of 1 GPUs. The requested devices are: [-1]
[INFO:sockeye.utils] Acquired GPU master_lock.
[INFO:sockeye.utils] Acquired GPU 0.
[INFO:sockeye.utils] Releasing GPU master_lock.
[INFO:sockeye.utils] Releasing GPU 0.
[ERROR:root] Uncaught exception
Traceback (most recent call last):
  File "C:\Users\v-waz\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\portalocker\portalocker.py", line 73, in lock
    msvcrt.locking(file_.fileno(), mode, lock_length)
OSError: [Errno 36] Resource deadlock avoidedportalocker.exceptions.LockException: (1, 'Resource deadlock avoided')

What's the reason of this error and how can I fix it? Thanks.

**Comment by tdomhan** [comment]
This is an exception thrown from the underlying locking library `portalocker`. This is out of our control and I would therefore suggest raising a ticket with that library: https://github.com/WoLpH/portalocker

To unblock your training you can temporarily disable locking:
```
--disable-device-locking
```

I hope that helps.

**Comment by MichaelZhouwang** [comment]
> This is an exception thrown from the underlying locking library `portalocker`. This is out of our control and I would therefore suggest raising a ticket with that library: https://github.com/WoLpH/portalocker
> 
> To unblock your training you can temporarily disable locking:
> 
> ```
> --disable-device-locking
> ```
> 
> I hope that helps.

Thanks! It helps. I have another question that when I pass the bpe-preprocessed training data to sockeye data preparation and then train the model. During inference I got a lot of "asymp@@ " tokens for relatively rare words. Why would this happen? Thanks a lot!

**Comment by tdomhan** [comment]
This is just the data in the BPE format. BPE splits word into known subwords. As a postprocessing step you can merge the sub-words, e.g.:
```
cat translations | sed "s/@@//g"
```

**Comment by MichaelZhouwang** [comment]
> This is just the data in the BPE format. BPE splits word into known subwords. As a postprocessing step you can merge the sub-words, e.g.:
> 
> ```
> cat translations | sed "s/@@//g"
> ```

Thanks. I know it is bpe processed tokens, but it is wired that "asymp@@ " appears way too many times. Perhaps it is because of overfitting? I'll try to add more regularization and see what will happen. Thanks~

**Comment by tdomhan** [comment]
oh ok. Or maybe not enough training data. Did the model finish training or are you looking at samples during training?

**Comment by MichaelZhouwang** [comment]
Yes it finished after valid perplexity stop increase for 32 epochs.  I am working on grammar error correction and I have roughly 1.7M sentence pairs. I used default transformer architecture and training/validating ppl are both around 2-3. Most of the predictions are fine except for the asymp@@ which keep appearing where it should be other relatively rare words.

**Comment by tdomhan** [comment]
Interesting, but then it mostly seems like a model issue. So the asymp@@  token does not appear frequently in the training data? 1.7M sentence pairs is definitely a decent amount.

**Comment by tdomhan** [comment]
I will close the issue for now. Let us know if you have other issues.
