### ISSUE TITLE
Python Package for GPU

### ISSUE THREAD

**Issue by jamesewoo** [awslabs/sockeye#702]
Can we get a Python package `sockeye-gpu` to simplify installation of GPU related dependencies?
Instead of downloading the latest GPU requirements file it would become `pip install sockeye-gpu`. This also helps avoid the situation in which both CPU and GPU versions of MXNet are installed by accident.

**Comment by tdomhan** [comment]
The problem is that there is one mxnet version per CUDA version, which means that we would need to upload one sockeye python package per GPU version as well. So you ran into lot of issues with the approach of using the requirements file?

**Comment by jamesewoo** [comment]
No major issues using the requirements file. It would simplify the installation of Sockeye in Docker images, though.

**Comment by tdomhan** [comment]
How does your Dockerfile currently look like? Something along the lines of:
```
RUN wget https://raw.githubusercontent.com/awslabs/sockeye/master/requirements/requirements.gpu-cu${CUDA_VERSION}.txt  && \
  pip install sockeye --no-deps -r requirements.gpu-cu${CUDA_VERSION}.txt &&\
  rm requirements.gpu-cu${CUDA_VERSION}.txt
```
?

**Comment by jamesewoo** [comment]
For CPU it's:
```
RUN pip3 install --user -U pip pipenv \
    && pipenv install
```
But for GPU it's:
```
RUN pip3 install --user -U pip pipenv \
    && pipenv run pip install --no-cache-dir --no-deps sockeye==$SOCKEYE_VERSION \
    && pipenv install
```
where `sockeye` is in the first Pipfile but not in the second. It would be nice if I could avoid the extra `pip install` in the second `RUN` command.
