### ISSUE TITLE
Constrained decoding with "<s>" (BOS) constraint: possible bug

### ISSUE THREAD

**Issue by bricksdont** [awslabs/sockeye#710]
I am observing odd behaviour with constraints that include `<s>`. If I understand this page correctly:

https://awslabs.github.io/sockeye/inference.html

`<s>` and `</s>` are special constraints and mean BOS and EOS.

I have a multilingual system, where the target language is indicated on the target side of the parallel training data, e.g. `<2de>`.

Then I use constrained decoding and JSON input. One line of the input looks as follows:

    {"text": "tyto peníze po@@ mohly téměř 800 000 mlad@@ ých lidí a 55 000 mal@@ ých podniků v celé Evropě .", "constraints": ["<s> <2de>"]}

But the translation very often looks like:

    <2en> this money helped almost 800 000 young people and 55 000 small businesses across Europe . <s> <2de> .

Where `<s>` seems to be interpreted as a regular token and `<2de>` is not actually at the beginning of the translation. Am I misunderstanding the purpose of `<s>` in this case?

Sockeye version 1.18.89, MXnet version 1.4.0

**Comment by fhieber** [comment]
@mjpost Does constrained decoding support these types of constraints (i.e. encoding that the constraint should appear at the beginning of the sentence)?

**Comment by bricksdont** [comment]
Just to clarify: I thought this was possible because of the "scoring" section here:

https://awslabs.github.io/sockeye/inference.html

which explains how constrained decoding can be used as a rudimentary scoring mechanism, and the example call is:

    echo '{ "text": "This is a test", "constraints": ["<s> Dies ist ein Test </s>"] }' \
    python3 -m sockeye.translate -m /path/to/model --json-input --beam-size 1 \
    --output-type translation_with_score

**Comment by mjpost** [comment]
Yes, `<s>` and `</s>` should enforced as start-of-sentence and end-of-sentence tokens by the constraint system. Perhaps it got broken at some point. Do you see any message about OOV constraints or anything in the logger output?

**Comment by bricksdont** [comment]
No, for the specific example above the only logging output is

    [2019-07-09:15:24:07:INFO:sockeye.inference:translate] Input 1 has 1 constraint: <s> <2de>

- What message in particular is it that warns about OOV constraints?
- Could you please point me to the code that treats differently "normal" constraints and ones that have `<s>` and `</s>`? I cannot find it right now.

Let me know what exactly you need from me to debug / reproduce.

**Comment by mjpost** [comment]
If for example you give it a constraint token that is OOV, it will complain. But I think that would be unrelated here. Clearly the constraints aren't working. My guess is either (a) the constraint state is updated in the loop but isn't fed the `<s>` so that it can start tracking or (b) no hypothesis with the constraints met actually survives the beam.

I am not sure I'll have time in the near future to fix this, unfortunately...

**Comment by bricksdont** [comment]
Thanks Matt! I will try a wider beam (does this mean higher chances to meet the constraint?), and have a closer look at the code.

**Comment by mjpost** [comment]
That could help. What were you using? Make sure to use `--beam-prune 30 --beam-size 20`.

**Comment by bricksdont** [comment]
I was using `--beam-prune 20 --beam-size 20`.

**Comment by mjpost** [comment]
Probably fine. It's actually probably a bug. Can you get it to work with a simpler example?

**Comment by mjdenkowski** [comment]
Closing for now as this applies to an older version of Sockeye.
