### ISSUE TITLE
Error with YAML training config file

### ISSUE THREAD

**Issue by okgrammer** [awslabs/sockeye#734]
Hello, I am having a problem with running sockeye training by using a YAML config file. I'm getting this error message:

```
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!TransformerConfig'
  in "config.yaml", line 1, column 17
```

Config file: https://gist.github.com/okgrammer/f87b9e7f74cc069cb8136bce578e7c20
Training command:
```
python -m sockeye.train \
    --config config.yaml \
    --source $bpe_dir/train.src.gz \
    --target $bpe_dir/train.trg.gz \
    --validation-source $bpe_dir/dev.src.gz \
    --validation-target $bpe_dir/dev.trg.gz \
    --output $model_dir \
    --device-ids -4 2> $log_file
```

Have been trying debugging it for a while, but could not figure what's wrong with it still. Any help is appreciated!

**Comment by fhieber** [comment]
Hi @okgrammer ,

thanks for your question and apologies for the delay in responding to your issue. The config file you are supplying is a configuration file for the model (`<modelfolder)/config.yaml`), which is not what this commandline argument (--config) expects. Instead what it requires is a file similar to `<modelfolder>/args.yaml` that simply contains the commandline arguments passed to the CLI in YAML format. I agree this is not well documented and can be a bit confusing.

**Comment by tdomhan** [comment]
Closing the issue.

**Comment by tomsbergmanis** [comment]
Good one... figuring this out is a bit difficult given that tutorial says that it should be config.yaml
https://awslabs.github.io/sockeye/tutorials/adapt.html

**Comment by fhieber** [comment]
Oh, good catch, thank you! I will update the tutorial.
