### ISSUE TITLE
Does sockeye support multi-task training?

### ISSUE THREAD

**Issue by eecrazy** [awslabs/sockeye#743]
Does sockeye support multi-task training? Like two decoders share the same encoder in an alternatively training?

For example, I want to train English->German and English->French at the same time, and German decoder and French decoder share the same English encoder?

Is there any proper way I can do this with sockeye?

**Comment by fhieber** [comment]
You can of course do this, but not out of the box and it would require some coding. You would probably need to write a custom data iterator that alternatives between French and German batches (or mixes them). In the model definition you would want to create a second decoder instance and then you have to determine for each batch what decoder to send it to.

**Comment by fhieber** [comment]
Here is a similar issue about multi-source models: https://github.com/awslabs/sockeye/issues/701

**Comment by eecrazy** [comment]
I see, thank you!

**Comment by fhieber** [comment]
Closing for now, feel free to reopen if you have more questions.
