### ISSUE TITLE
Installation fails due to conflicting numpy version

### ISSUE THREAD

**Issue by NeolithEra** [awslabs/sockeye#764]
Hi, users are unable to run **_sockeye_** due to dependency conflict with _**numpy**_ package. As shown in the following full dependency graph of **_sockeye_**, **_sockeye_** requires _**numpy >=1.14**_，while **_mxnet-mkl_** requires **_numpy <1.17.0,>=1.8.2_**.

According to pip’s _“first found wins”_ installation strategy, _**numpy 1.17.4**_ is the actually installed version. However, _**numpy 1.17.4**_ does not satisfy **_<1.17.0,>=1.8.2_**.

### Dependency tree-----------
```
sockeye - 1.18.106
| +- mxnet-mkl(install version:1.4.1 version range:==1.4.1)
| | +- numpy(install version:1.4.1 version range:<1.17.0,>=1.8.2)
| +- numpy(install version:1.16.5 version range:>=1.14)
| +- portalocker(install version:1.5.2 version range:*)
| +- pyyaml(install version:5.2 version range:>=5.1)
| +- sacrebleu(install version:1.3.6 version range:==1.3.6)
| | +- typing(install version:3.7.4.1 version range:*)
| +- typing(install version:3.7.4.1 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependency to be **_mxnet-mkl>=1.4.1_**. I have checked this revision will not affect your downstream projects now.
2.	Remove your direct dependency **_numpy_**, and use **_numpy_** transitively introduced by **_mxnet-mkl_**.

@fhieber Which solution do you prefer, 1 or 2?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by fhieber** [comment]
Hi @NeolithEra ,
Thanks for investigating! First choice is not an option as we would like to depend on MXNet 1.5.1. I am also not a big fan of transitive dependencies if we use nunpy explicitly in Sockeye. Would it work to simply use the same version requirement as mxnet-mkl?

**Comment by bricksdont** [comment]
In case that's relevant here: newer versions of numpy cause problems for training continuation:

https://github.com/awslabs/sockeye/issues/693

**Comment by fhieber** [comment]
This is fixed in Sockeye 2, closing.
