### ISSUE TITLE
import error on train CLI

### ISSUE THREAD

**Issue by cherryc** [awslabs/sockeye#78]
First commit that exhibits the error:
34748cb

Error:
Training the model...
Traceback (most recent call last):
  File "/Users/cherryc/nlp/jsalt/git/upstream/sockeye/sockeye/train.py", line 32, in <module>
    from . import arguments
ImportError: cannot import name 'arguments'

Command:
PYTHONPATH=$SOCKEYE python3 $SOCKEYE/sockeye/train.py \
  --source data/multi30k/train-toy.$1.atok \
  --target data/multi30k/train-toy.$2.atok \
  --validation-source data/multi30k/val.$1.atok \
  --validation-target data/multi30k/val.$2.atok \
  --word-min-count 2 \
  --rnn-num-layers 1 \
  --rnn-cell-type gru \
  --rnn-num-hidden 64 \
  --num-embed-source 64 \
  --num-embed-target 64 \
  --attention-type mlp \
  --attention-num-hidden 64 \
  --batch-size 64 \
  --normalize-loss \
  --dropout 0.1 \
  --optimizer adam \
  --initial-learning-rate 0.001 \
  --use-cpu \
  --output models/multi30k-$1-$2/baseline

**Comment by davvil** [comment]
You should call train, and other CLI tools, as modules, i.e. "PYTHONPATH=$SOCKEYE python3 -m sockeye.train <args>". Calling train.py directly generates the import error you are seeing.

It may have been the case that direct invocation worked before, but it was not explicitly supported.

**Comment by cherryc** [comment]
That fixed it, thanks.
