### ISSUE TITLE
Serialize Sockeye model cache to reduce model init time?

### ISSUE THREAD

**Issue by shashi-tn** [awslabs/sockeye#781]
First time Sockeye/MXNet user here.

I am trying to deploy a Seq2Seq model using Sockeye. At inference time, the model seems pretty quick except for when it sees a piece of text which is longer than the text blobs it has seen before.

I figured out a work-around for this by initializing the model at the beginning with texts of varying length that I would expect at inference time - small to large.
It did the job, but now the model initialization time seems too long for my use case.

I am wondering how can I initialize the model with a custom set of text data and serialize the cache and carry it along the model to deployment.
Then, I would just need to a. load the architecture + b. load the weights + c. load the cache.

Has anybody tried anything like this? Or have an opinion whether his would work (reduce the model initialization time)? Or any other ideas to do the same?

I am open to suggestions.

**Comment by fhieber** [comment]
Hi @shashi-tn,

If you train your model on sentences of a maximum length of `n`, Sockeye will by default split inputs at inference time into chunks of size `n` and translate them in sequence, if the input > `n`.

Generally, I wouldn't expect a model to perform very well on data that looks very different from the training data. But besides this, I am not sure I understand what you mean by cache. Are you referring to the computation graphs created for each bucket? Technically, you can serialize them through the MXNet Module API and load them at inference time but that would require you to work around the Sockeye logic a little bit.

**Comment by fhieber** [comment]
Closing. Feel free to reopen if you have more questions.
