### ISSUE TITLE
Time statistics for scoring are strange

### ISSUE THREAD

**Issue by bricksdont** [awslabs/sockeye#786]
I am using

    python -m sockeye.score

to score a large number of lines, roughly two million. After processing the file in many batches, the last logging entry is

    [INFO:sockeye.scoring] Processed 2069323 lines in 512 batches. Total time: 6.4850, sec/sent: 0.0000, sent/sec: 319094.8627

The total time to process two million lines was certainly more than 6 seconds.

The log entry originates here:

https://github.com/awslabs/sockeye/blob/ca0eb7fee6a902722b3c42b5d66a0872da231606/sockeye/scoring.py#L293

but I'm not sure yet how exactly the calculation is wrong, or why the timing could be off in certain environments.

**Comment by fhieber** [comment]
Can you put an `mx.nd.waitall()` in line 260 and try again?

**Comment by tdomhan** [comment]
yeah, it's likely because the model runs asynchronously. If this is the issue we should just measure total_time = time.time() - start_time before the logging statement.

**Comment by bricksdont** [comment]
Sorry for the delay!

After including the wait:

    [INFO:sockeye.scoring] Processed 2069323 lines in 512 batches. Total time: 3673.3927, sec/sent: 0.0018, sent/sec: 563.3275

Which is roughly 1 hour. Actual time elapsed according to the batch scheduling system:

    01:24:10

So, waiting for asynchronous calls alone does not appear to solve the problem. Also, I am not sure: does`mx.nd.waitall()` _prevent_ asynchronous operations, or does it simply do better accounting?

**Comment by tdomhan** [comment]
Is there any overhead like downloading the model?

If not, it may be worth checking the timing if the end_time measurement was moved to the end of the for loop (line 291).  The output processing taking up time is the only other explanation, although it would be a bit surprising if this much time was spent there.

**Comment by bricksdont** [comment]
If I use overall `time.time()` outside of the for loop (as suggested by Tobi), the total time is:

    [INFO:sockeye.scoring] Processed 2069323 lines in 512 batches. Total time: 4978.0369, sec/sent: 0.0024, sent/sec: 415.6906

Actual time elapsed:

    01:23:14

Which is exactly right. There is no loading overhead or similar, it's just that time taken to score only partially reflects overall time. The code also creates lots of bucketed parallel data sets, this might take time.

**Comment by tdomhan** [comment]
huh, thanks for checking! So it means we spend a lot of time on the post-processing/output handling. I think it would make sense to move the time measurement at the end of the loop as processing a batch does include feeding it to the output handler. As at that point the data has been consumed we probably don't need the waitall at that point.

**Comment by bricksdont** [comment]
No, not necessarily a lot of time spent in postprocessing in my opinion. More info, don't know if relevant here:

A new data set is created for each batch:

    [INFO:sockeye.data_io] Created bucketed parallel data set. Introduced padding: source=87.2% target=87.3%)

For me, the number of batches is ~ 4000, i.e. I am seeing the line above ~ 4k times in the log. The reason is that `data_io.BatchedRawParallelSampleIter` calls `load` of a dataset loader for every batch:

https://github.com/awslabs/sockeye/blob/bcda5699670ea66e3919cf6fe197e03971110b80/sockeye/data_io.py#L1661

--------

The number of batches reported is also strange:

    Processed 2069323 lines in 512 batches.

I did specify a batch size of 512 and word-level batching, the number of actual batches is 4k. What is logged is num_sentences divided by num_batches:

https://github.com/awslabs/sockeye/blob/bcda5699670ea66e3919cf6fe197e03971110b80/sockeye/scoring.py#L294

**Comment by fhieber** [comment]
scoring is rewritten in Sockeye and the issue should be fixed. Feel free to reopen if you observe the problem again.
