### ISSUE TITLE
Cuda 10.2

### ISSUE THREAD

**Issue by i55code** [awslabs/sockeye#788]
Hi, when will cuda 10.2 will supported by sockeye? Thanks!

**Comment by fhieber** [comment]
Hi @i55code ,

Cuda 10.2 support depends on MXNet. It doesn't seem like they are currently offered: https://mxnet.apache.org/get_started?platform=linux&language=python&processor=gpu&environ=pip&

https://github.com/apache/incubator-mxnet/issues/17058

Closing, as this is not a Sockeye issue.

**Comment by tdomhan** [comment]
FYI https://github.com/apache/incubator-mxnet/issues/17058 So there should be support with the next MXNet version.
