### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by i55code** [awslabs/sockeye#790]
Hi all, I hope to ask for some help with training: 

When I train a model by specifying -o -vs -vt -d: 
python3 -m sockeye.prepare_data -s $DIR/train.s -t $DIR/train.t -o $DIR/train-sockeye
python3 -m sockeye.train -d $DIR/train-sockeye -o $DIR/out -vs $DIR/valid.s-vt $DIR/valid.t

I receive the error below: 
Mismatch in arguments for training continuation.
Differing arguments: encoder, initial_learning_rate, source, prepared_data, decoder, num_layers, num_embed, rnn_num_hidden, target.

I did not specify any of the above, what might caused this?

**Comment by fhieber** [comment]
It seems like the call to `sockeye.train` is trying to continue an existing training in the same output folder that used different sets of parameters. Can you delete $DIR/out first? You could also specify `--overwrite-output` to do this automatically.

**Comment by i55code** [comment]
Thank you so much @fhieber :) This solves it!
