### ISSUE TITLE
K-Fold Cross Validation Implementation

### ISSUE THREAD

**Issue by lachiemg** [awslabs/sockeye#791]
Hi,

I was just wondering if there is currently, or are there plans, for an implementation of K-Fold Cross Validation. I understand it isn't too hard to implement personally, but I feel like it would be a good addition for those with a corpus.

**Comment by fhieber** [comment]
Hi @lachiemg what is your use case for cross validation?

**Comment by lachiemg** [comment]
Hi @fhieber,

I am trying to train a model on converting informal to formal English. Unfortunately, datasets of this variety are pretty hard to come by, so we only have a training dataset size of 75k synonymous sentence pairs. On the AWS MLU course, they mentioned that K-Fold Cross-Validation could be used to bolster the training of limited datasets.

On a side note, if you know of any good datasets out there for this application, please let me know! 

Thanks

**Comment by fhieber** [comment]
Hi @lachiemg,

Cross-validation in this case could probably be implemented fairly easily as a thin wrapper script around sockeye.train/sockeye.translate. I don't think we would provide much additional value if we would pull something like that into Sockeye.

**Comment by fhieber** [comment]
Closing. Feel free to reopen if you have more questions.
