### ISSUE TITLE
sockeye.utils.SockeyeError: Given major version (1.0.3) does not match major code version (1.18.106)

### ISSUE THREAD

**Issue by nariman9119** [awslabs/sockeye#793]
Trying to translate from one language to another and it gives me this error. The problem is that I trained the model on GCP and then download it to my local computer and when I am using sockeye.translate it gives this and I can not find out why:(

**Comment by tdomhan** [comment]
You used an extremely old version of Sockeye for training (1.0). The major version needs to match. So you can either train a model with the code major version you have (1.18) or check out an old version of Sockeye.

**Comment by nariman9119** [comment]
The error happened because I did not have a config file in my model directory. 
Thanks for fast response!!
