### ISSUE TITLE
Gradient delay?

### ISSUE THREAD

**Issue by tomsbergmanis** [awslabs/sockeye#805]
Marian NMT has a gradient delay mechanism, which allows to accumulate several smaller batches thus allowing for much larger batch size than what would fit in GPU memory. Does Sockeye implement anything similar?

**Comment by fhieber** [comment]
You can use `--update-interval x` to set the number of batches to process to `x` before doing a gradient update.

**Comment by fhieber** [comment]
Closing for now, feel free to reopen if you have more questions.
