### ISSUE TITLE
Training checkpoint stopped creating decode.output 

### ISSUE THREAD

**Issue by ogunoz** [awslabs/sockeye#811]
Hi,

After passing some checkpoints successfully, sockeye stops calculating BLEU score during checkpoints but it keeps logging perplexity and saves new params.NUM files.

**Last successful Checkpoint**

> [2020-05-14:17:46:36:INFO:sockeye.training:fit] Checkpoint [88] Updates=440000 Epoch=16 Samples=280841176 Time-cost=2919.597 Updates/sec=1.713
> [2020-05-14:17:46:36:INFO:sockeye.training:fit] Checkpoint [88] Train-perplexity=2.603048
> [2020-05-14:17:46:38:INFO:sockeye.training:fit] Checkpoint [88] Validation-perplexity=1.350713
> **[2020-05-14:17:46:38:INFO:sockeye.training:collect_results] Decoder-87 finished: {'bleu-val': 0.7527509099234959, 'chrf-val': 0.8385353050482615, 'rouge1-val': 0.7619336112171186, 'rouge2-val': 0.6748560114329887, 'rougel-val': 0.7457107039294799, 'length-ratio-mse': 1.0308577832975823, 'avg-sec-per-sent-val': 0.08381631994247436, 'decode-walltime-val': 41.90815997123718}**
> [2020-05-14:17:46:38:INFO:sockeye.training:start_decoder] Starting process: Decoder-88
> [2020-05-14:17:46:40:INFO:sockeye.training:fit] Validation-perplexity improved to 1.350713 (delta=0.000705).
> [2020-05-14:17:46:41:INFO:sockeye.utils:log_gpu_memory_usage] GPU 1: 24486/32480 MB (75.39%) GPU 2: 24218/32480 MB (74.56%)
> [2020-05-14:17:47:28:INFO:sockeye.training:__call__] Epoch[16] Batch [440050]   Speed: 634.01 samples/sec 21833.64 tokens/sec 0.94 updates/sec   perplexity=2.607029

**Next Checkpoint**

> [2020-05-14:18:35:35:INFO:sockeye.training:fit] Checkpoint [89] Updates=445000 Epoch=16 Samples=284026656 Time-cost=2915.589 Updates/sec=1.715
> [2020-05-14:18:35:35:INFO:sockeye.training:fit] Checkpoint [89] Train-perplexity=2.601719
> [2020-05-14:18:35:37:INFO:sockeye.training:fit] Checkpoint [89] Validation-perplexity=1.352920
> [2020-05-14:18:35:37:INFO:sockeye.training:start_decoder] Starting process: Decoder-89
> [2020-05-14:18:35:39:INFO:sockeye.training:fit] Validation-perplexity has not improved for 1 checkpoints, best so far: 1.350713
> [2020-05-14:18:35:41:INFO:sockeye.utils:log_gpu_memory_usage] GPU 1: 24486/32480 MB (75.39%) GPU 2: 24218/32480 MB (74.56%)
> [2020-05-14:18:36:28:INFO:sockeye.training:__call__] Epoch[16] Batch [445050]   Speed: 568.60 samples/sec 21589.55 tokens/sec 0.94 updates/sec   perplexity=2.603905

After this point, validation set is not evaluated with BLEU and no decode.output.NUM created. There is neither a warning log.

 Here is the running environment:

Python 3.6.10 :: Anaconda, Inc.
sockeye==1.18.106
mxboard==0.1.0
mxnet-cu101==1.6.0 # CUDA 10.1 is installed in device
mxnet-mkl==1.4.1

I have another device with CUDA 10.0 and there is no such a problem there. So you may not easily reproduce the issue. I hope you can help.

**Comment by ogunoz** [comment]
I am calling the sockeye through Jupyter notebook using sockeye.arguments.add_train_cli_args

When I directly use a shell script, everything works fine. I think it is not a sockeye related problem but a Jupyter environment problem. So you can close the issue but it would be even better if you could add an INFO or WARNING level log when a checkpoint Decoder can't be finished as a nice to have feature.

**Comment by fhieber** [comment]
Hi @ogunoz 
In this version of Sockeye, the decoder process to translate the validation data is actually spawned in a subprocess and its results are collected when the main training process reaches the next checkpoint. It could be that this setup does not play well with running side a Jupyter notebook. Are there restrictions to subprocesses/logging of output from subprocesses inside notebooks?

**Comment by fhieber** [comment]
Newer versions of Sockeye (>2.0) will not decode in a subprocess and therefore this issue should not be present once you update.

**Comment by ogunoz** [comment]
Hi @fhieber 

Thank you so much for your response. After our one week investigations, I realized that it is not related with Jupyter notebook as well. I suspect that it is related with the shared folder structure in the cloud machine. I will check the new Sockeye! If there is no reason for me to use the older one, I will migrate to 2.0. Thank you also for this information.

**Comment by ogunoz** [comment]
Just another note, when the decoder cannot translate and generate BLEU score, if validation perplexity is improved, it keeps updating the params.best. For this reason, when I try to go on from interrupted point, I can't actually use the "real" params.best. For your information :)

**Comment by ogunoz** [comment]
I believe with the new version >= 2.0, it is going to be fixed. So I am closing the issue now.

**Comment by ogunoz** [comment]
I have one more question to specify "Sockeye 2" version. I couldn't find any released package for that. Should I directly clone it from your [sockeye2 branch](https://github.com/awslabs/sockeye/tree/sockeye_2)?

**Comment by fhieber** [comment]
Yes, you can clone the sockeye_2 branch to use it. We haven’t released to pypi yet.
