### ISSUE TITLE
Model's compatibility between Sockeye 2.+ and previous versions

### ISSUE THREAD

**Issue by ktoetotam** [awslabs/sockeye#818]
Hello,

We had to switch to Sockeye 2.1.7 from Sockeye 1.18.106 because of the issue described in  #811 

Is there any way to make the models trained in different Sockeye versions compatible? It is relevant for us for the cases when we want to retrain a model with the parameters of an older model or continue the training of a model trained in 1.18.106 (particularly relevant for the models that were affected by the issue #811 ) but also for inference. 

Currently, we are getting the error: 
SockeyeError: Given release version (1.18.106) does not match release code version (2.1.7)

Best regards,
Maria

**Comment by fhieber** [comment]
Hi @ktoetotam,
Sockeye 2 is a ground up rewrite of most of the pieces in Sockeye and maintaining backwards compatibility would be quite difficult. Currently there is no mechanism to convert a Sockeye 1 model into a Sockeye 2 model.

**Comment by ktoetotam** [comment]
@fhieber I see, is there also a reason why Sockeye 2.0 does not have beam-prune? Setting a higher beam pruning parameter was really helping to speed up the inference and did not have any negative effect on BLEU score. So we are really curious about what is the motivation behind removing it and if there any other way to use it?

**Comment by fhieber** [comment]
Hi @ktoetotam, no specific reason, we just focused on core features to port to Sockeye 2. The new version should overall be quite a bit faster than Sockeye 1, so I suggest you give it a try first without beam pruning. If still needed by your use case, feel free to submit a PR.

**Comment by fhieber** [comment]
Closing for now, feel free to reopen if you have more questions.
