### ISSUE TITLE
End-to-end tests?

### ISSUE THREAD

**Issue by mjdenkowski** [awslabs/sockeye#82]
We're reaching a large enough number of components that it's probably not reasonable to expect everyone to know what everyone else is working on and avoid potential breaks.  Our unit tests are doing a great job catching local problems but it would be nice to run end-to-end tests to make sure our code produces output, however bad.

One option would be to build a tiny model on literally a few lines of data just to make sure we can go from data to model to decoded output and a zero exit code.  I can look at this next week.  Anyone else have thoughts on automated end-to-end tests?

**Comment by fhieber** [comment]
Very much agreed. I was hoping to get to this this week, but haven't been able to.
What I was considering to do is to write an integration test for multiple configurations on a sequence-copy or sequence-sorting task for numbers (0-9). The former is fairly simple and one should very quickly reach a ppl of 1. The advantage is that we could generate this data randomly on-the-fly when running the test, and would not need to checkin data files anywhere.

From a technical point of view I am not sure whether this should be implemented as a unit test, or somehow be run on TravisCI / Github for every commit/PR. 
Do you have any opinion on that?

**Comment by tdomhan** [comment]
training a small network + translating a few sentences on Travis CI seems like a good option. The sequence copy task trains super quickly with just a tiny network, so it should be possible to run this for all commits.

**Comment by mjdenkowski** [comment]
Sounds good!  I was thinking of a similar test with a couple of model configurations to cover as many options as possible.  I'm putting it on my queue for next week but if anyone else can get to it sooner, feel free to get started!

**Comment by fhieber** [comment]
+1, lets sit together next week to get this in!

**Comment by fhieber** [comment]
#85

**Comment by fhieber** [comment]
Closing this for now (#85 was merged)
