### ISSUE TITLE
Extract embeddings trained

### ISSUE THREAD

**Issue by i55code** [awslabs/sockeye#830]
Hi, may I ask 2 questions: 

1.  what is a simple command for extracting embeddings trained in a sockeye model? 
2. Does sockeye provides a way to visualize the embeddings (2D, 3D or PCA)? 

Thanks!

**Comment by fhieber** [comment]
Hi,

1) you can take a look at how `sockeye/embeddings.py` does it:
```python
sockeye_model, src_vocab, trg_vocab = sockeye.model.load_model(<model_dir>)
params = model.collect_params()
if args.side == "source":
        logger.info("Loading %s", sockeye_model.source_embed_weight.name)
        weights = params[sockeye_model.source_embed_weight.name].data()
    else:
        logger.info("Loading %s", sockeye_model.target_embed_weight.name)
        weights = params[sockeye_model.target_embed_weight.name].data()
    logger.info("Embedding size: %d", weights.shape[1])
```

The CLI in `embeddings.py` has some very rudimentary way of computing the k nearest neighbors for an input.

2) No, but you simply convert the embeddings matrix to a numpy matrix (`.asnumpy()`) and use your favorite visualization tool from there.

**Comment by i55code** [comment]
Thank you so much! This is very helpful!
