### ISSUE TITLE
sockeye commands fail in Linux with Illegal instruction error

### ISSUE THREAD

**Issue by MrRaghav** [awslabs/sockeye#836]
Hello, I have quickly checked all the 196 closes issues and hope that I'm not duplicating any of them. Also, I have went through following link to understand installation process: https://awslabs.github.io/sockeye/setup.html

Actually, I am expected to use Sockeye in a **distributed Linux environment**. I am explaining the steps and errors found by me in below points:

### 1) pip install sockeye

when I used this, it created files like **sockeye-prepare-data** and **sockeye-train** in **/home/[my user name]/.local/bin** folder.
When I used both commands by giving full path ( ex: /home/[my user name]/.local/bin/sockeye-prepare-data) with necessary parameters , I got below error message:

[my user name]@[server]:~/directory1/sockeye$ cat 76154.out
/usr/bin/python: Import by filename is not supported.
/usr/bin/python: Import by filename is not supported.

### 2) git clone https://github.com/awslabs/sockeye.git

when I cloned their repository, files like prepare_data.py and train.py were present in **/home/[my user name]/sockeye**. But still, I got following error message when I used both commands by giving full path (ex: /home/[my user name]/sockeye/sockeye.prepare_data) with all the necessary parameters:

[my user name]@[server]:~/directory1/sockeye$ cat 76155.out
/usr/bin/python: Import by filename is not supported.
/usr/bin/python: Import by filename is not supported.

### 3) CUDA_VERSION

I know, there is an option to install using CUDA_VERSION but as it is a distributed system and for each job GPUs are allotted randomly , I am not pretty sure how to follow this.

I request you to guide me what am I doing wrong.

**Comment by bricksdont** [comment]
What happens if you call Sockeye as follows?

python -m sockeye.train

Just cloning the Github repo does not install Sockeye: you still have to use pip to install from your local copy of the files.

What do you mean by installing using CUDA_VERSION? CUDA_VERSION is a Unix environment variable, you cannot install Sockeye "with" CUDA_VERSION. CUDA is a dependency of Mxnet (which is a dependency of Sockeye). 

On a cluster system you perhaps have several versions of CUDA available. When installing Sockeye, you already need to know which version of CUDA you will use Sockeye with.

**Comment by MrRaghav** [comment]
Hello, thank you for replying me. Please find the details in following points:

Before replying to your questions, I uninstalled sockeye and re-installed it to confirm if I am still getting the error.

1) **Installation**

      pip3 install sockeye
      _output:_ Successfully installed sockeye-2.1.7 with other libraries

2) **Running commands**

_command1:_   export PYTHONPATH="/home/[my user name]/.local/lib/python3.7/site-packages/sockeye"

_command2:_   python3 -m sockeye.prepare_data -s directory1/training.BPE.de -t directory1/training.BPE.en -o directory1/trained_data --use-cpu

_command3:_   python3 -m sockeye.train -d directory1/trained_data  -vs directory1/val.BPE.de  -vt directory1/val.BPE.en --max-seq-len 60   --decode-and-evaluate 500  -o directory1/model --use-cpu

But, the error I'm getting now is:

**Illegal instruction**

For this, I checked https://github.com/awslabs/sockeye/issues/692 , but it was with (core dumped) without any solution.


3) I know that I need to build and install after cloning a git repo but I don't have privilege. So I have dropped this idea.

4) Actually, before posting it as an issue, I checked following blog on AWS: https://aws.amazon.com/blogs/machine-learning/train-neural-machine-translation-models-with-sockeye/

   It says that we can install by specifying CUDA version but, when I tried command mentioned there:
   **pip3 install sockeye --no-deps numpy mxnet-cu80==0.10.0**
   and ran following command:
   sockeye prepare data: python3 -m sockeye.prepare_data -s parallel/train.BPE.hi -t parallel/train.BPE.en -o parallel/train_data

   it gave me below error:

   **OSError: libcudart.so.8.0: cannot open shared object file: No such file or directory**

    Then, I thought of not using this way.

5) Actually, I access that Linux server remotely with many other users. Also, I am allowed to submit a job on scheduler which randomly allots GPUs for submitted job. This is why I called it distributed system. But, I don't think it has any significance in this situation.
   

I am not sure what was missed in installation. Although, I have followed every mentioned step.

**Comment by bricksdont** [comment]
"with other libraries" is part of the output of running pip? Please paste the output of:

pip3 freeze | grep mxnet

What device would you like to train on: CPU (will be quite slow) or GPU? If GPU, to move forward, you would need to find out which CUDA version is available on your system. Then follow the instructions here:

https://awslabs.github.io/sockeye/setup.html

It can be helpful to start installing libraries in a clean environment, such as a new Python virtualenv:

    # if the command "virtualenv" is not available
    pip3 install virtualenv

    # create a new virtualenv
    virtualenv -p python3 venv

    # activate env
    source venv/bin/activate

    # install libraries as usual
    pip install (...)

> I know that I need to build and install after cloning a git repo but I don't have privilege. So I have dropped this idea.

You do not need root privileges to install Sockeye. You can either 1) use the pip option `--user` or 2) work in a virtualenv (see above).

> Actually, before posting it as an issue, I checked following blog on AWS: https://aws.amazon.com/blogs/machine-learning/train-neural-machine-translation-models-with-sockeye/

The blog you are referring to is 3 (!) years old - you cannot expect it to contain up-to-date information (it does not). The command you pasted from the blog installs MXNet version 0.10.0 (very outdated) and assumes that CUDA 8.0 is installed (probably not available on your system).

**Comment by MrRaghav** [comment]
Hello,
Thank you for these suggestions. Please find the steps performed by me in following points:

### 1)  pip freeze command was ran to get following output:

   _[username]@[server]:~/username/sockeye$ pip3 freeze | grep mxnet
   mxnet==1.6.0
   mxnet-mkl==1.6.0_

### 2) CUDA
 
 I don't think CUDA  is available in this server. I ran following commands to confirm the same.

   _[myuserid]@[server]:~$ cat /proc/driver/nvidia/version
   cat: /proc/driver/nvidia/version: No such file or directory_

   _[myuserid]@[server]:~$ nvcc -V
   -bash: nvcc: command not found_

   _[myuserid]@[server]:~$ /usr/local/cuda/bin/nvcc --version
   -bash: /usr/local/cuda/bin/nvcc: No such file or directory_

   _[myuserid]@[server]:~$ nvidia-smi
   -bash: nvidia-smi: command not found_

   _[myuserid]@[server]:~$ whereis cuda
   cuda:_

There is no cuda directory available in /usr/local/. Perhaps, this means, that the options available in https://awslabs.github.io/sockeye/setup.html to use CUDA won't work here.

### 3) virtual environment

I created a virtual environment and installed sockeye using 

_(virEnv1) [myuserid]@[server]:~/myuserid/virtualEnvs$ pip3 install sockeye
Collecting sockeye_

Then, I found following sockeye related files installed in the bin directory of my virtual environment:

_(virEnv1) [myuserid]@[server]:~/myuserid/virtualEnvs/virEnv1/bin$ ls -lrt
total 4788
-rwxr-xr-x 1 myuserid users     242 Jun 30 14:44 sacrebleu
-rwxr-xr-x 1 myuserid users     268 Jun 30 14:44 sockeye-autopilot
-rwxr-xr-x 1 myuserid users     248 Jun 30 14:44 sockeye-average
-rwxr-xr-x 1 myuserid users     251 Jun 30 14:44 sockeye-embeddings
-rwxr-xr-x 1 myuserid users     249 Jun 30 14:44 sockeye-evaluate
-rwxr-xr-x 1 myuserid users     259 Jun 30 14:44 sockeye-extract-parameters
-rwxr-xr-x 1 myuserid users     255 Jun 30 14:44 sockeye-init-embed
-rwxr-xr-x 1 myuserid users     248 Jun 30 14:44 sockeye-lexicon
-rwxr-xr-x 1 myuserid users     253 Jun 30 14:44 sockeye-prepare-data
-rwxr-xr-x 1 myuserid users     249 Jun 30 14:44 sockeye-quantize
-rwxr-xr-x 1 myuserid users     247 Jun 30 14:44 sockeye-rerank
-rwxr-xr-x 1 myuserid users     246 Jun 30 14:44 sockeye-score
-rwxr-xr-x 1 myuserid users     246 Jun 30 14:44 sockeye-train
-rwxr-xr-x 1 myuserid users     250 Jun 30 14:44 sockeye-translate
-rwxr-xr-x 1 myuserid users     246 Jun 30 14:44 sockeye-vocab_

Also, I can see following version of mxnet:

_(virEnv1) [myuserid]@[server]:~/myuserid/virtualEnvs/virEnv1$ pip3 freeze | grep mxnet
mxnet-mkl==1.6.0_

After this, I checked all the libraries installed in virtual environment, as follows:

_(virEnv1) [myuserid]@[server]:~/myuserid/virtualEnvs/virEnv1$ pip3 list
Package       Version
certifi       2020.6.20
chardet       3.0.4
graphviz      0.8.4
idna          2.10
mxnet-mkl     1.6.0
numpy         1.19.0
pip           20.1.1
pkg-resources 0.0.0
portalocker   1.7.0
PyYAML        5.3.1
requests      2.24.0
sacrebleu     1.4.3
setuptools    47.3.1
sockeye       2.1.7
typing        3.7.4.1
urllib3       1.25.9
wheel         0.34.2_

Moreover, I can see **whereis** command is able to find the related files in the virtual environment:

_(virEnv1) [myuserid]@[server]:~/myuserid/virtualEnvs/virEnv1$ whereis sockeye-prepare-data
sockeye-prepare-data: /myuserid/virtualEnvs/virEnv1/bin/sockeye-prepare-data_

_(virEnv1) [myuserid]@[server]:~/myuserid/virtualEnvs/virEnv1$ whereis sockeye-train
sockeye-train: /myuserid/virtualEnvs/virEnv1/bin/sockeye-train_

But, still, when I ran following command, as suggested in the 3rd last line of the following website: https://awslabs.github.io/sockeye/setup.html, it gave error.

_(virEnv1) [myuserid]@[server]:~/myuserid/virtualEnvs/virEnv1$ sockeye-prepare-data -s training.BPE.de -t training.BPE.en -o trained_data_
**Illegal instruction**


### 4) referred blog
Thank you for highlighting that it is 3 years old. I overlooked it.


Till now, I am not sure what did I miss in the steps mentioned.

**Comment by bricksdont** [comment]
> mxnet==1.6.0
> mxnet-mkl==1.6.0

This shows there are two different versions of mxnet installed at the same time: that can lead to problems. Always uninstall libraries before installing a different version.

> I don't think CUDA is available in this server.

This is my last attempt to explain this :-)

If you are on a cluster system, it is likely that you are logged in on a small login node. The login node itself does not have libraries or resources available to use Sockeye. You seem to hint at this yourself, saying that you have to submit jobs (e.g. with SLURM) that are then run on a different instance.

The question is not whether CUDA is available in the place where you submit jobs from, you need to know if CUDA is available in the environment that submitted jobs will run in, and how to specify to the scheduler that CUDA is needed. You probably need to read documentation of this particular cluster system or check with your admin.

--------

You did not answer my question: What device would you like to train on: CPU (will be quite slow) or GPU? If GPU, the correct way to install Sockeye is **with one of the requirements files**, as explained here:

https://awslabs.github.io/sockeye/setup.html

**Comment by MrRaghav** [comment]
Hello,
Thank you for looking into this issue and sparing your time in guiding me. This issue was fixed by the server's Admin when he installed Sockeye to one of the GPUs. 

However, I tried to install it in my personal Google Cloud Platform (GCP) and sockeye.prepare_data command worked okay there. So, it seems there was installation issue with the Server.

I will close this issue now.
