### ISSUE TITLE
Int8 Inference Problems

### ISSUE THREAD

**Issue by graftim** [awslabs/sockeye#838]
Hi, I have trained a new model (amp enabled) with sockeye version 2.1.7 and have tried to use it for int8 inference. 
When I use it to decode on a gpu, everything works as intended, and when I decode on cpu in the sockeye cpu container it works as long as  `--dtype` is `float32`. But when I use `--dtype int8`, over half of the translated lines is empty, and the rest are just interpunction symbols with some random words. If I use a topk-lexicon as described [here](https://github.com/awslabs/sockeye/tree/master/sockeye_contrib/docker), then the output is 3000 completely empty lines.

When translating on cpu where the output is fine (dtype float32), I get this UserWarning: 
```
opt/sockeye/sockeye/decoder.py:259: UserWarning: Parameter decoder_transformer_4_att_enc_k2h_weight,
decoder_transformer_2_att_enc_k2h_weight, decoder_transformer_3_att_enc_k2h_weight,
decoder_transformer_3_att_enc_v2h_weight, decoder_transformer_0_att_enc_v2h_weight,
decoder_transformer_1_att_enc_k2h_weight, decoder_transformer_1_att_enc_v2h_weight,
decoder_transformer_5_att_enc_k2h_weight, decoder_transformer_0_att_enc_k2h_weight,
decoder_transformer_5_att_enc_v2h_weight, decoder_transformer_4_att_enc_v2h_weight,
decoder_transformer_2_att_enc_v2h_weight is not used by any computation. Is this intended?
```

And when I use dtype int8, the warning also includes the scaling parameters:
```
/opt/sockeye/sockeye/decoder.py:259: UserWarning: Parameter decoder_transformer_1_att_enc_k2h_weight,
decoder_transformer_5_att_enc_k2h_weight, decoder_transformer_4_att_enc_k2h_weight,
decoder_transformer_4_att_enc_v2h_weight, decoder_transformer_1_att_enc_v2h_weight,
decoder_transformer_3_att_enc_k2h_weight, decoder_transformer_2_att_enc_v2h_weight,
decoder_transformer_5_att_enc_v2h_scaling, decoder_transformer_0_att_enc_v2h_scaling,
decoder_transformer_2_att_enc_k2h_weight, decoder_transformer_3_att_enc_v2h_scaling,
decoder_transformer_2_att_enc_k2h_scaling, decoder_transformer_0_att_enc_k2h_scaling,
decoder_transformer_5_att_enc_v2h_weight, decoder_transformer_1_att_enc_k2h_scaling,
decoder_transformer_5_att_enc_k2h_scaling, decoder_transformer_0_att_enc_v2h_weight,
decoder_transformer_3_att_enc_k2h_scaling, decoder_transformer_2_att_enc_v2h_scaling,
decoder_transformer_0_att_enc_k2h_weight, decoder_transformer_3_att_enc_v2h_weight,
decoder_transformer_4_att_enc_k2h_scaling, decoder_transformer_1_att_enc_v2h_scaling,
decoder_transformer_4_att_enc_v2h_scaling is not used by any computation. Is this intended?
```

I have tried quantizing the model before the inference and also using the trained model and quantization at runtime, but the results remain the same. Is this a known problem or am I making some kind of rookie-mistake?

Thanks a lot!

**Comment by graftim** [comment]
I have now upgraded to sockeye 2.1.10. This solved the problem and int8-decoding now works perfectly fine, as long as I don't use the lexicon. I have now inspected the lexicon, and it seems like there was a mishap when creating the lexicon, as I only get
 `Output: n=4 <pad>(0) <unk>(1) <s>(2) </s>(3)`, no matter which input I use. Has anyone ever run into this problem?

**Comment by fhieber** [comment]
Hi @graftim 
thanks for reporting the issue and glad to hear that the latest version fixes the int8 decoding issues. Could you document what steps you followed to create the lexicon and paste the logfiles? Thank you!

**Comment by graftim** [comment]
Hi @fhieber 
I followed the instructions [here](https://github.com/awslabs/sockeye/tree/master/sockeye_contrib/fast_align), but I have now noticed that something must have gone wrong during `./lextable.sh`, as the lex.out was completely empty. Sadly, I have not saved those logs so I am now running it again and I'll comment here if the problem persists. 
Thank you :)

**Comment by graftim** [comment]
So I let it run again but lex.out was still empty.
I started the command in the following way:
`nohup ./lex_table.sh preprocessed.train.de .preprocessed.train.en lex.out > nohup.out &`
In nohup.out, there is nothing exceptional to me, here is a snippet of it, I removed all the dotted lines and the iterations in between the first and the last one.

```
ARG=i
ARG=v
ARG=d
ARG=o
ARG=p
ARG=t
INITIAL PASS 
expected target length = source length * 0.991001
ITERATION 1
  log_e likelihood: -4.24516e+10
  log_2 likelihood: -6.12447e+10
     cross entropy: 29.8974
        perplexity: 1e+09
      posterior p0: 0.08
 posterior al-feat: -0.166666
       size counts: 32299
[...]
ITERATION 5 (FINAL)
  log_e likelihood: -9.32308e+09
  log_2 likelihood: -1.34504e+10
     cross entropy: 6.56596
        perplexity: 94.7439
      posterior p0: 0
 posterior al-feat: 0
       size counts: 32299
conditional probabilities: /lexicon
```

**Comment by fhieber** [comment]
Hi @graftim,
Is your data (preprocessed.train.de .preprocessed.train.en) special in some way? It seems that `lex_table.sh` is using a fairly large value for the beam_threshold (-t). Maybe this is causing the resulting ttable to be empty? Can you try without the `-t` argument?

**Comment by graftim** [comment]
Hi @fhieber,
The data is pretty standard data with sentencepiece subwords. I now removed the -t  in `lex_table.sh` but the output is still empty.
```
ARG=i
ARG=v
ARG=d
ARG=o
ARG=p
INITIAL PASS 
expected target length = source length * 0.991001
ITERATION 1
  log_e likelihood: -4.24516e+10
  log_2 likelihood: -6.12447e+10
     cross entropy: 29.8974
        perplexity: 1e+09
      posterior p0: 0.08
 posterior al-feat: -0.166666
       size counts: 32299
[...]
ITERATION 5 (FINAL)
  log_e likelihood: -9.32308e+09
  log_2 likelihood: -1.34504e+10
     cross entropy: 6.56596
        perplexity: 94.744
      posterior p0: 0
 posterior al-feat: 0
       size counts: 32299
conditional probabilities: /lexicon
```

**Comment by graftim** [comment]
Okay nevermind @fhieber, this was a dumb mistake on my part. The problem was that the docker container did not have permission to write. As soon as I changed that, it worked like a charm. Sorry for the inconveniences caused.

**Comment by fhieber** [comment]
Glad to hear its resolved :)
