### ISSUE TITLE
Training errors

### ISSUE THREAD

**Issue by i55code** [awslabs/sockeye#839]
Hi, 

I work on a GPU memory of 8GB.  I have a lot of difficulty with training with sockeye: 

1. I train a network of layer 1 RNN of 512 nodes batchsize 64 (I reduce all params to be extremely small), but it gives the error of GPU memory problem. (But my machine used to train RNN model with 4 layers using sockeye on 1024 nodes and batchsize 512 without any problem with other dataset before). 
**mxnet.base.MXNetError: Traceback (most recent call last):
  File "src/operator/tensor/.././../common/../operator/mxnet_op.h", line 1113
Name: Check failed: err == cudaSuccess (2 vs. 0) : mxnet_generic_kernel ErrStr:out of memory**

2. When I reduce the batchsize to 32, it gives the error. As a result, I cannot decrease batchsize to make my model fit the GPU memory: 
**sockeye.utils.SockeyeError: Word batch size must cover sequence lengths for all buckets: (51 > 50)**

3. If I reduce the params even smaller, here is another error that I face: 
**sockeye.utils.SockeyeError: Empty target validation sentence.**

Please let me know what are some of the ways I can do as next steps. Thanks. 

Thanks!

**Comment by fhieber** [comment]
Hi @i55code,

There are several options to reduce memory consumption of model training, the most impactful being the batch size. By default, Sockeye uses word-based batching. If you reduce word-based batch size too much, you are going to exclude too many training samples. You could instead use `--batch-type sentence` and set `--batch-size` to the number of sentences you want to have in one batch. This should allow you to reduce it to arbitrarily small numbers (including 1).

Regarding parameter sizes: you can also try reducing the embedding size and change the attention type to `dot`.

**Comment by i55code** [comment]
Hi @fhieber , 

Thank you! I used batch-type sentence and used batch size 1, however, there is still the out of memory error: 

mxnet.base.MXNetError: Traceback (most recent call last):
  File "src/operator/tensor/.././../common/../operator/mxnet_op.h", line 1113
Name: Check failed: err == cudaSuccess (2 vs. 0) : mxnet_generic_kernel ErrStr:out of memory

Please let me know what you think. Thanks!

**Comment by fhieber** [comment]
Hi @i55code that is very suspicious and seems unrelated to sockeye. Can you allocate any GPU memory using mxnet on this instance?
For example do something like:
```python
ipython
import mxnet as mx
a = mx.nd.ones((100,100), ctx=mx.gpu())
```
and then increase the size of the allocated array?

**Comment by i55code** [comment]
Hi @fhieber , thank you! Here is the limit : 

>>> a = mx.nd.ones((100,100), ctx=mx.gpu())
>>> a = mx.nd.ones((1000,1000), ctx=mx.gpu())
>>> a = mx.nd.ones((10000,10000), ctx=mx.gpu())
>>> a = mx.nd.ones((100000,100000), ctx=mx.gpu()) 
mxnet.base.MXNetError: Traceback (most recent call last):
  File "src/operator/numpy/../tensor/init_op.h", line 309
MXNetError: Check failed: param_shape.Size() < (int64_t{1} << 31) - 1 (10000000000 vs. 2147483647) : [InitShape-input] Size of tensor you are trying to allocate is larger than 2^31 elements. Please build with flag USE_INT64_TENSOR_SIZE=1

Feel free to let me know what you think might be the cause, and what are some good next steps. Thanks!

**Comment by i55code** [comment]
This problem went away after I reinstalled system, and GPUs. I know it is not ideal, but now this issue went away. Thanks a lot!
