### ISSUE TITLE
fairseq support

### ISSUE THREAD

**Issue by feiyulv** [awslabs/sockeye#84]
Is sockeye going to support facebook's fairseq and goolge's tensor2tensor?

**Comment by tdomhan** [comment]
we don't currently have any convolutional decoder. For an attention is all you need style model check out this WIP branch: https://github.com/awslabs/sockeye/pull/62

**Comment by fhieber** [comment]
For reference, Sockeye now supports both transformer models and the 'fairseq' approach of fully convolutional seq2seq models.
