### ISSUE TITLE
Error in mxnet when building sockeye cpu container.

### ISSUE THREAD

**Issue by graftim** [awslabs/sockeye#846]
Hello everyone ;)
I have issues when building new sockeye containers as they are provided in sockeye_contrib/docker. When building new images without cache, when I run `python -m sockeye.translate` I get the following Error message:
```
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/sockeye/sockeye/translate.py", line 28, in <module>
    from sockeye.lexicon import TopKLexicon
  File "/opt/sockeye/sockeye/lexicon.py", line 26, in <module>
    from . import arguments
  File "/opt/sockeye/sockeye/arguments.py", line 26, in <module>
    from . import data_io
  File "/opt/sockeye/sockeye/data_io.py", line 36, in <module>
    from . import vocab
  File "/opt/sockeye/sockeye/vocab.py", line 25, in <module>
    from . import utils
  File "/opt/sockeye/sockeye/utils.py", line 756, in <module>
    def log_parameters(params: mx.gluon.ParameterDict):
AttributeError: module 'mxnet.gluon' has no attribute 'ParameterDict'
```
I think the problem is that the intgemm mxnet is not fixed and that there might be an issue with the current intgemm mxnet version (Commit 528b77d4393c011f8f3723904608e17ba6c79a0d), as this was the only difference I could find when I compared the installs in working containers.
Also when I built the container in the new sockeye version I was still able to get it running when older build stages were cached, but when I built it with `--no-cache`, I had the same intgemm mxnet commit hash and it didn't work anymore.

Best wishes
Tim

**Comment by fhieber** [comment]
@mjdenkowski can you take a look?

**Comment by graftim** [comment]
I think the problem is in the `Dockerfile.cpu`, where mxnet is cloned. 
```
ENV MXNET_COMMIT=b02dbc3387c38392b1be1570ba1fa7bfe1673d61
RUN cd /opt && \
    git clone https://github.com/kpuatamazon/incubator-mxnet.git mxnet && \
    cd mxnet && \
    git checkout ${MXNET_COMMIT} && \
    git checkout intgemm && \
    git submodule init && \
    git submodule update --recursive
```

I don't get why first the mxnet commit is checked out and then again the intgemm branch. I was able to fix it with checking out a recent commit (7a20b91e6986fd774d85c838c3465d10391a7d82) after `git checkout intgemm && \`. I was then able to decode on CPU with `--dtype int8`, which should mean that i have an intgemm verison installed, correct?

**Comment by graftim** [comment]
I have now tested it again with removing `git checkout intgemm` from the Dockerfile and leaving the rest unchanged and it seems to work. I was able to build the container and I could decode with int8 and the installed mxnet version in the container according to pip3 freeze is now `-e git+https://github.com/kpuatamazon/incubator-mxnet.git@b02dbc3387c38392b1be1570ba1fa7bfe1673d61#egg=mxnet&subdirectory=python`.

**Comment by mjdenkowski** [comment]
Thanks for reporting this issue!  Your assessment is correct that the second checkout line is an error in the Dockerfile.

We've added commit 1ca2788948d92e678a796b7cf346aee5727d3a43 that credits you with the fix.
