### ISSUE TITLE
softmax-temperature

### ISSUE THREAD

**Issue by wangpeng138375** [awslabs/sockeye#857]
Why there is no "--softmax-temperature“  and "--beam-prune" parameters in Sockeye version 2.1.17 ? The parameter of “--sample”  and "constraints" seem to conflict， as the results of sampling with constraints tend to similar with each other. Why?

**Comment by fhieber** [comment]
Hi @wangpeng138375,
With Sockeye 2 we rewrote large parts of the codebase, concentrating on the most important features. If you have a use case for missing features such as softmax-temperature, we'd welcome a pull request to add it back.

Could you clarify what you mean with "sample" and "constraints" conflicting?

**Comment by wangpeng138375** [comment]
"sample" and "constraints" conflicting means when set "constraints" in input JSON and use sample method to generate multi hypotheses,  the hypotheses tend to be similar or same with high probability.  I don't know why.

And , The DBA doesn't guarantee the "constraints" must appear , but the GBS(grid beam search) dose , am i right？

**Comment by fhieber** [comment]
@davvil @mjpost Can one of you comment on interaction between constrained decoding and sampling?

Hi @wangpeng138375, are you referring to this method: #843?

**Comment by mjpost** [comment]
In Sockeye 1, constraints and sampling are mutually exclusive. Sampling randomly generates each token, while constrained decoding uses a variant of beam search to ensure the tokens appear. 

Constrained decoding with DBA *does* guarantee the tokens will appear, just as with GBS. The constraints are hard constraints.

**Comment by wangpeng138375** [comment]
@fhieber Yes！Thanks.
@mjpost When the constraint contains multi tokens seperated by space, take this JSON string of `{ 'text': 'This is a test .', 'constraints': ['constr@@ aint'}`  as example, I found some hypotheses in one beam have no "constr@@ aint" 。This phenomenon is more obvious under the condition of "avoid"，is this phenomenon right or normal?

**Comment by mjpost** [comment]
What do you mean "in one beam"? Not all hypotheses will have covered all constraints. For negative constraints, the phrase should not be present.

**Comment by wangpeng138375** [comment]
I mean, such as beam_size=10 , not all 10 hypotheses cover all constraints. and not  all 10 hypotheses avoid all negative constraints. especially when there is two or more tokens in one constraints or one negative constraints.

**Comment by mjpost** [comment]
Yes, this is by design. Because it is impossible to know where to place the constraints, DBA divides the beam into bins that reflect hypotheses covering different numbers of constraints.

In the negative setting, however, constraints should never be present in the beam.

**Comment by wangpeng138375** [comment]
Thanks for your reply . I will do more test to find the reason why this problem occur : `'avoid': ['constr@@']` with one token works , `'avoid': ['constr@@ aint']` with two tokens probably fails. Thanks!

**Comment by mjpost** [comment]
It may be a bug in the implementation.

**Comment by fhieber** [comment]
#869 re-introduces softmax temperature.
