### ISSUE TITLE
Fix parameters:  encoder/decoder

### ISSUE THREAD

**Issue by i55code** [awslabs/sockeye#864]
Hi Sockeye team,  is there a function of fixing parameters already implemented? For example fix encoder while training decoder. 
 Thanks!

**Comment by fhieber** [comment]
Hi @i55code,

take a look at this cmdline flag: https://github.com/awslabs/sockeye/blob/master/sockeye/arguments.py#L987 and its choices here: https://github.com/awslabs/sockeye/blob/master/sockeye/constants.py#L387

For fixing all parameters except decoder parameters, you could specify `--fixed-param-strategy all_except_decoder`.

**Comment by i55code** [comment]
Thank you so much, @fhieber ! This is very helpful!
