### ISSUE TITLE
Purge and reinstall sockeye 

### ISSUE THREAD

**Issue by i55code** [awslabs/sockeye#870]
Hi, may I ask what is the best way to purge previous installation of sockeye and reinstall it? Thanks!

**Comment by fhieber** [comment]
That depends on how you installed Sockeye. If you installed via `pip`, `pip uninstall sockeye` would do.

**Comment by i55code** [comment]
@fhieber , thank you! If it is installed through source, what is the best way to purge it? Thanks!
