### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by i55code** [awslabs/sockeye#871]
I have been using Sockeye for sometime in my old machine. But I have some difficulty resolving a previous thread on installing sockeye for a new machine (cuda 10.2, Nvidia 440, Ubuntu 18.06 , mxnet 10.2), so I tried to install the docker version.

1. This is the issue by installing through the traditional way: 
$ pip install sockeye --no-deps -r requirements/requirements.gpu-cu102.txt 
  Could not find a version that satisfies the requirement mxnet-cu102mkl==1.6.0 (from -r requirements/requirements.gpu-cu102.txt (line 2)) (from versions: 1.6.0.post0)
No matching distribution found for mxnet-cu102mkl==1.6.0 (from -r requirements/requirements.gpu-cu102.txt (line 2))

2.I tried to fix the previous issue by changing  requirements/requirements.gpu-cu102.txt to "mxnet-cu102mkl==1.6.0.post0" and get past the installation, however training also shows error: 
  File "/home/.local/lib/python3.6/site-packages/sockeye/train.py", line 221, in create_checkpoint_decoder
    hybridize=hybridize)
  File "/home/.local/lib/python3.6/site-packages/sockeye/checkpoint_decoder.py", line 104, in __init__
    "Empty target validation sentence.")
  File "/home/.local/lib/python3.6/site-packages/sockeye/utils.py", line 135, in check_condition
    raise SockeyeError(error_message)
sockeye.utils.SockeyeError: Empty target validation sentence.

3. This is the docker error: 
python3 sockeye_contrib/docker/build.py gpu 
ERROR: Could not find a version that satisfies the requirement mxnet-cu101==1.6.0 (from versions: 1.4.1, 1.5.0, 1.5.1, 1.5.1.post0, 1.6.0.post0, 1.7.0)
ERROR: No matching distribution found for mxnet-cu101==1.6.0

May you point to the next step?

**Comment by fhieber** [comment]
Hi @i55code, 
one issue is that the [Dockerfile](https://github.com/awslabs/sockeye/blob/master/sockeye_contrib/docker/Dockerfile.gpu#L72) tries to install an MXNet version that does not exist. That line should say `ENV MXNET_VERSION=1.6.0.post0`.

Your second issue is that your validation contains an empty line.

**Comment by i55code** [comment]
Thank you @fhieber , the docker runs smoothly now. Thanks!
