### ISSUE TITLE
Translation outputs warning: Parameters not used by any computation

### ISSUE THREAD

**Issue by bricksdont** [awslabs/sockeye#873]
I am seeing the following warning in the translation log file:

> /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/decoder.py:262: UserWarning: Parameter decoder_transformer_5_att_enc_v2h_weight, decoder_transformer_4_att_enc_v2h_weight, decoder_transformer_3_att_enc_k2h_weight, decoder_transformer_1_att_enc_k2h_weight, decoder_transformer_2_att_enc_k2h_weight, decoder_transformer_0_att_enc_v2h_weight, decoder_transformer_1_att_enc_v2h_weight, decoder_transformer_4_att_enc_k2h_weight, decoder_transformer_5_att_enc_k2h_weight, decoder_transformer_2_att_enc_v2h_weight, decoder_transformer_3_att_enc_v2h_weight, decoder_transformer_0_att_enc_k2h_weight is not used by any computation. Is this intended?

As far as I can see, those weights are for [attention to encoder states in the decoder](https://github.com/awslabs/sockeye/blob/master/sockeye/transformer.py#L166). I expected that they would be used in vanilla beam search translation.

What does the warning mean exactly and do I have to take action?

I am glad to provide more information if needed.

**Comment by fhieber** [comment]
That warning is expected (it comes from Gluon) and is because we do cache the computation that these parameters are involved in across beam search time steps. Nothing to worry about.

**Comment by bricksdont** [comment]
I see, that makes a lot of sense, thanks Felix.
