### ISSUE TITLE
Low GPU-usage during training

### ISSUE THREAD

**Issue by graftim** [awslabs/sockeye#874]
Hi, with sockeye2, the GPU-Util in gpustat or nvidia-smi is often low. e.g. as follows:
```
[0] Quadro RTX 8000  | 50'C,   0 % | 44481 / 48571 MB
[1] Quadro RTX 8000  | 51'C,   0 % | 44705 / 48571 MB
[2] Quadro RTX 8000  | 45'C,   4 % | 44743 / 48571 MB
[3] Quadro RTX 8000  | 50'C,   3 % | 44313 / 48571 MB
[4] Quadro RTX 8000  | 44'C,   7 % | 43667 / 48571 MB
[6] Quadro RTX 8000  | 51'C,  46 % | 44745 / 48571 MB
[7] Quadro RTX 8000  | 48'C,   7 % | 45187 / 48571 MB
```
The process is run via `sockeye.train` and not with `horovodrun`. Is this behaviour expected or are there certain hyperparameters that I have set in a very unoptimized fashion?

**Comment by bricksdont** [comment]
Could you please share the training command you have used? Thanks.

**Comment by graftim** [comment]
Here you go:
```
python -m sockeye.train \
    --device-ids 0 1 2 3 4 5 6 7 \
    --disable-device-locking \
    --encoder=transformer \
    --decoder=transformer \
    --num-layers=6:6 \
    --transformer-model-size 512 \
    --transformer-attention-heads=8 \
    --transformer-feed-forward-num-hidden 8192 \
    --transformer-positional-embedding-type=fixed \
    --transformer-preprocess=n \
    --transformer-postprocess=dr \
    --transformer-dropout-attention=0.1 \
    --transformer-dropout-act=0.1 \
    --transformer-dropout-prepost=0.1 \
    --weight-tying-type=src_trg_softmax \
    --weight-init=xavier \
    --weight-init-scale=3.0 \
    --weight-init-xavier-factor-type=avg \
    --num-embed 512 \
    --optimizer adam \
    --optimized-metric=perplexity \
    --label-smoothing=0.1 \
    --gradient-clipping-threshold=-1 \
    --initial-learning-rate=0.0002 \
    --learning-rate-reduce-num-not-improved=8 \
    --learning-rate-warmup 16000 \
    --learning-rate-reduce-factor=0.7 \
    --learning-rate-scheduler-type=plateau-reduce \
    --max-num-checkpoint-not-improved=32 \
    --batch-type=word \
    --batch-size 20000 \
    --amp \
    --bucket-width 8 \
    --batch-sentences-multiple-of 8 \
    --pad-vocab-to-multiple-of 8 \
    --omp-num-threads 8 \
    --env=OMP_NUM_THREADS=8 \
    --checkpoint-interval=5000 \
    --max-num-epochs 10 \
    --keep-last-params=5 \
    --max-seq-len=287
```

**Comment by bricksdont** [comment]
I'm not sure what the cause for this is, but answers to the following might lead to an answer:

- Are you using `sockeye.prepare` before training?
- What's the size of the data set, roughly? How many batches?
- What's the CPU usage during training? How many hyperthreads (or actual cores)?
- What happens if you train only on four "adjacent" devices, i.e. `0, 1, 2, 3` or `4, 5, 6, 7`?

**Comment by graftim** [comment]
Hi @bricksdont and thanks for your suggestions!

> Are you using sockeye.prepare before training?

Yes I am, and I used the following options for this training: 
```
--pad-vocab-to-multiple-of 8 \
    --max-processes 8 \
    --bucket-width 8 \
    --shared-vocab \
    --max-seq-len "287:95" 
```

> What's the size of the data set, roughly? How many batches?

`num_sents` in data.config is 137'143'533 and one epoch consists of ~167'000 batches

> What's the CPU usage during training? How many hyperthreads (or actual cores) on the machine?

CPU-Usage is nowhere near max, and there are 20 physical cores (40 hyperthreads) available.

> What happens if you train only on four "adjacent" devices, i.e. `0, 1, 2, 3 `or `4, 5, 6, 7`?

This is quite interesting, with 2 different trainings at the same time, GPU-Usage is still not at its max, but by eyeballing the average GPU-usage seems to be higher (~60% per GPU it seems)

**Comment by bricksdont** [comment]
Just a hunch, perhaps 8 threads are not enough to keep all GPUs busy. The CPU usage is not expected to be at max for 40 cores, since you set `OMP_NUM_THREADS` to 8. Can you please check if CPU load of the Sockeye process is more or less 800% for 8 GPUs? And then try using more CPU threads.

**Comment by graftim** [comment]
Thanks a lot, I could very well imagine that this is the problem. The trainings that are currently running on 4 GPUs each use around 600-700% CPU each, so it seems that  `OMP_NUM_THREADS` 8 is not enough to saturate all 8 GPUs. I will not be able to verify it until Thursday, but I will post the results here asap. If this turns out to be the problem, the help-text for `--omp-num-threads` should maybe be adjusted, as it currently recommends to set it to the number of GPUs. Or is this usually enough, but just not on cards with a lot of VRAM?

**Comment by graftim** [comment]
Hi again, so we tested it again and set `OMP_NUM_THREADS` to 20 but it did not make a difference. Whether we use it set to 8 or to 20, total CPU-Usage of the sockeye process is around 1300% in both cases, which is quite strange given that in the former case it should be at most 800%.

**Comment by bricksdont** [comment]
Thanks for testing, increasing `OMP_NUM_THREADS` does not solve the problem it seems.

- You could look into other env variables related to threads (https://mxnet.apache.org/versions/1.7/api/faq/env_var.html), for instance `MXNET_GPU_WORKER_NTHREADS`. I am not sure what exactly this variable does.
- It would perhaps be helpful to ask in the Mxnet forum: https://discuss.mxnet.apache.org/ to get help from someone with a deeper understanding of Mxnet, or open a Github issue in Mxnet. For the latter it would be extremely helpful if you can provide a minimal, reproducible example.

**Comment by tdomhan** [comment]
Thanks for all the suggestions Mathias! 
One more thing to try for testing purposes is to run single GPU training to see whether that get's the desired utilization on a single GPU (reducing the batch size accordingly).

**Comment by graftim** [comment]
We now tested it with one GPU and reduced the batch-size to 1/8 of the previous size, and the usage is much higher. It never drops below 70% and also, the single GPU is around 15°C hotter than in the 8 GPU-Setup, so it must be some issue with scaling to multiple GPUs.

**Comment by fhieber** [comment]
Using multiple GPU devices on a single host with MXNet currently seems to not scale well. I would suggest setting up multi-gpu training with Horovod instead.
