### ISSUE TITLE
fine tune the model with new data

### ISSUE THREAD

**Issue by wangpeng138375** [awslabs/sockeye#876]
Hi, I used `sockeye.prepare_data -s $source_file -t $target_file -o $train_data --shared-vocab` and  `sockeye.train -d $train_data -o old_model ............` to train a model in **old_model** directory. 

And then, how could i fine tune the **old_model** with new data , I used the same command to prepare the data: `sockeye.prepare_data -s $new_source_file -t $new_target_file -o $_new_train_data --shared-vocab` .

When I use the same command for fine tune :  `sockeye.train -d $_new_train_data -o old_model ............`, I got some error：**Mismatch in arguments for training continuation.
Differing arguments: prepared_data.
**
So, My question is : Is there any instructions for fine tune the existing model?

**Comment by tdomhan** [comment]
For fine-tuning you want to specify a new training folder `-o new_model` and pass in the parameters of the old model in through `--params old_model/params.best`. 

Hope that helps.

**Comment by wangpeng138375** [comment]
Thanks, I close it
