### ISSUE TITLE
Sockeye 2.1.16 translation -- apparent memory leak

### ISSUE THREAD

**Issue by tuglat** [awslabs/sockeye#881]
I built a sockeye 2.1.16 model, and then started using it to translate some 20M lines. After several days, it became apparent that sockeye-translate was grabbing more and more of the system memory. It now holds some 265g virtual and 228g resident memory.

My invocation looks like this:
sockeye-translate --device-ids ${myDevice} --input ${input} --output ${output} --models ${model} --omp-num-threads 8 --beam-size 12 --batch-size 20

I haven't tried to track down the source of the problem as yet.

**Comment by bricksdont** [comment]
As a temporary workaround, perhaps this is useful for you:

https://gist.github.com/bricksdont/2f5b0b0ba54997c7d622d8f8f8538dbe

It translates chunks of inputs, which means Sockeye processes will run for a shorter time and cannot accumulate that much memory.

**Comment by fhieber** [comment]
Thanks for reporting. Unfortunately, it seems that MXNet has had issues with memory leaks recently, so this could be related: https://github.com/apache/incubator-mxnet/issues?q=memory+leak
