### ISSUE TITLE
Incompatibility  >=2.1.17 vs. <=2.1.16

### ISSUE THREAD

**Issue by graftim** [awslabs/sockeye#882]
Hi everyone,

In an attempt of getting the latest and greatest with MXNet 1.7.0 I noticed that models trained with Sockeye 2.1.16 and smaller have issues when translating with Sockeye 2.1.17 and greater. When I don't change anything I receive the following error:
```
AssertionError: Parameter 'decoder.layers.0.autoregr_layer.ff_out.weight' is missing in file
'model_fixed_preprocessing_big/params.best', which contains parameters: 'output_layer.weight',
'embedding_source.factor0_weight', 'encoder.pos_embedding.weight', ..., 'decoder.layers.1.ff.ff2.bias',
'decoder.final_process.layer_norm.gamma', 'decoder.final_process.layer_norm.beta', 'output_layer.bias'. 
Set allow_missing=True to ignore missing parameters.
```

When I set `allow_missing=True`, The translation starts and finishes without throwing an Error, but the output has lots of repetitions:
Output when translating with 2.1.16:
`▁Feuer ▁gelöscht ▁in ▁einem ▁französischen ▁Chemie werk`

Output when translating with 2.1.17 or higher (with a model on 2.1.16):
`▁Feuer ▁gelöscht es ▁Feuer ▁gelöscht es ▁Feuer ▁in ▁einem ▁französischen ▁Chemie werk ▁gelöscht`

 Is there a possible fix for this or did #851 perform changes that lead to incompatibility, so that 2.1.17 should actually be 2.2.0? 

Thanks in advance

**Comment by tdomhan** [comment]
Thanks for reporting! What was the command you used for training? (specifically, did you set the `--decoder` parameter?)

**Comment by graftim** [comment]
Hi @tdomhan 

Thanks for the quick response! here are all the model-specifi parameters that were used for the training, and yes `--decoder` was set to `transformer:`
```
    --encoder=transformer \
    --decoder=transformer \
    --num-layers=20:2 \
    --transformer-model-size 1024 \
    --transformer-attention-heads=8 \
    --transformer-feed-forward-num-hidden 4096 \
    --transformer-positional-embedding-type=fixed \
    --transformer-preprocess=n \
    --transformer-postprocess=dr \
    --transformer-dropout-attention=0.1 \
    --transformer-dropout-act=0.1 \
    --transformer-dropout-prepost=0.1 \
    --weight-tying-type=src_trg_softmax \
    --weight-init=xavier \
    --weight-init-scale=3.0 \
    --weight-init-xavier-factor-type=avg \
    --num-embed 1024 \
    --optimizer adam \
    --optimized-metric=perplexity \
    --label-smoothing=0.1 \
    --gradient-clipping-threshold=-1 \
    --initial-learning-rate=0.0002 \
    --learning-rate-reduce-num-not-improved=8 \
    --learning-rate-warmup 16000 \
    --learning-rate-reduce-factor=0.7 \
    --learning-rate-scheduler-type=plateau-reduce \
    --max-num-checkpoint-not-improved=32 \
    --batch-type=word \
    --batch-size 10000 \
    --update-interval 2 \
    --amp \
    --bucket-width 8 \
    --batch-sentences-multiple-of 8 \
    --pad-vocab-to-multiple-of 8 \
    --env=OMP_NUM_THREADS=2 \
    --checkpoint-interval=5000 \
    --max-num-epochs 10 \
    --keep-last-params=5 \
    --max-seq-len=150
```

**Comment by tdomhan** [comment]
Thanks! It seems that the SSRU change inadvertently added a model incompatibility.  `allow_missing=True` will lead to some parameters being randomly initialized instead of loaded from disk, which explains the odd model behavior. Sorry for the inconvenience!

Note that you should be able to use Sockeye 2.1.16 with MXNet 1.7.0 as well (i.e. manually updating your MXNet installation).

**Comment by graftim** [comment]
Alright, thanks for investigating and for the hint!

**Comment by tdomhan** [comment]
This PR will fix the problem: https://github.com/awslabs/sockeye/pull/885

**Comment by tdomhan** [comment]
Can you check if the latest version works for you?

**Comment by graftim** [comment]
Works like a charm, thank you very much!
