### ISSUE TITLE
Question: Does change in 2.1.24 break desired behavior of --max-checkpoints?

### ISSUE THREAD

**Issue by tuglat** [awslabs/sockeye#889]
Version 2.1.24 makes the change: Make sure to write a final checkpoint when stopping with --max-updates, --max-samples or --max-num-epochs.

However, the desired behavior of the --max-checkpoints option, which piggy-backs on --max-updates (or used to), is that training will be continued for the desire number of checkpoints and then stop, but allowing training to continue in a subsequent run. The purpose of this is to allow those who must share GPU resources to give others use of scarce GPU's for a time.

Does the change described above break the desired behavior?

**Comment by tdomhan** [comment]
Hi! Thanks for raising the concern. With the update we make sure to always create a final checkpoint even when the max_updates aren't a multiple of the checkpoint_interval. For the case that max_updates is a multiple of checkpoint_interval the behavior should be exactly the same before and after the change.

Just to clarify: Are you saying in your setup with training continuation you have run into an issue after the change (if so it'd be great to know more details of your training setup, such as the exact commands used for training) or where you mainly asking whether there's an issue?

**Comment by tuglat** [comment]
I haven't yet tried 2.1.24 or above. I just saw the comments, and wondered if this implied a break w/ previous behavior. 

No, I haven't actually witnessed any problems here.
