### ISSUE TITLE
Continuing Training: Refusing to overwrite model folder as it seems to contain a trained model.

### ISSUE THREAD

**Issue by i55code** [awslabs/sockeye#892]
Hi, I have a model training that is interrupted. I want to resume training. 

when I relaunched it, it says it refuse to overwrite model folder as it seems to contain a trained model. (Which is the model that I want the new model to continue training from ) 
The whole training script is unchanged.

May you share a script of an example of continued training due to interruption?

May you share how to fix this error? Thanks!

**Comment by i55code** [comment]
I realized I did change the batch size,when I keep the batch size, the training continues as usual. Thanks.

**Comment by LiangQiqi677** [comment]
Hi, I have the same problem too. And I just run it again without changing anything and I got this error. 

Can you show me your params setting and your output_dir detail?

**Comment by tdomhan** [comment]
What's the error you are seeing? You should only see the message if you actually change training parameters.
