### ISSUE TITLE
[Question] Is there a way to have auto-batch fitting? 

### ISSUE THREAD

**Issue by sianvolta** [awslabs/sockeye#909]
From  https://github.com/awslabs/sockeye/blob/master/CHANGELOG.md#11885 and https://github.com/awslabs/sockeye/pull/662 , we understand that the auto-batching should be disable because it's slow in inference, is it possible to enable only during training? Or is it also slow during training too? 

Any pointers as to how should we go about re-implementing a working and non-slow dynamic batching?

**Comment by tdomhan** [comment]
When you refer to dynamic batching in the context of training could you clarify what you mean? Are you referring to batch sizes that automatically fill the GPU until there's no memory left?

**Comment by tdomhan** [comment]
For training the batching strategies currently are to either create batches for a given number of words or for a given number of sentences.
