### ISSUE TITLE
Upgrade to newest version of sacrebleu

### ISSUE THREAD

**Issue by bricksdont** [awslabs/sockeye#913]
Sockeye currently pins the sacrebleu dependency to an older version, `sacrebleu==1.4.10`.

I would like to install the most recent sacebleu (1.4.14 at the moment) because it introduced TER, but this breaks the Sockeye checkpoint decoder code due to backward-incompatible changes to the sacrebleu API.

Adapting those calls in Sockeye would only be a minor change, and I would like to open a PR for this.

Is there another reason for pinning the sacrebleu version to 1.4.10?

**Comment by tdomhan** [comment]
No, I think that's the only reason, namely that we want to avoid API backwards incompatabilities to be automatically pulled in. If you update and adjust the calls that sounds great!
