### ISSUE TITLE
beam search strategy may conflicts with negative constraints decoding

### ISSUE THREAD

**Issue by wangpeng138375** [awslabs/sockeye#915]
Dose the argument of "--nbest-size" simply select topN hypothesis from the result of beam search? What's the difference between "nbest_size" and "beam_size"? I'm confused by the post-processing under this argument, which may damage the result of negative **phrase** constraints decoding.

**Comment by tdomhan** [comment]
The beam size is how many hypothesis are kept in search whereas the nbest size is how many are returned after search. In fact nbest size must therefore be smaller than beam size (see [here](https://github.com/awslabs/sockeye/blob/master/sockeye/inference.py#L725)). Can you ellaborate on the concerns about post-processing?

**Comment by wangpeng138375** [comment]
I think there is a bug as for negative phrase constraints decoding. 
Take follows as example:
beam_size =3, phrase constraint is [a, b]
at **t** step: the model select top_3 words of [b, a, c] for hypothesis , and the negative trie track the state in in current words order;
at **t+1** step: the model select top_3 words of [b, d, c] for hypothesis , and the negative trie track the state in current words order;
Than, if the beam_search select the second word of a at time **t** step , and all of three words of [b, d, c] at **t+1** step,  the  hypothesis will be [ab, ad, ac] . The negative state tracking will fail under this situation , and the phrase of **ab** will not be avoided any more. 
Do I make this bug clear?

**Comment by wangpeng138375** [comment]
When adding `avoid_states.consume(best_word_indices)` at beam_search.py[#L695](https://github.com/awslabs/sockeye/blob/master/sockeye/beam_search.py#L695), it will work  when beam_size ==1, but fail when beam_size > 1

**Comment by bricksdont** [comment]
For constraints, as far as I know, negative or not, only the best hypothesis in the beam is guaranteed to satisfy all constraints. Other hypotheses in the beam, for instance the ones you can output with `--nbest-list`, are not guaranteed to do that.

Does this perhaps answer your question?

**Comment by wangpeng138375** [comment]
I don't think so. And I think the problem lies in the mismatch between hypothesises selection of beam and the state tracking of negative constraints. The order of hypothesises in beam is changing depends on everystep words scores, but the corresponding order of negative constraints states do not change.  This is the problem.

**Comment by fhieber** [comment]
I think you are right, the current version neither sorts the elements in the `AvoidBatch` instance, nor does it call `AvoidBatch.consume()` in beam search. I am not very familiar with this code but it looks like this is not working correctly currently.
