### ISSUE TITLE
Model trained on 2.1.21 not compatible with 2.3.2

### ISSUE THREAD

**Issue by jlquinn** [awslabs/sockeye#916]
I trained a sockeye model using sockeye 2.1.21 and mxnet-cu101 1.7.0 on a v100.  I then installed sockeye 2.3.2 and tried to translate with this model.  I am getting the following error:

(pt15) [jlquinn@dccxc335 base.75.1]$ sockeye-translate --config args.yaml --input /dccstor/jmws1/ws/zhen/20191025/data/test/newstest2018.zh.txt.bpe.rbm -o nt18.out.test -m $PWD --batch-size 100
Traceback (most recent call last):
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/bin/sockeye-translate", line 5, in <module>
    from sockeye.translate import main
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/translate.py", line 28, in <module>
    from sockeye.lexicon import TopKLexicon
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/lexicon.py", line 26, in <module>
    from . import arguments
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/arguments.py", line 26, in <module>
    from . import data_io
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/data_io.py", line 36, in <module>
    from . import vocab
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/vocab.py", line 26, in <module>
    from . import utils
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/utils.py", line 44, in <module>
    NDarrayOrSymbol = Union[mx.nd.NDArray, mx.sym.Symbol]
AttributeError: module 'mxnet' has no attribute 'nd'

**Comment by jlquinn** [comment]
After uninstalling and reinstalling, I now get the following:

sockeye.utils.SockeyeError: Given major version (2.1.21) does not match major code version (2.3.2)

**Comment by tdomhan** [comment]
Unfortunately, we don't have any tools to automatically convert. If you wanted to convert you'd need to potentially remap parameter names. What issues are you seeing when downgrading to 2.1.x?

**Comment by jlquinn** [comment]
Here's what happens when I try to install sockey 2.1.21.  First I re-download the requirements file for tag 2.1.21.  Then I run pip with --no-cache-dir to prevent picking up anything else.

It seems that it wants mxnet-cu101mkl.  At the bottom I show the results from pip search.  1.6.0.post0 doesn't match up with 1.6.0 and installation fails.


(pt15) [jlquinn@dccxl010 tfbase]$ pip list
Package     Version
----------- -------------------
certifi     2020.6.20
chardet     3.0.4
graphviz    0.8.4
idna        2.10
mkl-fft     1.2.0
mkl-random  1.1.1
mkl-service 2.3.0
numpy       1.18.5
pip         20.1.1
PyYAML      5.3.1
requests    2.24.0
scipy       1.5.0
setuptools  47.3.1.post20200622
six         1.15.0
torch       1.5.1
typing      3.7.4.3
urllib3     1.25.10
wheel       0.34.2

(pt15) [jlquinn@dccxl010 tfbase]$ wget https://raw.githubusercontent.com/awslabs/sockeye/2.1.21/requirements/requirements.gpu-cu101.txt
--2020-11-24 14:14:41--  https://raw.githubusercontent.com/awslabs/sockeye/2.1.21/requirements/requirements.gpu-cu101.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 91 [text/plain]
Saving to: ‘requirements.gpu-cu101.txt.1’

100%[================================================================================================================================>] 91          --.-K/s   in 0s      

2020-11-24 14:14:41 (6.24 MB/s) - ‘requirements.gpu-cu101.txt.1’ saved [91/91]

(pt15) [jlquinn@dccxl010 tfbase]$ mv requirements.gpu-cu101.txt.1 requirements.gpu-cu101.txt.2.1.21

(pt15) [jlquinn@dccxl010 tfbase]$ cat requirements.gpu-cu101.txt.2.1.21 
pyyaml>=5.1
mxnet-cu101mkl==1.6.0
numpy>1.16.0,<2.0.0
typing
portalocker
sacrebleu==1.4.10


(pt15) [jlquinn@dccxl010 tfbase]$ pip --no-cache-dir install sockeye==2.1.21 --no-deps -r requirements.gpu-cu101.txt.2.1.21 
Collecting sockeye==2.1.21
  Downloading sockeye-2.1.21-py3-none-any.whl (206 kB)
     |████████████████████████████████| 206 kB 16.9 MB/s 
Requirement already satisfied: pyyaml>=5.1 in /dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages (from -r requirements.gpu-cu101.txt.2.1.21 (line 1)) (5.3.1)
ERROR: Could not find a version that satisfies the requirement mxnet-cu101mkl==1.6.0 (from -r requirements.gpu-cu101.txt.2.1.21 (line 2)) (from versions: 1.4.1, 1.5.0, 1.5.1, 1.5.1.post0, 1.6.0.post0)
ERROR: No matching distribution found for mxnet-cu101mkl==1.6.0 (from -r requirements.gpu-cu101.txt.2.1.21 (line 2))


(pt15) [jlquinn@dccxl010 tfbase]$ pip search mxnet|grep cu101
mxnet-cu101 (1.7.0)                             - MXNet is an ultra-scalable deep learning framework. This version uses CUDA-10.1.
mxnet-cu101mkl (1.6.0.post0)                    - MXNet is an ultra-scalable deep learning framework. This version uses CUDA-10.1 and MKLDNN.

**Comment by jlquinn** [comment]
OK it looks like just changing requirements.gpu-cu101.txt to have:
```
mxnet-cu101mkl==1.6.0.post0
```
will solve my issue

**Comment by bricksdont** [comment]
Yes exactly, 1.6.0 is not available on Pypi anymore.
