### ISSUE TITLE
possible bug in LearningRateSchedulerPlateauReduce in lr_scheduler.py

### ISSUE THREAD

**Issue by tuglat** [awslabs/sockeye#919]
In LearningRateSchedulerPlateauReduce we have the method definition:

    def __repr__(self):
        return "LearningRateSchedulerPlateauReduce(reduce_factor=%.2f, " \
               "reduce_num_not_improved=%d)" % (self.reduce_factor, self.num_not_improved)

Shouldn't this be

    def __repr__(self):
        return "LearningRateSchedulerPlateauReduce(reduce_factor=%.2f, " \
               "reduce_num_not_improved=%d)" % (self.reduce_factor, self.reduce_num_not_improved)

**Comment by fhieber** [comment]
Correct good catch! Do you want to submit a PR?

**Comment by tuglat** [comment]
I have submitted a PR, but it fails the pylint check in code that is outside my (very trivial) change.
