### ISSUE TITLE
Bug: During training, if  --keep-last-params is too small, construction of model averages can be corrupted

### ISSUE THREAD

**Issue by tuglat** [awslabs/sockeye#928]
if  --keep-last-params is set for 4, for example, and we want to construct an average of the 4 best parameters sets, it is very likely that the true 4 best parameters sets are not all saved in those kept around by --keep-last-params.

**Comment by fhieber** [comment]
Hi @tuglat,

Thanks for bringing this up. I am not yet convinced that the above issue is really a bug, and not more a configuration issue by the user. I agree that the interaction between parameter averaging and `--keep-last-params` is a bit obscure and maybe it is worth adding a warning to parameter averaging if the set to select parameters from is very small.

**Comment by tuglat** [comment]
One of the reasons for only keeping N of the past parameters sets is to save storage space. Keeping all of the parameters sets as we go can eat up quite a bit of disk space. Instead of a bug, then, this could be considered a performance improvement, where we can ensure that we only keep around as many of the N-best that we actually need.

**Comment by tuglat** [comment]
fixed w/ pull request #929
