### ISSUE TITLE
Unable to do ninja build

### ISSUE THREAD

**Issue by thakurritesh19** [awslabs/sockeye#938]
While building the Docker image provided, I keep getting this error when Docker runs the ninja build command: ninja -j$(nproc)

Error:
```
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
Now I can google this too but check this out:
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFLastDirectory@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFWriteEncodedStrip@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'

//usr/lib/libgdal.so.20: undefined reference to `TIFFSetDirectory@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFReadScanline@LIBTIFF_4.0'
//usr/lib/libgdal.so.20: undefined reference to `TIFFNumberOfTiles@LIBTIFF_4.0'
```

I get similar errors for other libraries as well. While I can go on and list those libraries as well, there are a lot.

I am trying to understand if these are a result of similar libraries already installed in my docker's base image ? (Base Image used: 10.0-cudnn7-devel-ubuntu18.04)

**Comment by tdomhan** [comment]
What's the exact command you are running to get this error? have you tried other base images (Dockerfile.gpu currently refers to `cuda:10.1-devel-ubuntu18.04` for example)?

**Comment by mjdenkowski** [comment]
Closing for now as this applies to an older version of Sockeye.
