### ISSUE TITLE
Multi GPU training consistenly segfaults

### ISSUE THREAD

**Issue by aijanai** [awslabs/sockeye#943]
Hi,
when launching a multi GPU training, it often segfaults after checkpointing
```
[INFO:sockeye.training] E=50 B=20950    s/sec=395.30 tok/sec=31624.13 u/sec=6.18        ppl=5.754722
[INFO:sockeye.training] E=50 B=21000    s/sec=426.09 tok/sec=31837.74 u/sec=6.66        ppl=5.754165
[INFO:root] Saved params to "sockeye-transformer-head-ablation-1/params.00007"
[INFO:sockeye.training] Checkpoint [7]  Updates=21000 Epoch=50 Samples=1344000 Time-cost=462.375 Updates/sec=6.488
[INFO:sockeye.training] Checkpoint [7]  Train-ppl=5.754165

Segmentation fault: 11

terminate called without an active exception
./train-suggester-heads-ablation.sh: line 3: 49780 Aborted                 (core dumped) python3 -m sockeye.train --batch-size 128 --batch-type sentence --device-ids 0 1 2 3 --checkpoint-interval 3000 --decode-and-evaluate 100 --decoder ssru_transformer --embed-dropout 0.2 --initial-learning-rate 0.0001 --keep-last-params 2 --learning-rate-reduce-factor 0.7 --learning-rate-reduce-num-not-improved 2 --encoder transformer --max-num-checkpoint-not-improved 4 --max-seq-len 500 --optimized-metric bleu --optimizer adam --num-embed 512:512 --num-layers 1:1 --transformer-attention-heads $i:$i --source train.26208.diff --target train.26208.msg --output $MODEL_DIR --validation-source test.3000.diff --validation-target test.3000.msg
```
env is python 3.7 with conda, requirements:
```
pyyaml>=5.1
mxnet-cu100==1.7.0
numpy>1.16.0,<2.0.0
portalocker
sacrebleu==1.4.14
dataclasses
rouge
```

**Comment by aijanai** [comment]
Forgot to report the hardware: 4x Tesla P100 16GB

**Comment by aijanai** [comment]
Additional detail:

the log indicates that it doesn't perform the actual validation after saving the parameters, as part of the checkpointing:

```
[2021-03-14:13:23:50:INFO:sockeye.training:_create_checkpoint] Checkpoint [2]	Train-ppl=21.071828
[2021-03-14:13:23:55:INFO:sockeye.training:_evaluate] Checkpoint [2]	Validation-ppl=446.094805	Validation-bleu=0.318714	Validation-chrf=0.368589	Validation-rouge1=0.320084	Validation-rouge2=0.217728	Validation-rougel=0.297544	Validation-length-ratio-mse=0.872531	Validation-avg-sec-per-sent=0.010777	Validation-decode-walltime=1.077699
[2021-03-14:13:23:55:INFO:sockeye.training:_determine_improvement] Validation-bleu improved to 0.318714 (delta=0.038669).
```
Perhaps something in the validation procedure?

**Comment by fhieber** [comment]
Hi @aijanai,

it seems like you use BLEU to determine early-stopping (``--optimized-metric bleu``?). In order to compute BLEU at checkpoints, Sockeye decodes (a subset of) the validation data at every checkpoint. This may require additional GPU memory. Is it possible that you are running out of GPU memory? You can try lowering the training batch size to reduce memory.

**Comment by aijanai** [comment]
Perfectly legit, but why segfaulting instead of "failed malloc" or similar?

**Comment by fhieber** [comment]
Good question, the segfault is likely happening inside MXNet over which we don't have direct control.

**Comment by aijanai** [comment]
Thanks mates

**Comment by bricksdont** [comment]
> Perfectly legit, but why segfaulting instead of "failed malloc" or similar?

With Mxnet, out of memory on GPU can lead to many different exceptions unfortunately. I also think reducing the batch size / monitoring GPU memory usage could be worth a try. Would be great if you could confirm that GPU OOM is not an issue.
