### ISSUE TITLE
Docker image fails because of python 3.6 not being supported

### ISSUE THREAD

**Issue by AbdallahNasir** [awslabs/sockeye#956]
The docker base image is nvidia/cuda:10.1-devel-ubuntu18.04 which uses python 3.6 which is not supported anymore starting from 2.3.14.

**Comment by mjdenkowski** [comment]
Thanks for reporting this issue.

#957 updates the Docker builds for GPUs and CPUs.

Best,
Michael

**Comment by mjdenkowski** [comment]
#957 is merged.
