### ISSUE TITLE
[Question] How to train sockeye in multi machine?

### ISSUE THREAD

**Issue by Adnios** [awslabs/sockeye#967]
I have read the document of sockeye. It seems that sockeye does not support multi machine distributed training. I wonder if there is a way to achieve it?

**Comment by mjdenkowski** [comment]
Hi Adnios,

Sockeye supports training on any number of GPUs and nodes using Horovod.

You can convert the recipe for [multi-GPU training](https://github.com/awslabs/sockeye/tree/master/sockeye_contrib/docker#example-distributed-training-with-horovod-and-automatic-mixed-precision) to multi-node training by editing `horovodrun` command to specify multiple hosts, similar to [this example](https://horovod.readthedocs.io/en/stable/running_include.html).

While multi-node training provides access to more GPUs, it also introduces more overhead for sharing data across GPUs.  In the experiments for the [2020 Sockeye paper](https://arxiv.org/abs/2008.04885), we found that training on 8 GPUs on a single node delivered the best value.

Best,
Michael
