### ISSUE TITLE
Docker Sockey GPU: OSError: libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by RamoramaInteractive** [awslabs/sockeye#974]
According to the README of your Github repository I created a Sockeye-GPU image on Docker. On the Docker image I wanted to train the model from this page:

https://aws.amazon.com/blogs/machine-learning/train-neural-machine-translation-models-with-sockeye/

Unfortunately, I receive this error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/sockeye/sockeye/train.py", line 30, in <module>
    import mxnet as mx
  File "/opt/mxnet/python/mxnet/__init__.py", line 23, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/opt/mxnet/python/mxnet/context.py", line 23, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/opt/mxnet/python/mxnet/base.py", line 351, in <module>
    _LIB = _load_lib()
  File "/opt/mxnet/python/mxnet/base.py", line 342, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcuda.so.1: cannot open shared object file: No such file or directory
```

I have no idea why this happened and what to do.

**Comment by mjdenkowski** [comment]
The Sockeye GPU image is based on Nvidia's optimized MXNet image that includes CUDA and other libraries.

It runs with [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) which automatically configures GPU support for images.

Have you tried running the image with nvidia-docker?

**Comment by RamoramaInteractive** [comment]
No, I haven't tested with nvidia-docker yet.

**Comment by RamoramaInteractive** [comment]
I'm working on Windows 10. Can I also install nvidia-docker or only on a Linux distribution?

**Comment by mjdenkowski** [comment]
It's generally easiest to install nvidia-docker when you're running Linux natively: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

Nvidia also provides documentation for installing CUDA and nvidia-docker via Windows Subsystem for Linux: https://docs.nvidia.com/cuda/wsl-user-guide/index.html
