### ISSUE TITLE
Step-By-Step Tutorial is not available anymore

### ISSUE THREAD

**Issue by RamoramaInteractive** [awslabs/sockeye#978]
Are there other tutorials for Sockeye?

The link https://github.com/awslabs/sockeye/tree/main/tutorials is down and I didn't find other tutorials for Sockeye.

**Comment by fhieber** [comment]
Hi @RamoramaInteractive ,

`https://github.com/awslabs/sockeye/tree/main/docs/tutorials` still exists and the Github page seems to work fine: `https://awslabs.github.io/sockeye/tutorials.html`.

Can you point to the page/place that refers to the link that you found not working? Thank you.

**Comment by RamoramaInteractive** [comment]
@fhieber 

The first link works, the second link shows me an 404 Not Found Error.
All the links in https://github.com/awslabs/sockeye/blob/main/docs/tutorials.md also show me an 404 File Not Found Error. :(

**Comment by fhieber** [comment]
Weird, https://awslabs.github.io/sockeye/tutorials.html does work fine for me.
Can you access the github.io page: https://awslabs.github.io/sockeye/tutorials.html ? From there the Tutorials section is accessible.

There might be an issue with how links are resolved when looking at the Github.io page and when browsing the `.md` files directly in the repository.

**Comment by RamoramaInteractive** [comment]
Now this works for me! Thank you, @fhieber.

Beside this repository, are there other tutorials you would also recommend?
I'm looking for Sockeye code to build a transformer model. I want to replicate the transformer model from the paper Training Neural Machine Translation To Apply Terminology Constraints (Link: https://arxiv.org/abs/1906.01105).

**Comment by fhieber** [comment]
I am not aware of other tutorials for Sockeye. The paper you are referring to is using the source factor feature in Sockeye. There is some documentation [here](https://awslabs.github.io/sockeye/training.html) on how to use them.
