### ISSUE TITLE
WMT German to English news translation - Missing Metrics and Module 'apply_bpe' not found

### ISSUE THREAD

**Issue by RamoramaInteractive** [awslabs/sockeye#981]
I have two problems related with the WMT German to English news translation tutorial.

1. After training the WMT Model from the Tutorial 2 https://awslabs.github.io/sockeye/tutorials/wmt.html I noticed, that the _'metrics'_ folder was not generated inside the _wmt_model_ folder. Is the metrics folder only generated when I set `--optimized-metric bleu` as parameter or is an error happened while training?

2. If I want to do the Translation as described with the code
    ```
    echo "er ist so ein toller Kerl und ein Familienvater ." | \
            python -m apply_bpe -c bpe.codes --vocabulary bpe.vocab.en \
            --vocabulary-threshold 50 | \
            python -m sockeye.translate -m wmt_model 2>/dev/null | \
            sed -r 's/@@( |$)//g'  
    ```
    I get the error message `ModuleNotFoundError: No module named 'apply_bpe'`. After installing subwort-nmt via pip, it was working,     but I don't receive nothing. What could be the source of the error?

**Comment by fhieber** [comment]
1. there is no `metrics` folder but a `metrics` file that is generated inside the model directory during training. It contains various training-related metrics, such as perplexity or BLEU (if `--decode-and-evaluate` is not set to 0). `--optimized-metric` is only relevant if you are using early-stopping to control length of training. If set to `bleu` training will stop if the BLEU score on the validation set does not improve over some time. This only works if you have `--decode-and-evaluate != 0`.
2. The tutorial hasn't been updated in a while. You should check if the first part of your command, `echo "er ist so ein toller Kerl und ein Familienvater ." | \
        python -m apply_bpe -c bpe.codes --vocabulary bpe.vocab.en \
        --vocabulary-threshold 50` produces subword-tokenized output. If it does, remove `2>/dev/null` to see whether sockeye throws an error.

**Comment by RamoramaInteractive** [comment]
Hi @fhieber,

1. My error, I meant `metrics` file. Thank you for the information. I think question number 1 is answered.
2. Yes, the first part of the command produces `er ist so ein tol@@ ler Ker@@ l und ein Familien@@ v@@ ater .`. After removing `2>/dev/null` I got the following error message:

```
/data/subword-nmt/apply_bpe.py:396: DeprecationWarning: this script's location has moved to /data/subword-nmt/subword_nmt. This symbolic link will be removed in a future version. Please point to the new location, or install the package and use the command 'subword-nmt'
  DeprecationWarning
/data/subword-nmt/apply_bpe.py:416: ResourceWarning: unclosed file <_io.TextIOWrapper name='bpe.codes' mode='r' encoding='UTF-8'>
  args.codes = codecs.open(args.codes.name, encoding='utf-8')
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/data/subword-nmt/apply_bpe.py:422: ResourceWarning: unclosed file <_io.TextIOWrapper name='bpe.vocab.en' mode='r' encoding='UTF-8'>
  args.vocabulary = codecs.open(args.vocabulary.name, encoding='utf-8')
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[INFO:sockeye.utils] Sockeye version 2.3.24, commit 35dd717a80ae1f04128d79bd0bcf340e2e9d1427, path /opt/conda/envs/rapids/lib/python3.7/site-packages/sockeye/__init__.py
[INFO:sockeye.utils] MXNet version 1.8.0, path /opt/conda/envs/rapids/lib/python3.7/site-packages/mxnet/__init__.py
[INFO:sockeye.utils] Command: /opt/conda/envs/rapids/lib/python3.7/site-packages/sockeye/translate.py -m wmt_model
[INFO:sockeye.utils] Arguments: Namespace(avoid_list=None, batch_size=1, beam_search_stop='all', beam_size=5, brevity_penalty_constant_length_ratio=0.0, brevity_penalty_type='none', brevity_penalty_weight=1.0, bucket_width=10, checkpoints=None, chunk_size=None, config=None, device_ids=[-1], disable_device_locking=False, dtype=None, ensemble_mode='linear', env=None, greedy=False, input=None, input_factors=None, json_input=False, length_penalty_alpha=1.0, length_penalty_beta=0.0, lock_dir='/tmp', loglevel='INFO', loglevel_secondary_workers='INFO', max_input_length=None, max_output_length=None, max_output_length_num_stds=2, mc_dropout=False, models=['wmt_model'], nbest_size=1, no_hybridization=False, no_logfile=False, omp_num_threads=None, output=None, output_type='translation', prevent_unk=False, quiet=False, quiet_secondary_workers=False, restrict_lexicon=None, restrict_lexicon_topk=None, sample=None, seed=None, softmax_temperature=None, strip_unknown_words=False, use_cpu=False)
[ERROR:root] Uncaught exception
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/rapids/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/sockeye/translate.py", line 272, in <module>
    main()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/sockeye/translate.py", line 46, in main
    run_translate(args)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/sockeye/translate.py", line 79, in run_translate
    exit_stack=exit_stack)[0]
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/sockeye/utils.py", line 363, in determine_context
    "No GPUs found, consider running on the CPU with --use-cpu ")
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/sockeye/utils.py", line 136, in check_condition
    raise SockeyeError(error_message)
sockeye.utils.SockeyeError: No GPUs found, consider running on the CPU with --use-cpu


```

**Comment by fhieber** [comment]
Add `--use-cpu` to the Sockeye command. I'll update the tutorial to conform to the assumption made at the beginning of the tutorial regarding commands on CPU/GPU.

**Comment by RamoramaInteractive** [comment]
I did it with the new command

`echo "er ist so ein toller Kerl und ein Familienvater ." | python -m apply_bpe -c bpe.codes --vocabulary bpe.vocab.en --vocabulary-threshold 50 | python -m sockeye.translate --use-cpu -m wmt_model | sed -r 's/@@( |$)//g'`

But my new error from this tutorial is

`sockeye.utils.SockeyeError: No model parameter file found under wmt_model/params.best. This is either not a model directory or the first training checkpoint has not happened yet.`

During the training of the wmt model, no params-files were generated.

**Comment by fhieber** [comment]
If there is no `params.best` then your model did not train long enough until a checkpoint. You can check the log file in `wmt_model/log`. Not having a checkpoint though is consistent with your experience of not seeing the `metrics` file either.

**Comment by RamoramaInteractive** [comment]
I noticed in the log file and while retraining the model the following outputs:

```
[INFO:sockeye.utils] Fixed parameters:
['decoder_transformer_target_pos_embed_weight [(96, 512), float32]',
 'encoder_transformer_source_pos_embed_weight [(96, 512), float32]']
[INFO:sockeye.loss] Loss: cross-entropy | weight=1.00 | metric: perplexity (ppl) | output_name: 'logits' | label_name: 'target_label'
**[INFO:sockeye.training] mxboard not found. Consider 'pip install mxboard' to log events to Tensorboard.**
[INFO:sockeye.inference] Translator (1 model(s) beam_size=5 algorithm=BeamSearch, beam_search_stop=all max_input_length=95 nbest_size=1 ensemble_mode=None max_batch_size=16 avoiding=0 dtype=float32 softmax_temperature=None)
[INFO:sockeye.checkpoint_decoder] Created CheckpointDecoder(max_input_len=-1, beam_size=5, num_sentences=500)
**[INFO:sockeye.training] Early stopping by optimizing 'perplexity'**
[INFO:sockeye.model] Saved model config to "wmt_model/config"
[INFO:sockeye.training] Training started.
```
After that my model stops training. According to _pip freeze_ and _pip3 freeze_, I have already installed `mxboard==0.1.0.`
What does `[INFO:sockeye.training] Early stopping by optimizing 'perplexity'` mean?

I followed all the steps in tutorial 2 from start to training.

**Comment by fhieber** [comment]
`mxboard` is not required. `INFO:sockeye.training] Early stopping by optimizing 'perplexity'` means that your training will stop once perplexity does not improve over a number of checkpoints. But if the above snippet is the last part of your logfile, training hasn't even started really.
It looks like you are training on a CPU and the above model hasn't even completed the first 50 batches to output another log line. You probably need to wait much longer :)

**Comment by RamoramaInteractive** [comment]
Yes, this snippet is the last part above. I trained my model on a Tesla GPU server with a Nvidia-Docker, but I have no idea why it's still not working. 

Alright, I try this time with CPU.

**Comment by RamoramaInteractive** [comment]
In CPU it's working, but it takes a lot of times.  I see the epochs and lines. 

What could be possible reasons, that Sockeye doesn't continued training on the GPU? The Sockeye Version for Cuda 10 is installed.

**Comment by RamoramaInteractive** [comment]
I think I found a solution for my problem.
If I rewrite the Sockeye code like in the tutorial https://awslabs.github.io/sockeye/tutorials/wmt_large.html then it starts to train as if by magic.

Thank you for you help and I think this issue can be closed.
