### ISSUE TITLE
WMT 2014 English-German - CUDA out of memory

### ISSUE THREAD

**Issue by RamoramaInteractive** [awslabs/sockeye#988]
After executing the code to start the training from the [WMT 2014 English-German tutorial ](https://awslabs.github.io/sockeye/tutorials/wmt_large.html)

```
sockeye-train \
    --prepared-data prepared --validation-source dev.en.bpe \
    --validation-target dev.de.bpe --output model --num-layers 6 \
    --transformer-model-size 1024 --transformer-attention-heads 16 \
    --transformer-feed-forward-num-hidden 4096 --amp --batch-type max-word \
    --batch-size 5000 --update-interval 80 --checkpoint-interval 500 \
    --max-updates 15000 --optimizer-betas 0.9:0.98 \
    --initial-learning-rate 0.06325 \
    --learning-rate-scheduler-type inv-sqrt-decay --learning-rate-warmup 4000 \
    --seed 1
```

I received the following error message:

> RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.78 GiB total capacity; 2.61 GiB already allocated; 31.19 MiB free; 2.63 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I solved this problem by reducing the batch size. Is there another solution for this problem? Is it problematic if I reduce the batch size?

Edit: I tested it again, and even the solution approach of reducing the batch size isn't working anymore. :(

What does the error `Cannot import NVIDIA Apex optimizers (FusedAdam, FusedSGD)` mean?

**Comment by mjdenkowski** [comment]
Lowering the batch size is a good first step to reducing memory usage.  If you decrease `--batch-size`, you can increase `--update-interval` to keep the effective batch size (update size) the same.  For example, `--batch-size 5000 --update-interval 80` is equivalent to `--batch-size 2500 --update-interval 160`.

[NVIDIA Apex](https://github.com/NVIDIA/apex) is an optional library.  If it's installed, Sockeye automatically uses its faster optimizer implementations.  If not, Sockeye uses the standard PyTorch implementations.

**Comment by RamoramaInteractive** [comment]
Thank you! This is very useful!

This also means that NVIDIA APEX is not obligated. I have an MXNET Container on the Tesla-Server which supports CUDA 10.2.
If I install the PyTorch version for [CUDA 10.2](https://pytorch.org/get-started/locally/) then Sockeye doesn't work, because it's the version **torch==1.8.2** which is not compatible to torch==1.10.0.

Is there a GPU version for torch==1.10.0?

**Comment by mjdenkowski** [comment]
If you visit https://pytorch.org/get-started/locally/, you can select the version of PyTorch that matches your environment and copy the installation command.

**Comment by RamoramaInteractive** [comment]
For Unix the installation command is 

`pip3 install torch torchvision torchaudio`, 

but for windows it's `pip3 install torch==1.10.0+cu102 torchvision==0.11.1+cu102 torchaudio===0.10.0+cu102 -f https://download.pytorch.org/whl/cu102/torch_stable.html` . I think, It's not a big difference.

Thank you for your help.
