### ISSUE TITLE
sockeye inference in the browser

### ISSUE THREAD

**Issue by AmitMY** [awslabs/sockeye#998]
It would be extremely useful to perform inference directly in the browser, offline, without a server.
Such a feature would distinguish sockeye from most other MT frameworks.

It might be an option to work with `tvm` - https://tvm.apache.org/2020/05/14/compiling-machine-learning-to-webassembly-and-webgpu for the pytorch models if that is the way sockeye is going forward.

Another option, if you don't want to use `tvm` -  as MXNet is written I C++, it should be able to compile to WebAssembly and run natively in the browser.

**Comment by tdomhan** [comment]
Running Sockeye in the browser would certainly be great. There are no official plans for this, but any contribution in this direction is of course be welcome!
Note that with v3 Sockeye is based on PyTorch:
https://github.com/awslabs/sockeye/blob/main/README.md#version-300--backwards-compatibility

**Comment by AmitMY** [comment]
Cool. Btw, the `tvm` supports pytorch.
