### ISSUE TITLE
Correct parameters and training model from the paper "Training Neural Machine Translation To Apply Terminology Constraints"

### ISSUE THREAD

**Issue by RamoramaInteractive** [awslabs/sockeye#999]
According to the paper [Training Neural Machine Translation To Apply Terminology Constraints
](https://arxiv.org/pdf/1906.01105.pdf) I added the given parameters from the appendix in order to create their described model.

The Train data are the given _Europarl_ and the validation (dev) data are the _News-Commentary_ data.
I processed the data in the same way as in the [Multilingual Zero-shot Translation IWSLT 2017
](https://github.com/awslabs/sockeye/blob/main/docs/tutorials/multilingual.md), because it's the same way of processing like in this paper. For the batch-size I chose a higher parameter.

Do you agree with the parameters and data processing according to the paper or did I forget something?
I know I could leave out some parameters, because their values are already default, but I want to make sure that these parameters are all complete.

```
sockeye-train -d train_data \
-vs data/news-commentary-v13.tag.src \
-vt data/news-commentary-v13.tag.trg \
--shared-vocab \
-o amazon_model \
--transformer-attention-heads 8:8 \
--transformer-activation-type 'relu':'relu' \
--transformer-dropout-act 0.1:0.1 \
--transformer-dropout-attention 0.1:0.1 \
--transformer-dropout-prepost 0.1:0.1 \
--dtype float32 \
--transformer-feed-forward-num-hidden 2048:2048 \
--max-seq-len 101:101 \
--transformer-model-size 512:512 --num-layers 2:2 \
--transformer-positional-embedding-type fixed \
--transformer-postprocess dr:dr \
--transformer-preprocess n:n \
--embed-dropout 0.0:0.0 \
--label-smoothing 0.1 \
--loss cross-entropy \
--num-words 32302:32302 \ 
--num-embed 512:512 \
--source-factors-num-embed 1 \ 
--target-factors-num-embed 1 \
--min-num-epochs 50 \
--max-num-epochs 100 \
--batch-size 560 

```

**Comment by RamoramaInteractive** [comment]
Regarding Source Factoring: https://awslabs.github.io/sockeye/training.html#source-factors

If I want to translate a single sentence with a sockeye model trained with source-factors, how can I do this (like in the paper above)?

Should it be more like this:

```
echo "The|O boy|O ate|O the|O waff@@|B le|E .|O." | \
  python -m apply_bpe -c bpe.codes --vocabulary bpe.vocab.de \
                                   --vocabulary-threshold 50 | \
  sockeye-translate -m source-factor-model 2>/dev/null | \
  sed -r 's/@@( |$)//g'
```

Does Fairseq also support Source-Factoring?

**Comment by fhieber** [comment]
You should not apply BPE after providing source factors. Source factors should be added to the bpe-ed input that is fed into Sockeye. In your command above your echo input already seems to be BPE-tokenized (since it contains '@@' markers).

**Comment by RamoramaInteractive** [comment]
So, this means if my echo input is already tokenized I just need to write this:

```
echo "The|O boy|O ate|O the|O waff@@|B le|E .|O." | \
  sockeye-translate -m source-factor-model 2>/dev/null | \
  sed -r 's/@@( |$)//g'
```
Do I need more flags like "--source" or is this sufficient?
How can I apply "Train-By-Replace" and "Train-By-Append"? 

Are other feature lines possible like 

`0000120`

instead of

`O O O O B E O`?

**Comment by fhieber** [comment]
if you use the `|` annotation, Sockeye will automatically parse the input. In this case it will detect 1 factor and will check if the model is also trained with one source factor. If you provide more or less factors than at training time for the model, an error will be thrown.
What you use as factors is up to you, but you need to do this at training time.

**Comment by RamoramaInteractive** [comment]
Do I need more flags like "--source" or is this sufficient?
How can I apply "Train-By-Replace" and "Train-By-Append"?

**Comment by RamoramaInteractive** [comment]
Thank you for this information. I will keep an eye on the training parameters. 👍

What about with the two other questions above?

**Comment by fhieber** [comment]
For detailed questions on the paper you might want to contact the authors directly. 
To provide source factors during training for the training and validation data, you need to add `--source-factors` and `--source-validation-factors` to the `sockeye.train` command.

**Comment by RamoramaInteractive** [comment]
I've contacted the authors.

One more comprehension questions before this issue can be closed:

Assuming I would train this Copy Behaviour model with its Source Factors with Europarl.v7 training data. For --source-factors do I need a copy of the Europarl.v7 training data and replace the tokens with Token Parallel or what does such a sample file look like?

Which specification do I have to make to the --validation-source-factors parameter?

If I use as token parallels e.g. the numbers 0 (source words), 1 (source terms) and 2 (target terms), how do I have to annotate the data?

Do I need --target-factors?

**Comment by fhieber** [comment]
The requirements for files specified for `--source-factors` or `--validation-source-factors` are 
1. each of them have the same number of lines as the file(s) given to `--source` (and `--validation-source`),
2. they need to be 'token-parallel' to the file(s) given to `--source` (and `--validation-source`).

The latter means that if a sentence in `--source` file has 4 whitespace-separated tokens, the same line in the each of the files given to `--source-factors` also needs to have 4 whitespace-separated tokens. 
How these tokens look like and what kind of information they encode is totally up to you.

With `--validation-source-factors` you supply the factors for the validation set that is used during training to compute perplexity (and BLEU if the CheckpointDecoder is enabled). If you train a model with source factors, it always expects source factors. It cannot translate without these additional inputs.

For the paper you are referring to you don't need target factors. But the required format for these (length and token parallelism across files) is the same.

**Comment by RamoramaInteractive** [comment]
Thanks for your advice, @fhieber.

I found a solution how to replace in the training and validation data the tokens with token parallelism.
Maybe there is a better solution, but this one worked for me:

First I made copies of the training and validation data:

`cat file >> file_cp`

For the token parallelism I choose the following tokens: _0_ for _source words_, _1_ for _source terms_ and _2_ for `target terms`.

This means for me that the terms I would prefer to be translated would be replaced with 1. All the other words will be replaced with 0. As source terms I mostly prefer nouns and verbs. I use the stream edit to replace certain terms with 1 in the copy file:

`sed -i 's/term/1/gi' file_cp`

After that I replace all the other tokens with zeros, except 1:

`sed -Ei 's/\<(1)\>/\n&/g; s/(^| )\S+/\10/g; s/\n//g' file`

If I follow the steps above, a certain line from the training data would be token parallized like this (the examples is not tokenized and processed with BPE):

> **1)** Big data is a field that treats ways to analyze, systematically extract information from, or otherwise deal with data sets that are too large or complex to be dealt with by traditional data-processing application software.

> **2)** Big data is a _1_ that _1_ ways to analyze, systematically extract information from, or otherwise deal with _1 1_ that are too _1_ or _1_ to be dealt with by traditional _1 1 1_.

> **3)** _0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0_

What do you think of this approach so far?

When I prepared the data

```
sockeye-prepare-data \
    -s examples/translation/wmt17_en_de/train.en \
    -t examples/translation/wmt17_en_de/train.de --shared-vocab \
    -sf examples/translation/wmt17_en_de/s_train.en \
    --source-factors-use-source-vocab true \
    --word-min-count 2 --pad-vocab-to-multiple-of 8 --max-seq-len 95 \
    --num-samples-per-shard 10000000 --output prepared --max-processes $(nproc)  
```

and started the training

```
sockeye-train -d prepared \
-vs examples/translation/wmt17_en_de/valid.en \
-vt examples/translation/wmt17_en_de/valid.de \
--shared-vocab \
-o amazon_model \
--min-num-epochs 1 \
--max-num-epochs 1 \
--batch-size 560 \
--transformer-attention-heads 8:8 \
--transformer-activation-type 'relu':'relu' \
--transformer-dropout-act 0.1:0.1 \
--transformer-dropout-attention 0.1:0.1 \
--transformer-dropout-prepost 0.1:0.1 \
--transformer-feed-forward-num-hidden 2048:2048 \
--transformer-model-size 512 --num-layers 2:2 \
--transformer-positional-embedding-type fixed \
--transformer-preprocess n:n \
--transformer-postprocess dr:dr \
--target-factors-num-embed 1 \
--source-factors-num-embed 1 \
--dtype float32 \
--max-seq-len 101:101 \
--num-words 32302:32302 \
--num-embed 512:512 \
--label-smoothing 0.1 \
--embed-dropout 0.0:0.0 \
--loss cross-entropy \
--source examples/translation/wmt17_en_de/s_train.en \
--validation-source examples/translation/wmt17_en_de/s_valid.en
``` 

I get the error message:

> sockeye.utils.SockeyeError: Either specify a raw training corpus with --source and --target or a preprocessed corpus with --prepared-data.

If I train the model with raw data it works. Is there still a solution to preprocess all data with the source factors?

When the model is working and I want to test the translation with the sentence from the Sockeye website:
`The boy ate the waffle.`

then I should write something like this, right?

```
echo "The|0 boy|0 ate|0 the|0 waff@@|1 le|1 Waff@@|2 el|2 .|0" | \
  sockeye-translate -m source-factor-model 2>/dev/null | \
  sed -r 's/@@( |$)//g'

```

**Comment by fhieber** [comment]
You need to remove `--source examples/translation/wmt17_en_de/s_train.en \` from the `sockeye-train` command.

And you are specifying `--validation-source / -vs` twice with different files.

**Comment by RamoramaInteractive** [comment]
I removed the --source and the second --validation-source.

After preparing the data a new

```
sockeye-prepare-data \
    -s examples/translation/wmt17_en_de/train.en \
    -t examples/translation/wmt17_en_de/train.de --shared-vocab \
    -sf examples/translation/wmt17_en_de/s_train.en \
    --source-factors-use-source-vocab true \
    --word-min-count 2 --pad-vocab-to-multiple-of 8 --max-seq-len 95 \
    --num-samples-per-shard 10000000 --output prepared --max-processes $(nproc) 
```

and train them again

```
sockeye-train -d prepared \
-vs examples/translation/wmt17_en_de/valid.en \
-vt examples/translation/wmt17_en_de/valid.de \
--shared-vocab \
-o amazon_model \
--min-num-epochs 1 \
--max-num-epochs 1 \
--batch-size 560 \
--transformer-attention-heads 8:8 \
--transformer-activation-type 'relu':'relu' \
--transformer-dropout-act 0.1:0.1 \
--transformer-dropout-attention 0.1:0.1 \
--transformer-dropout-prepost 0.1:0.1 \
--transformer-feed-forward-num-hidden 2048:2048 \
--transformer-model-size 512 --num-layers 2:2 \
--transformer-positional-embedding-type fixed \
--transformer-preprocess n:n \
--transformer-postprocess dr:dr \
--target-factors-num-embed 1 \
--source-factors-num-embed 1 \
--dtype float32 \
--max-seq-len 101:101 \
--num-words 32302:32302 \
--num-embed 512:512 \
--label-smoothing 0.1 \
--embed-dropout 0.0:0.0 \
--loss cross-entropy 
```

I get the error:

> Mismatch in arguments for training continuation.
> Differing arguments: target, source, prepared_data.

**Comment by fhieber** [comment]
You need to provide a source factor file for your validation data.

**Comment by RamoramaInteractive** [comment]
> You need to provide a source factor file for your validation data.

That's right, I hadn't considered that at all. 🤦‍♂️

Here my correction:

```
sockeye-prepare-data \
    -s examples/translation/wmt17_en_de/train.en \
    -t examples/translation/wmt17_en_de/train.de --shared-vocab \
    -sf examples/translation/wmt17_en_de/s_train.en \
    --source-factors-use-source-vocab true \
    --word-min-count 2 --pad-vocab-to-multiple-of 8 --max-seq-len 95 \
    --num-samples-per-shard 10000000 --output prepared --max-processes $(nproc)  
```

I want to work with the token parallels 0 (source words), 1 (source terms) and 2 (target terms).
So the s_train.en file only consist of 0s and 1s.

The code to train the model looks like this

```
sockeye-train -d prepared \
-vs examples/translation/wmt17_en_de/valid.en \
-vt examples/translation/wmt17_en_de/valid.de \
--shared-vocab \
-o amazon_model \
--min-num-epochs 1 \
--max-num-epochs 1 \
--batch-size 560 \
--transformer-attention-heads 8:8 \
--transformer-activation-type 'relu':'relu' \
--transformer-dropout-act 0.1:0.1 \
--transformer-dropout-attention 0.1:0.1 \
--transformer-dropout-prepost 0.1:0.1 \
--transformer-feed-forward-num-hidden 2048:2048 \
--transformer-model-size 512 --num-layers 2:2 \
--transformer-positional-embedding-type fixed \
--transformer-preprocess n:n \
--transformer-postprocess dr:dr \
--target-factors-num-embed 1 \
--source-factors-num-embed 1 \
--dtype float32 \
--max-seq-len 101:101 \
--num-words 32302:32302 \
--num-embed 512:512 \
--label-smoothing 0.1 \
--embed-dropout 0.0:0.0 \
--loss cross-entropy \
--validation-source-factors examples/translation/wmt17_en_de/s_valid.en &
```

I trained only for one epoch.

If test the following terminology constraint

```
echo "The|0 boy|0 ate|0 the|0 waff@@|1 le|1 Waff@@|2 el|2 .|0" | \
  sockeye-translate -m source-factor-model 2>/dev/null | \
  sed -r 's/@@( |$)//g'
```

The output is

> Der Junge ist der Waffel Waffel .

I know I need more epochs to train, but is anything right I did?
I thought waff@@ le would be replaced with waff@@ el.

**Comment by RamoramaInteractive** [comment]
After reading the paper again I found out how to annotate the source data:
If you have e.g. a line of training data (before tokenization and BPE) like

> The boy ate the waffle.

you have to decide if you want to add the target term in the source data (Train-by-Append) or you replace the source term with the target term (Train-by-Replace).

Train-by-Appending

> The boy ate the waffle Waffel.

Train-by-Replace

> The boy ate the Waffel.

The next step is to create token parallel data of the source file:

Train-by-Appending (Token Parallels)

> The boy ate the waffle Waffel.
> 0 0 0 0 1 2 0

Train-by-Replace (Token Parallels)

> The boy ate the Waffel.
> 0 0 0 0 2 0

Then I can apply the tokenization and BPE.

After that I can test the model with

```
echo "The|0 boy|0 ate|0 the|0 waff@@|1 le|1 Waff@@|2 el|2 .|0" | \
  sockeye-translate -m source-factor-model 2>/dev/null | \
  sed -r 's/@@( |$)//g'
```

I think I finally understood the annotation process and the issue can be closed.

**Comment by fhieber** [comment]
Happy to hear it is working for you now.

**Comment by RamoramaInteractive** [comment]
According to Training Neural Machine Translation To Apply Terminology Constraints:

> We embed the three values of
> this additional stream into vectors of size 16 and
> concatenate them to the corresponding sub-word
> embeddings.

I need the parameter source-factors-num-embed, right?

`--source-factors-num-embed 16 `

Is my training code complete? Do I need further parameter, if my source factors are 0, 1 and 2?

```
sockeye-prepare-data \
    -s examples/translation/wmt17_en_de/x_train.en \
    -t examples/translation/wmt17_en_de/x_train.de --shared-vocab \
    -sf examples/translation/wmt17_en_de/y_train.en \
    --source-factors-use-source-vocab true \
    --word-min-count 2 --pad-vocab-to-multiple-of 8 --max-seq-len 95 \
    --num-samples-per-shard 10000000 --output prepared --max-processes $(nproc)  
```

```
sockeye-train -d prepared \
-vs examples/translation/wmt17_en_de/x_valid.en \
-vt examples/translation/wmt17_en_de/x_valid.de \
--shared-vocab \
-o term_constraint_model2 \
--overwrite-output \
--min-num-epochs 50 \
--max-num-epochs 100 \
--batch-size 560 \
--transformer-attention-heads 8:8 \
--transformer-activation-type 'relu':'relu' \
--transformer-dropout-act 0.1:0.1 \
--transformer-dropout-attention 0.1:0.1 \
--transformer-dropout-prepost 0.1:0.1 \
--transformer-feed-forward-num-hidden 2048:2048 \
--transformer-model-size 512 --num-layers 2:2 \
--transformer-positional-embedding-type fixed \
--transformer-preprocess n:n \
--transformer-postprocess dr:dr \
--source-factors-num-embed 16 \
--dtype float32 \
--max-seq-len 101:101 \
--num-words 32302:32302 \
--num-embed 512:512 \
--label-smoothing 0.1 \
--embed-dropout 0.0:0.0 \
--loss cross-entropy \
--keep-last-params 1 \
--cache-last-best-params 1 \
--validation-source-factors examples/translation/wmt17_en_de/y_valid.en 
```
I also need the target term in the reference.

> We hypothesize that the model
> will learn to use the provided terminology at training
> time if it holds true that when a terminology
> entry (ts; tt) is annotated in the source, the target
> side tt is present in the reference.

The target terms I used are not in the reference file, only source file. Is there a way to fix the model?
What would be an fast and easy way to annotate 10% of 3.000.000 lines of the source and target file?
